//! One learned older-prefix group-state / read channel above the frozen local prior.
//!
//! # What this is
//!
//! The frozen step-512 prior predicts `x[i+1]` from the local pair `(x[i-1], x[i])` only. This
//! component adds **one exact `2I` group register** summarising the *older* part of the same
//! bounded context, excluding that pair:
//!
//! ```text
//! q_i = product over j in [max(0, i-63), i-1)  of  gamma[ argmax A[x[j], :] ]
//! ```
//!
//! (`[start, end)` is Rust half-open.) An empty older prefix contributes **zero** residual. The
//! learned token-to-palette choice `A` has 8 offline floating logits per token; only the hard
//! argmax (lowest palette ID on ties) is exported, nibble-packed. The palette is a fixed,
//! data-independent set of 8 exact group elements containing identity and two noncommuting
//! generators, so its closure is the full 120-element group.
//!
//! # Served forward (hard, integer, multiplier-free)
//!
//! ```text
//! Z_total[v] = Z_parent[v] + ((sum_j Wcode[v,j] * Rcode[q,j]) << 8)
//! ```
//!
//! implemented as: read `h[j] = Rcode[q,j] << 5` and apply the ternary `Wcode` with output shift 3
//! (because `5 + 3 = 8`). The parent's `F = 10` remains the sole score-to-logit exponent, so each
//! residual code-sum unit is `2^8 * 2^-10 = 0.25` logit. Both maps are fixed-scale ternary tables
//! built with `TernaryLinear::from_packed` (no adaptive quantizer), so training, export/reload and
//! generation execute the identical integer forward.
//!
//! # Scope
//!
//! This register is a **bounded coalescing summary**, not exact memory, a semantic metric, or an
//! independent golden/Galois companion. Pure group transitions are bijections and cannot
//! selectively overwrite; the 64-token context supplies explicit bounded forgetting. No zeta
//! feature, gate, bias, normalizer or sampler is added.
#![forbid(unsafe_code)]

use std::collections::HashMap;
use std::sync::OnceLock;

use super::group_table::{group_table, GROUP_ORDER, ROW_STRIDE};
use super::lowbit::TernaryLinear;
use super::prior_learning::{PriorCore, BIAS_CODE_MAX, PRIOR_CLAMP};

/// Number of palette actions.
pub const PALETTE_SIZE: usize = 8;
/// Reader hidden width.
pub const READER_WIDTH: usize = 16;
/// Reader row shift: `h[j] = Rcode[q,j] << READER_SHIFT`.
pub const READER_SHIFT: u32 = 5;
/// Ternary output row shift; `READER_SHIFT + OUTPUT_SHIFT = 8` is the declared residual shift.
pub const OUTPUT_SHIFT: u32 = 3;
/// Declared residual score shift.
pub const RESIDUAL_SHIFT: u32 = READER_SHIFT + OUTPUT_SHIFT;
/// Max older-prefix tokens: `H = 64` context minus the two local tokens.
pub const MAX_OLDER_TOKENS: usize = 62;
/// Largest absolute residual score: 16 ternary reader units times `2^8`.
pub const RESIDUAL_MAX_ABS: i64 = (READER_WIDTH as i64) << RESIDUAL_SHIFT;

/// Reader/output Adam learning rate.
pub const READER_LR: f32 = 0.03;
/// Action-logit Adam learning rate.
pub const ACTION_LR: f32 = 0.003;
/// Adam betas, as one fixed pilot configuration.
pub const BETA1: f32 = 0.9;
pub const BETA2: f32 = 0.999;
pub const ADAM_EPS: f32 = 1e-8;
/// Ternary threshold; `|v| >= 0.5` maps to `±1` (ties resolve to magnitude one).
pub const TERNA_TIE: f32 = 0.5;

const CODE_ZERO: u8 = 0;
const CODE_POS: u8 = 1;
const CODE_NEG: u8 = 2;

// ---------------------------------------------------------------------------
// Palette
// ---------------------------------------------------------------------------

/// A fixed, data-independent set of exact group elements. Contains the identity and a chosen
/// noncommuting generator pair, so the subgroup generated by the palette is the whole group.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Palette {
    pub elements: [u8; PALETTE_SIZE],
    pub identity: u8,
}

impl Palette {
    /// Every distinct element reachable from the palette under composition, by BFS closure.
    pub fn closure_size(&self) -> usize {
        let t = group_table();
        let mut seen = vec![false; GROUP_ORDER];
        let mut queue = vec![t.identity as usize];
        seen[t.identity as usize] = true;
        // Seed with the palette itself.
        for &e in self.elements.iter() {
            if !seen[e as usize] {
                seen[e as usize] = true;
                queue.push(e as usize);
            }
        }
        while let Some(a) = queue.pop() {
            for &e in self.elements.iter() {
                let p = t.product[a * ROW_STRIDE + e as usize] as usize;
                if !seen[p] {
                    seen[p] = true;
                    queue.push(p);
                }
            }
        }
        seen.iter().filter(|s| **s).count()
    }
}

/// The order of the subgroup generated by `gens`.
fn generated_order(gens: &[u8]) -> usize {
    let t = group_table();
    let mut seen = vec![false; GROUP_ORDER];
    let mut queue = vec![t.identity as usize];
    seen[t.identity as usize] = true;
    for &g in gens {
        if !seen[g as usize] {
            seen[g as usize] = true;
            queue.push(g as usize);
        }
    }
    while let Some(a) = queue.pop() {
        for &g in gens {
            let p = t.product[a * ROW_STRIDE + g as usize] as usize;
            if !seen[p] {
                seen[p] = true;
                queue.push(p);
            }
        }
    }
    seen.iter().filter(|s| **s).count()
}

/// Deterministically choose the first canonical noncommuting generator pair that generates the
/// whole group, then take the identity, `a`, `b`, their inverses, `a*b`, `b*a` and the smallest
/// remaining element as the eight palette entries. No target data is consulted.
pub fn build_palette() -> Result<Palette, String> {
    let t = group_table();
    let e = t.identity;
    for a in 0..GROUP_ORDER as u8 {
        if a == e {
            continue;
        }
        for b in 0..GROUP_ORDER as u8 {
            if b == e || b == a {
                continue;
            }
            let ab = t.product[a as usize * ROW_STRIDE + b as usize];
            let ba = t.product[b as usize * ROW_STRIDE + a as usize];
            if ab == ba {
                continue;
            }
            if generated_order(&[a, b]) != GROUP_ORDER {
                continue;
            }
            let mut els: Vec<u8> = vec![
                e,
                a,
                b,
                t.inverse[a as usize],
                t.inverse[b as usize],
                ab,
                ba,
            ];
            for cand in 0..GROUP_ORDER as u8 {
                if els.len() == PALETTE_SIZE {
                    break;
                }
                if !els.contains(&cand) {
                    els.push(cand);
                }
            }
            if els.len() != PALETTE_SIZE {
                return Err("palette could not be filled to eight distinct elements".into());
            }
            let mut elements = [0u8; PALETTE_SIZE];
            elements.copy_from_slice(&els);
            let p = Palette {
                elements,
                identity: e,
            };
            if p.closure_size() != GROUP_ORDER {
                return Err("palette closure is not the full group".into());
            }
            return Ok(p);
        }
    }
    Err("no noncommuting generator pair with full closure was found".into())
}

static PALETTE: OnceLock<Palette> = OnceLock::new();

/// The process-wide palette, built on first use.
///
/// # Panics
/// Panics only if the exact group table itself is broken (no noncommuting generator pair), which the
/// `group_table` fixtures already exclude.
pub fn palette() -> &'static Palette {
    PALETTE.get_or_init(|| build_palette().expect("exact 2I palette"))
}

// ---------------------------------------------------------------------------
// Fixed-scale ternary packing
// ---------------------------------------------------------------------------

/// Ternarize a row-major master with the declared `|v| >= 0.5` rule and pack two bits per weight.
pub fn pack_fixed(master: &[f32], rows: usize, cols: usize, shift: u32) -> (Vec<u8>, Vec<u32>) {
    assert_eq!(master.len(), rows * cols);
    let mut packed = vec![0u8; (rows * cols).div_ceil(4)];
    for (i, &v) in master.iter().enumerate() {
        let code = if v >= TERNA_TIE {
            CODE_POS
        } else if v <= -TERNA_TIE {
            CODE_NEG
        } else {
            CODE_ZERO
        };
        if code != CODE_ZERO {
            let byte = i >> 2;
            let slot = (i & 3) as u32;
            packed[byte] |= code << (slot * 2);
        }
    }
    (packed, vec![shift; rows])
}

/// The served hard form of the channel: frozen parent plus the fixed-scale residual read.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrefixCore {
    pub parent: PriorCore,
    /// `GROUP_ORDER x READER_WIDTH`, uniform `READER_SHIFT`.
    pub reader: TernaryLinear,
    /// `vocab x READER_WIDTH`, uniform `OUTPUT_SHIFT`.
    pub wg: TernaryLinear,
    /// Hard per-token palette IDs.
    pub action_codes: Vec<u8>,
    pub palette: Palette,
    /// Arm identity, for report labelling only; it never changes the served computation.
    pub arm: u8,
}

impl PrefixCore {
    /// Fixed-scale constructor from hard codes. Validates shapes and the combined envelope.
    pub fn from_parts(
        parent: PriorCore,
        reader: TernaryLinear,
        wg: TernaryLinear,
        action_codes: Vec<u8>,
        palette: Palette,
        arm: u8,
    ) -> Result<Self, String> {
        if reader.rows != GROUP_ORDER || reader.cols != READER_WIDTH {
            return Err(format!(
                "reader shape {}x{} != {GROUP_ORDER}x{READER_WIDTH}",
                reader.rows, reader.cols
            ));
        }
        let v = parent.cfg.vocab;
        if wg.rows != v || wg.cols != READER_WIDTH {
            return Err(format!(
                "wg shape {}x{} != {v}x{READER_WIDTH}",
                wg.rows, wg.cols
            ));
        }
        if action_codes.len() != v {
            return Err("action code count != vocab".into());
        }
        if action_codes.iter().any(|&c| c as usize >= PALETTE_SIZE) {
            return Err("action code outside the palette".into());
        }
        for r in 0..GROUP_ORDER {
            if reader.shift(r) != READER_SHIFT {
                return Err(format!(
                    "reader row {r} shift {} != {READER_SHIFT}",
                    reader.shift(r)
                ));
            }
        }
        for r in 0..v {
            if wg.shift(r) != OUTPUT_SHIFT {
                return Err(format!(
                    "wg row {r} shift {} != {OUTPUT_SHIFT}",
                    wg.shift(r)
                ));
            }
        }
        let core = Self {
            parent,
            reader,
            wg,
            action_codes,
            palette,
            arm,
        };
        core.validate_envelope()?;
        Ok(core)
    }

    /// The parent's declared maximum absolute score, from its own envelope declaration.
    pub fn parent_declared_max_abs(&self) -> i64 {
        let bias = (BIAS_CODE_MAX as i64) << self.parent.cfg.bias_scale_bits;
        let h_max = if self.parent.cfg.norm_bits == 0 {
            PRIOR_CLAMP as i64
        } else {
            1i64 << self.parent.cfg.norm_bits
        };
        let acc = self.parent.cfg.dv as i64 * h_max;
        let mut w_max = 0i64;
        for r in 0..self.parent.cfg.vocab {
            let bound = acc
                .checked_shl(self.parent.w_o.shift(r))
                .unwrap_or(i64::MAX / 8);
            w_max = w_max.max(bound);
        }
        bias + w_max
    }

    /// Validate that parent bound plus the residual bound cannot approach `i32::MAX`.
    pub fn validate_envelope(&self) -> Result<(), String> {
        let total = self
            .parent_declared_max_abs()
            .saturating_add(RESIDUAL_MAX_ABS);
        if total > (i32::MAX as i64) / 2 {
            return Err(format!(
                "combined parent+residual envelope {total} exceeds half of i32::MAX; the integer \
                 forward could wrap"
            ));
        }
        Ok(())
    }

    /// Hard palette action for a token.
    #[inline]
    pub fn action(&self, token: u32) -> usize {
        let v = self.parent.cfg.vocab;
        self.action_codes[(token as usize).min(v - 1)] as usize
    }

    /// Number of older-prefix tokens for prediction position `i` of a window.
    #[inline]
    pub fn older_len(i: usize) -> usize {
        if i < 2 {
            0
        } else {
            (i - 1) - i.saturating_sub(63)
        }
    }

    /// Chronological product over the older prefix `[max(0,i-63), i-1)`, or `None` when empty.
    pub fn state_older(&self, tokens: &[u32], i: usize) -> Option<usize> {
        if i < 2 {
            return None;
        }
        let start = i.saturating_sub(63);
        let end = i - 1;
        if end <= start {
            return None;
        }
        let t = group_table();
        let mut q = t.identity as usize;
        for &tok in &tokens[start..end] {
            let k = self.action(tok);
            let gamma = self.palette.elements[k] as usize;
            q = t.product[q * ROW_STRIDE + gamma] as usize;
        }
        Some(q)
    }

    /// Local-tail state: the product of the two local tokens' palette actions, or `None` when the
    /// older prefix is empty (the same availability mask as the primary arm).
    pub fn state_tail(&self, tokens: &[u32], i: usize) -> Option<usize> {
        if i < 2 {
            return None;
        }
        let t = group_table();
        let mut q = t.identity as usize;
        for &tok in &tokens[i - 1..=i] {
            let k = self.action(tok);
            let gamma = self.palette.elements[k] as usize;
            q = t.product[q * ROW_STRIDE + gamma] as usize;
        }
        Some(q)
    }

    /// The residual read: `(sum_j Wcode[v,j] * Rcode[q,j]) << 8`.
    pub fn residual_scores(&self, q: usize) -> Vec<i32> {
        let mut h = vec![0i32; READER_WIDTH];
        for (j, slot) in h.iter_mut().enumerate() {
            *slot = self.reader.weight(q, j) << READER_SHIFT;
        }
        let mut out = self.wg.forward_i32(&h);
        // `forward_i32` already applied OUTPUT_SHIFT; assert the declared identity on one entry.
        debug_assert!(READER_SHIFT + OUTPUT_SHIFT == RESIDUAL_SHIFT);
        if false {
            out.clear();
        }
        out
    }

    /// Total integer scores: frozen parent plus the optional residual.
    pub fn int_logits(&self, prev: usize, cur: usize, q: Option<usize>) -> Vec<i32> {
        let mut z = self.parent.int_logits(prev, cur, true);
        if let Some(q) = q {
            let r = self.residual_scores(q);
            for (a, b) in z.iter_mut().zip(r.iter()) {
                *a += *b;
            }
        }
        z
    }

    /// **Arm-aware state selection** shared by training, evaluation and generation.
    ///
    /// The local-tail arm must never fall back to the older-prefix state during generation; its
    /// teacher-forced loss uses [`Self::state_tail`], so generation must too.
    pub fn state_for_arm(&self, tokens: &[u32], i: usize) -> Option<usize> {
        if self.arm == Arm::LearnedTail as u8 {
            self.state_tail(tokens, i)
        } else {
            self.state_older(tokens, i)
        }
    }

    /// Greedy continuation that recomputes the arm's state from the bounded context (no separate
    /// eviction subsystem).
    pub fn generate(&self, prompt: &[u32], n_new: usize) -> Vec<u32> {
        let mut toks = prompt.to_vec();
        let v = self.parent.cfg.vocab;
        for _ in 0..n_new {
            let i = toks.len() - 1;
            let prev = if i == 0 {
                self.parent.cfg.pad_row()
            } else {
                (toks[i - 1] as usize).min(v - 1)
            };
            let cur = (toks[i] as usize).min(v - 1);
            let q = self.state_for_arm(&toks, i);
            let z = self.int_logits(prev, cur, q);
            let mut best = 0usize;
            for r in 1..z.len() {
                if z[r] > z[best] {
                    best = r;
                }
            }
            toks.push(best as u32);
        }
        toks[prompt.len()..].to_vec()
    }

    pub fn weight_bytes(&self) -> usize {
        self.reader.weight_bytes() + self.wg.weight_bytes() + self.action_codes.len() / 2
    }
}

// ---------------------------------------------------------------------------
// Parent score cache
// ---------------------------------------------------------------------------

/// A bounded cache of frozen-parent integer scores keyed by the exact `(prev, cur)` pair. Shared by
/// every arm and invariant under the state permutation, which does not move the local pair.
#[derive(Default)]
pub struct ParentCache {
    map: HashMap<u32, Box<[i32]>>,
    pub hits: u64,
    pub misses: u64,
}

impl ParentCache {
    fn key(prev: usize, cur: usize, vocab: usize) -> u32 {
        ((prev as u32) * (vocab as u32)) + cur as u32
    }

    /// Cached parent scores, computing and storing them on first use.
    pub fn z_for(&mut self, parent: &PriorCore, prev: usize, cur: usize) -> &[i32] {
        let k = Self::key(prev, cur, parent.cfg.vocab);
        if !self.map.contains_key(&k) {
            self.misses += 1;
            let z = parent.int_logits(prev, cur, true);
            self.map.insert(k, z.into_boxed_slice());
        } else {
            self.hits += 1;
        }
        &self.map[&k]
    }

    pub fn entries(&self) -> usize {
        self.map.len()
    }

    pub fn bytes(&self) -> usize {
        self.map
            .values()
            .map(|v| v.len() * std::mem::size_of::<i32>())
            .sum()
    }
}

// ---------------------------------------------------------------------------
// Training
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum Arm {
    /// Learned older-prefix actions and reader/output.
    LearnedOlder = 0,
    /// The initial hard action map is frozen; reader/output trained.
    FixedOlder = 1,
    /// Same sizes, but the state is the local pair product only.
    LearnedTail = 2,
}

impl Arm {
    pub fn name(self) -> &'static str {
        match self {
            Arm::LearnedOlder => "learned_older_prefix",
            Arm::FixedOlder => "fixed_action_older_prefix",
            Arm::LearnedTail => "learned_local_tail",
        }
    }
    pub fn from_u8(x: u8) -> Result<Self, String> {
        match x {
            0 => Ok(Arm::LearnedOlder),
            1 => Ok(Arm::FixedOlder),
            2 => Ok(Arm::LearnedTail),
            _ => Err("unknown arm".into()),
        }
    }
    /// Whether action logits are updated after warm-up.
    pub fn trains_actions(self) -> bool {
        matches!(self, Arm::LearnedOlder | Arm::LearnedTail)
    }
    /// Whether the state is built from the older prefix (as opposed to the local pair only).
    pub fn uses_older_prefix(self) -> bool {
        !matches!(self, Arm::LearnedTail)
    }
}

fn xorshift(st: &mut u64) -> u64 {
    *st ^= *st << 13;
    *st ^= *st >> 7;
    *st ^= *st << 17;
    *st
}

fn seed_state(seed: u64, tag: u64) -> u64 {
    // SplitMix-style tag mixing so per-token initial choices are independent of iteration order.
    let mut z = seed
        .wrapping_add(0x9E37_79B9_7F4A_7C15)
        .wrapping_add(tag.wrapping_mul(0xBF58_476D_1CE4_E5B9));
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// Offline trainer for one arm. Never mutates the frozen parent.
#[derive(Clone, Debug)]
pub struct PrefixTrainer {
    pub parent: PriorCore,
    pub palette: Palette,
    pub arm: Arm,
    pub seed: u64,
    pub window: usize,
    pub batch: usize,
    pub updates: usize,
    pub warmup_updates: usize,
    pub r_master: Vec<f32>,
    pub w_master: Vec<f32>,
    pub a_logits: Vec<f32>,
    /// Frozen hard action map for the fixed-action arm.
    pub frozen_actions: Vec<u8>,
    r_m: Vec<f32>,
    r_v: Vec<f32>,
    w_m: Vec<f32>,
    w_v: Vec<f32>,
    a_m: Vec<f32>,
    a_v: Vec<f32>,
    pub reader_updates: u64,
    pub action_updates: u64,
    pub pass: u32,
    /// L2 norms of the last batch's mean gradients, for reporting only.
    pub last_grad_norm_reader: f64,
    pub last_grad_norm_action: f64,
    pub parent_sha256: [u8; 32],
    pub data_identity: [u8; 32],
}

impl PrefixTrainer {
    pub fn new(
        parent: PriorCore,
        palette: Palette,
        arm: Arm,
        seed: u64,
        window: usize,
        batch: usize,
        updates: usize,
        warmup_updates: usize,
        parent_sha256: [u8; 32],
    ) -> Result<Self, String> {
        let v = parent.cfg.vocab;
        if palette.closure_size() != GROUP_ORDER {
            return Err("palette closure is not the full group".into());
        }
        let mut st = seed ^ 0x5DEE_CE66_D1CE_B00D;
        // Reader masters: seeded +/- 1, so the reader is nonzero from the start and every output
        // row receives a gradient through the reader.
        let r_master: Vec<f32> = (0..GROUP_ORDER * READER_WIDTH)
            .map(|_| {
                if xorshift(&mut st) & 1 == 0 {
                    1.0
                } else {
                    -1.0
                }
            })
            .collect();
        // Output masters exactly zero: step 0 must reproduce the parent scores exactly.
        let w_master = vec![0.0f32; v * READER_WIDTH];
        // Action rows: one seeded palette choice at 0.1, the rest zero.
        let mut a_logits = vec![0.0f32; v * PALETTE_SIZE];
        let mut initial = vec![0u8; v];
        for (t, slot) in initial.iter_mut().enumerate() {
            let id = (seed_state(seed, t as u64) % PALETTE_SIZE as u64) as usize;
            *slot = id as u8;
            a_logits[t * PALETTE_SIZE + id] = 0.1;
        }
        let frozen_actions = match arm {
            Arm::FixedOlder => initial.clone(),
            _ => Vec::new(),
        };
        Ok(Self {
            parent,
            palette,
            arm,
            seed,
            window,
            batch,
            updates,
            warmup_updates,
            r_m: vec![0.0; r_master.len()],
            r_v: vec![0.0; r_master.len()],
            w_m: vec![0.0; w_master.len()],
            w_v: vec![0.0; w_master.len()],
            a_m: vec![0.0; a_logits.len()],
            a_v: vec![0.0; a_logits.len()],
            r_master,
            w_master,
            a_logits,
            frozen_actions,
            reader_updates: 0,
            action_updates: 0,
            pass: 0,
            last_grad_norm_reader: 0.0,
            last_grad_norm_action: 0.0,
            parent_sha256,
            data_identity: [0u8; 32],
        })
    }

    /// The actual initial hard action map.
    pub fn initial_actions(&self) -> Vec<u8> {
        (0..self.parent.cfg.vocab)
            .map(|t| argmax8(&self.a_logits[t * PALETTE_SIZE..(t + 1) * PALETTE_SIZE]) as u8)
            .collect()
    }

    /// The current hard action map.
    pub fn hard_actions(&self) -> Vec<u8> {
        match self.arm {
            Arm::FixedOlder => self.frozen_actions.clone(),
            _ => self.initial_actions(),
        }
    }

    /// Build the served hard core from the current masters.
    pub fn hard_core(&self) -> Result<PrefixCore, String> {
        let v = self.parent.cfg.vocab;
        let (rp, rs) = pack_fixed(&self.r_master, GROUP_ORDER, READER_WIDTH, READER_SHIFT);
        let (wp, ws) = pack_fixed(&self.w_master, v, READER_WIDTH, OUTPUT_SHIFT);
        let reader = TernaryLinear::from_packed(rp, rs, GROUP_ORDER, READER_WIDTH)?;
        let wg = TernaryLinear::from_packed(wp, ws, v, READER_WIDTH)?;
        PrefixCore::from_parts(
            self.parent.clone(),
            reader,
            wg,
            self.hard_actions(),
            self.palette.clone(),
            self.arm as u8,
        )
    }

    /// One hard-forward training batch. Returns the mean uncapped cross-entropy in bits over the
    /// actual scored targets. When `apply_actions` is false the action logits are untouched (reader
    /// warm-up).
    pub fn train_batch(
        &mut self,
        windows: &[Vec<u32>],
        cache: &mut ParentCache,
        apply_actions: bool,
    ) -> Result<f64, String> {
        let v = self.parent.cfg.vocab;
        let core = self.hard_core()?;
        let mut gw = vec![0.0f32; v * READER_WIDTH];
        let mut gr = vec![0.0f32; GROUP_ORDER * READER_WIDTH];
        let mut da = vec![0.0f32; v * PALETTE_SIZE];
        let mut loss = 0.0f64;
        let mut scored = 0usize;

        let scale = (-(core.parent.cfg.f_bits as f64)).exp2();
        let inv_ln2 = 1.0 / std::f64::consts::LN_2;

        for w in windows {
            for i in 0..w.len().saturating_sub(1) {
                let prev = if i == 0 {
                    core.parent.cfg.pad_row()
                } else {
                    (w[i - 1] as usize).min(v - 1)
                };
                let cur = (w[i] as usize).min(v - 1);
                let target = w[i + 1];
                let z_parent = cache.z_for(&core.parent, prev, cur).to_vec();
                let q = if core.arm == Arm::LearnedTail as u8 {
                    core.state_tail(w, i)
                } else {
                    core.state_older(w, i)
                };
                let z = if let Some(q) = q {
                    let r = core.residual_scores(q);
                    let mut z = z_parent.clone();
                    for (a, b) in z.iter_mut().zip(r.iter()) {
                        *a += *b;
                    }
                    z
                } else {
                    z_parent.clone()
                };
                // One softmax pass serves both the loss and the score gradient.
                let p = softmax_scaled(&z, scale);
                let t = (target as usize).min(v - 1);
                loss += -(p[t].max(1e-300).ln()) * inv_ln2;
                scored += 1;

                if q.is_none() {
                    continue;
                }
                let q = q.unwrap();

                // dLoss_nats/dZ with the declared 2^-F score-to-logit scale.
                let mut dz = vec![0.0f64; v];
                for (r, slot) in dz.iter_mut().enumerate() {
                    *slot = (p[r] - if r == t { 1.0 } else { 0.0 }) * scale * inv_ln2;
                }

                // g[j] = 256 * sum_v dZ[v] * Wcode[v,j]; gW[v,j] = 256 * dZ[v] * Rcode[q,j].
                let mut g = [0.0f32; READER_WIDTH];
                let rq: [i32; READER_WIDTH] = std::array::from_fn(|j| core.reader.weight(q, j));
                for r in 0..v {
                    let dzv = dz[r] as f32;
                    if dzv == 0.0 {
                        continue;
                    }
                    let scaled = 256.0 * dzv;
                    for j in 0..READER_WIDTH {
                        if rq[j] != 0 {
                            gw[r * READER_WIDTH + j] += scaled * rq[j] as f32;
                        }
                        let wc = core.wg.weight(r, j);
                        if wc != 0 {
                            g[j] += dzv * wc as f32;
                        }
                    }
                }
                for x in g.iter_mut() {
                    *x *= 256.0;
                }

                // Reader adjoint for the read row.
                for j in 0..READER_WIDTH {
                    gr[q * READER_WIDTH + j] += g[j];
                }

                // State adjoint u[s] = sum_j g[j] * Rcode[s,j].
                let mut u = vec![0.0f32; GROUP_ORDER];
                for (s, us) in u.iter_mut().enumerate() {
                    let mut acc = 0.0f32;
                    for j in 0..READER_WIDTH {
                        let rc = core.reader.weight(s, j);
                        if rc != 0 {
                            acc += g[j] * rc as f32;
                        }
                    }
                    *us = acc;
                }

                // Backpropagate through the bounded chain: explicit reset, no future-target leakage.
                let chain: Vec<usize> = if core.arm == Arm::LearnedTail as u8 {
                    vec![i - 1, i]
                } else {
                    (i.saturating_sub(63)..i - 1).collect()
                };
                let mut qs = Vec::with_capacity(chain.len() + 1);
                qs.push(group_table().identity as usize);
                for &j in &chain {
                    let k = core.action(w[j]);
                    let gamma = core.palette.elements[k] as usize;
                    let last = *qs.last().unwrap();
                    qs.push(group_table().product[last * ROW_STRIDE + gamma] as usize);
                }
                debug_assert_eq!(
                    *qs.last().unwrap(),
                    q,
                    "chain state must equal the read state"
                );
                let mut next_u = vec![0.0f32; GROUP_ORDER];
                for tstep in (0..chain.len()).rev() {
                    let j = chain[tstep];
                    let tok = w[j] as usize;
                    let k_t = core.action(w[j]);
                    let q_before = qs[tstep];
                    let gamma_t = core.palette.elements[k_t] as usize;
                    for (k, &gamma) in core.palette.elements.iter().enumerate() {
                        let h =
                            group_table().product[q_before * ROW_STRIDE + gamma as usize] as usize;
                        da[tok * PALETTE_SIZE + k] += u[h];
                    }
                    for s in 0..GROUP_ORDER {
                        next_u[s] = u[group_table().product[s * ROW_STRIDE + gamma_t] as usize];
                    }
                    std::mem::swap(&mut u, &mut next_u);
                }
            }
        }

        if scored == 0 {
            return Err("empty batch".into());
        }
        let inv = 1.0 / scored as f64;
        loss *= inv;

        // Mean gradients over the actual scored-target count.
        let inv32 = inv as f32;
        for x in gw.iter_mut() {
            *x *= inv32;
        }
        for x in gr.iter_mut() {
            *x *= inv32;
        }
        for x in da.iter_mut() {
            *x *= inv32;
        }
        self.last_grad_norm_reader = gr
            .iter()
            .chain(gw.iter())
            .map(|x| (*x as f64) * (*x as f64))
            .sum::<f64>()
            .sqrt();
        self.last_grad_norm_action = da
            .iter()
            .map(|x| (*x as f64) * (*x as f64))
            .sum::<f64>()
            .sqrt();

        // Softmax Jacobian on the offline action logits, applied once per batch (the logits are
        // constant inside the batch, so linear accumulation is equivalent).
        let mut d_a = vec![0.0f32; v * PALETTE_SIZE];
        for tok in 0..v {
            let row = &self.a_logits[tok * PALETTE_SIZE..(tok + 1) * PALETTE_SIZE];
            let pi = softmax8(row);
            let mut dot = 0.0f32;
            for k in 0..PALETTE_SIZE {
                dot += pi[k] * da[tok * PALETTE_SIZE + k];
            }
            for k in 0..PALETTE_SIZE {
                d_a[tok * PALETTE_SIZE + k] = pi[k] * (da[tok * PALETTE_SIZE + k] - dot);
            }
        }

        // Adam: reader/output age and action age advance independently.
        let next_reader_age = self.reader_updates + 1;
        adam_step(
            &mut self.r_master,
            &mut self.r_m,
            &mut self.r_v,
            &gr,
            READER_LR,
            next_reader_age,
        );
        adam_step(
            &mut self.w_master,
            &mut self.w_m,
            &mut self.w_v,
            &gw,
            READER_LR,
            next_reader_age,
        );
        self.reader_updates = next_reader_age;
        if apply_actions && self.arm.trains_actions() {
            let next_action_age = self.action_updates + 1;
            adam_step(
                &mut self.a_logits,
                &mut self.a_m,
                &mut self.a_v,
                &d_a,
                ACTION_LR,
                next_action_age,
            );
            self.action_updates = next_action_age;
        }
        Ok(loss)
    }

    pub fn state_bytes(&self) -> usize {
        (self.r_master.len() + self.w_master.len() + self.a_logits.len()) * 4
            + (self.r_m.len() + self.r_v.len() + self.w_m.len() + self.w_v.len()) * 4
            + (self.a_m.len() + self.a_v.len()) * 4
    }
}

fn argmax8(a: &[f32]) -> usize {
    let mut best = 0usize;
    for k in 1..PALETTE_SIZE {
        if a[k] > a[best] {
            best = k;
        }
    }
    best
}

fn softmax8(a: &[f32]) -> [f32; PALETTE_SIZE] {
    let mut max = a[0];
    for &x in &a[1..PALETTE_SIZE] {
        if x > max {
            max = x;
        }
    }
    let mut out = [0.0f32; PALETTE_SIZE];
    let mut sum = 0.0f32;
    for k in 0..PALETTE_SIZE {
        let e = (a[k] - max).exp();
        out[k] = e;
        sum += e;
    }
    for x in out.iter_mut() {
        *x /= sum;
    }
    out
}

fn softmax_scaled(z: &[i32], scale: f64) -> Vec<f64> {
    let mut max = f64::NEG_INFINITY;
    for &v in z {
        let s = v as f64 * scale;
        if s > max {
            max = s;
        }
    }
    let mut p = Vec::with_capacity(z.len());
    let mut sum = 0.0f64;
    for &v in z {
        let e = (v as f64 * scale - max).exp();
        p.push(e);
        sum += e;
    }
    for x in p.iter_mut() {
        *x /= sum;
    }
    p
}

/// One Adam step with bias correction at the update's own age, then a master clamp to `[-1, 1]`.
fn adam_step(master: &mut [f32], m: &mut [f32], vv: &mut [f32], grad: &[f32], lr: f32, age: u64) {
    assert_eq!(master.len(), grad.len());
    let b1 = BETA1;
    let b2 = BETA2;
    let bc1 = 1.0 - b1.powi(age.min(100_000) as i32);
    let bc2 = 1.0 - b2.powi(age.min(100_000) as i32);
    for i in 0..master.len() {
        let g = grad[i];
        m[i] = b1 * m[i] + (1.0 - b1) * g;
        vv[i] = b2 * vv[i] + (1.0 - b2) * g * g;
        let mhat = m[i] / bc1;
        let vhat = vv[i] / bc2;
        master[i] -= lr * mhat / (vhat.sqrt() + ADAM_EPS);
        master[i] = master[i].clamp(-1.0, 1.0);
    }
}

// ---------------------------------------------------------------------------
// Checkpoint (new format; the legacy CPCK is untouched)
// ---------------------------------------------------------------------------

pub const PREFIX_MAGIC: &[u8; 4] = b"CPXS";
pub const PREFIX_FORMAT_VERSION: u32 = 1;

impl PrefixTrainer {
    pub fn checkpoint_bytes(&self) -> Vec<u8> {
        let mut o = Vec::new();
        o.extend_from_slice(PREFIX_MAGIC);
        o.extend_from_slice(&PREFIX_FORMAT_VERSION.to_le_bytes());
        o.extend_from_slice(&(self.parent.cfg.vocab as u32).to_le_bytes());
        o.extend_from_slice(&(self.window as u32).to_le_bytes());
        o.extend_from_slice(&(self.batch as u32).to_le_bytes());
        o.extend_from_slice(&(self.updates as u32).to_le_bytes());
        o.extend_from_slice(&(self.warmup_updates as u32).to_le_bytes());
        o.push(self.arm as u8);
        o.extend_from_slice(&self.seed.to_le_bytes());
        o.extend_from_slice(&self.palette.elements);
        o.push(self.palette.identity);
        o.extend_from_slice(&self.reader_updates.to_le_bytes());
        o.extend_from_slice(&self.action_updates.to_le_bytes());
        o.extend_from_slice(&self.pass.to_le_bytes());
        o.extend_from_slice(&self.parent_sha256);
        o.extend_from_slice(&self.data_identity);
        for block in [
            &self.r_master,
            &self.w_master,
            &self.a_logits,
            &self.r_m,
            &self.r_v,
            &self.w_m,
            &self.w_v,
            &self.a_m,
            &self.a_v,
        ] {
            o.extend_from_slice(&(block.len() as u64).to_le_bytes());
            for f in block.iter() {
                o.extend_from_slice(&f.to_le_bytes());
            }
        }
        o
    }

    /// Load a checkpoint, validating config/arm/group/base identity before mutating anything.
    pub fn resume_from(&mut self, bytes: &[u8]) -> Result<(), String> {
        let mut c = 0usize;
        let take = |c: &mut usize, n: usize| -> Result<&[u8], String> {
            let end = c.checked_add(n).ok_or("size overflow")?;
            if end > bytes.len() {
                return Err("truncated checkpoint".into());
            }
            let s = &bytes[*c..end];
            *c = end;
            Ok(s)
        };
        if take(&mut c, 4)? != PREFIX_MAGIC {
            return Err("bad prefix checkpoint magic".into());
        }
        let u32_at = |c: &mut usize| -> Result<u32, String> {
            Ok(u32::from_le_bytes(take(c, 4)?.try_into().unwrap()))
        };
        let u64_at = |c: &mut usize| -> Result<u64, String> {
            Ok(u64::from_le_bytes(take(c, 8)?.try_into().unwrap()))
        };
        if u32_at(&mut c)? != PREFIX_FORMAT_VERSION {
            return Err("unsupported prefix checkpoint version".into());
        }
        let vocab = u32_at(&mut c)? as usize;
        let window = u32_at(&mut c)? as usize;
        let batch = u32_at(&mut c)? as usize;
        let updates = u32_at(&mut c)? as usize;
        let warmup = u32_at(&mut c)? as usize;
        let arm = Arm::from_u8(take(&mut c, 1)?[0])?;
        let seed = u64_at(&mut c)?;
        let mut elements = [0u8; PALETTE_SIZE];
        elements.copy_from_slice(take(&mut c, PALETTE_SIZE)?);
        let identity = take(&mut c, 1)?[0];
        let reader_updates = u64_at(&mut c)?;
        let action_updates = u64_at(&mut c)?;
        let pass = u32_at(&mut c)?;
        let mut parent_sha = [0u8; 32];
        parent_sha.copy_from_slice(take(&mut c, 32)?);
        let mut data_identity = [0u8; 32];
        data_identity.copy_from_slice(take(&mut c, 32)?);

        if vocab != self.parent.cfg.vocab
            || window != self.window
            || batch != self.batch
            || updates != self.updates
            || warmup != self.warmup_updates
            || arm != self.arm
            || seed != self.seed
            || elements != self.palette.elements
            || identity != self.palette.identity
        {
            return Err("prefix checkpoint configuration/arm/seed/palette differs".into());
        }
        if parent_sha != self.parent_sha256 {
            return Err("prefix checkpoint parent artifact differs".into());
        }
        let wants = [
            self.r_master.len(),
            self.w_master.len(),
            self.a_logits.len(),
            self.r_m.len(),
            self.r_v.len(),
            self.w_m.len(),
            self.w_v.len(),
            self.a_m.len(),
            self.a_v.len(),
        ];
        let mut blocks: Vec<Vec<f32>> = Vec::new();
        for want in wants {
            let len = u64_at(&mut c)? as usize;
            if len != want {
                return Err("prefix checkpoint block length differs".into());
            }
            let mut v = Vec::with_capacity(len);
            for _ in 0..len {
                let x = f32::from_le_bytes(take(&mut c, 4)?.try_into().unwrap());
                if !x.is_finite() {
                    return Err("prefix checkpoint holds a non-finite value".into());
                }
                v.push(x);
            }
            blocks.push(v);
        }
        if c != bytes.len() {
            return Err(format!("{} trailing checkpoint bytes", bytes.len() - c));
        }
        if blocks[4].iter().any(|x| *x < 0.0)
            || blocks[6].iter().any(|x| *x < 0.0)
            || blocks[8].iter().any(|x| *x < 0.0)
        {
            return Err("prefix checkpoint second moments are invalid".into());
        }
        let mut it = blocks.into_iter();
        self.r_master = it.next().unwrap();
        self.w_master = it.next().unwrap();
        self.a_logits = it.next().unwrap();
        self.r_m = it.next().unwrap();
        self.r_v = it.next().unwrap();
        self.w_m = it.next().unwrap();
        self.w_v = it.next().unwrap();
        self.a_m = it.next().unwrap();
        self.a_v = it.next().unwrap();
        self.reader_updates = reader_updates;
        self.action_updates = action_updates;
        self.pass = pass;
        self.data_identity = data_identity;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::native_geometric::learner::prior_learning::{bias_codes_from_counts, targets};

    fn tiny_parent(vocab: usize, dv: usize) -> PriorCore {
        let counts = vec![1u64; vocab];
        let total = vocab as u64;
        let bias = bias_codes_from_counts(&counts, total, vocab);
        let cfg = super::super::prior_learning::Config::new(vocab, dv);
        let mut st = 0x1234_5678u64;
        let mut fill = |n: usize| -> Vec<f32> {
            (0..n)
                .map(|_| {
                    let u = (xorshift(&mut st) as f64 / u64::MAX as f64) as f32;
                    (u * 2.0 - 1.0) * 1.5
                })
                .collect()
        };
        let e_old_m = fill((vocab + 1) * dv);
        let e_new_m = fill(vocab * dv);
        let wo_m = fill(vocab * dv);
        PriorCore {
            cfg,
            elements: (0..vocab).map(|t| (t % GROUP_ORDER) as u16).collect(),
            e_old: TernaryLinear::quantize(&e_old_m, vocab + 1, dv),
            e_new: TernaryLinear::quantize(&e_new_m, vocab, dv),
            w_o: TernaryLinear::quantize(&wo_m, vocab, dv),
            bias_codes: bias,
        }
    }

    fn trainer(arm: Arm, seed: u64) -> PrefixTrainer {
        PrefixTrainer::new(
            tiny_parent(64, 32),
            palette().clone(),
            arm,
            seed,
            8,
            2,
            4,
            2,
            [7u8; 32],
        )
        .expect("trainer")
    }

    #[test]
    fn palette_contains_the_identity_and_closes_over_the_whole_group() {
        let p = palette();
        assert!(p.elements.contains(&p.identity));
        assert_eq!(p.elements.len(), PALETTE_SIZE);
        let mut sorted = p.elements;
        sorted.sort_unstable();
        for w in sorted.windows(2) {
            assert_ne!(w[0], w[1], "palette elements must be distinct");
        }
        assert_eq!(p.closure_size(), GROUP_ORDER);
        let t = group_table();
        // Noncommuting pair present: some palette pair has a*b != b*a.
        let mut noncommuting = false;
        for &a in p.elements.iter() {
            for &b in p.elements.iter() {
                if t.product[a as usize * ROW_STRIDE + b as usize]
                    != t.product[b as usize * ROW_STRIDE + a as usize]
                {
                    noncommuting = true;
                }
            }
        }
        assert!(noncommuting, "palette must contain a noncommuting pair");
    }

    #[test]
    fn step_zero_reproduces_the_parent_scores_exactly() {
        let tr = trainer(Arm::LearnedOlder, 13);
        let core = tr.hard_core().expect("core");
        for (prev, cur) in [(1usize, 2usize), (5, 9), (63, 0)] {
            let parent = core.parent.int_logits(prev, cur, true);
            // Zero output masters => zero residual at step 0, for every state.
            for q in [0usize, 7, 119] {
                assert_eq!(core.int_logits(prev, cur, Some(q)), parent);
            }
        }
    }

    #[test]
    fn residual_scale_is_exactly_reader_times_output_shifts() {
        // A reader row of +1 and an output row of +1 must give exactly 1 << RESIDUAL_SHIFT.
        let parent = tiny_parent(8, 16);
        let mut r = vec![0.0f32; GROUP_ORDER * READER_WIDTH];
        r[0] = 1.0;
        let mut w = vec![0.0f32; 8 * READER_WIDTH];
        w[0] = 1.0;
        let (rp, rs) = pack_fixed(&r, GROUP_ORDER, READER_WIDTH, READER_SHIFT);
        let (wp, ws) = pack_fixed(&w, 8, READER_WIDTH, OUTPUT_SHIFT);
        let core = PrefixCore::from_parts(
            parent,
            TernaryLinear::from_packed(rp, rs, GROUP_ORDER, READER_WIDTH).unwrap(),
            TernaryLinear::from_packed(wp, ws, 8, READER_WIDTH).unwrap(),
            vec![0u8; 8],
            palette().clone(),
            0,
        )
        .expect("core");
        let res = core.residual_scores(0);
        assert_eq!(res[0], 1 << RESIDUAL_SHIFT);
        assert!(res[1..].iter().all(|&x| x == 0));
        assert_eq!(RESIDUAL_SHIFT, 8);
    }

    #[test]
    fn older_prefix_excludes_the_local_pair_and_is_empty_before_three_tokens() {
        let tr = trainer(Arm::LearnedOlder, 13);
        let core = tr.hard_core().unwrap();
        let toks = vec![10u32, 11, 12, 13];
        // Four-token trace: i=0 and i=1 have no older prefix; i=2 sees only x[0]; i=3 sees x[0],x[1].
        assert_eq!(core.state_older(&toks, 0), None);
        assert_eq!(core.state_older(&toks, 1), None);
        let t = group_table();
        let a0 = core.action(10);
        let a1 = core.action(11);
        let e = t.identity as usize;
        let exp2 = t.product[e * ROW_STRIDE + core.palette.elements[a0] as usize] as usize;
        assert_eq!(core.state_older(&toks, 2), Some(exp2));
        let exp3 = t.product[exp2 * ROW_STRIDE + core.palette.elements[a1] as usize] as usize;
        assert_eq!(core.state_older(&toks, 3), Some(exp3));
        assert_ne!(exp2, exp3);
        assert_eq!(PrefixCore::older_len(0), 0);
        assert_eq!(PrefixCore::older_len(1), 0);
        assert_eq!(PrefixCore::older_len(2), 1);
        assert_eq!(PrefixCore::older_len(64), 62);
        assert_eq!(PrefixCore::older_len(65), 62);
    }

    #[test]
    fn local_tail_state_is_the_pair_product_and_is_availability_masked() {
        let tr = trainer(Arm::LearnedTail, 13);
        let core = tr.hard_core().unwrap();
        let toks = vec![10u32, 11, 12, 13];
        assert_eq!(core.state_tail(&toks, 0), None);
        assert_eq!(core.state_tail(&toks, 1), None);
        let t = group_table();
        let e = t.identity as usize;
        let a = core.palette.elements[core.action(11)] as usize;
        let b = core.palette.elements[core.action(12)] as usize;
        let exp = t.product[t.product[e * ROW_STRIDE + a] as usize * ROW_STRIDE + b] as usize;
        assert_eq!(core.state_tail(&toks, 2), Some(exp));
    }

    /// The reader/output adjoints are checked against literal small integer values, and the
    /// palette/state adjoints against a finite difference of the continuous multilinear extension
    /// plus softmax Jacobian. Hard argmax is deliberately NOT finite-differenced.
    #[test]
    fn state_adjoint_matches_finite_difference_of_the_continuous_extension() {
        let p = palette();
        let t = group_table();
        let n = GROUP_ORDER;

        // c[h] = sum_{s,k: s*gamma[k]=h} c_prev[s] * pi[k]
        let convolve = |c_prev: &[f64], pi: &[f64; PALETTE_SIZE]| -> Vec<f64> {
            let mut c = vec![0.0f64; n];
            for s in 0..n {
                if c_prev[s] == 0.0 {
                    continue;
                }
                for k in 0..PALETTE_SIZE {
                    let h = t.product[s * ROW_STRIDE + p.elements[k] as usize] as usize;
                    c[h] += c_prev[s] * pi[k];
                }
            }
            c
        };

        // A fixed one-hot chain of length 2 and a nonuniform read weight over states.
        let q0 = 3usize;
        let k0 = 1usize;
        let k1 = 5usize;
        let mut c1 = vec![0.0f64; n];
        {
            let mut c0 = vec![0.0f64; n];
            c0[q0] = 1.0;
            let mut pi0 = [0.0f64; PALETTE_SIZE];
            pi0[k0] = 1.0;
            c1 = convolve(&c0, &pi0);
        }
        let mut pi1 = [0.0f64; PALETTE_SIZE];
        pi1[k1] = 1.0;
        let c2 = convolve(&c1, &pi1);

        // Read weight: u_h = sum_j g_j * Rcode[h,j] for a fixed literal g.
        let g: Vec<f64> = (0..READER_WIDTH).map(|j| (j as f64) - 6.5).collect();
        let rcode = |h: usize, j: usize| -> f64 {
            // A deterministic ternary reader, independent of the trainer.
            (((h * 7 + j * 13) % 3) as i64 - 1) as f64
        };
        let loss = |c: &[f64]| -> f64 {
            let mut l = 0.0;
            for h in 0..n {
                let mut u = 0.0;
                for j in 0..READER_WIDTH {
                    u += g[j] * rcode(h, j);
                }
                l += u * c[h];
            }
            l
        };

        // Analytic state adjoint at c2: u[h] = sum_j g_j Rcode[h,j].
        let mut u = vec![0.0f64; n];
        for h in 0..n {
            for j in 0..READER_WIDTH {
                u[h] += g[j] * rcode(h, j);
            }
        }
        // d_prev[s] = u[s * gamma[k1]]; d_palette[k] = u[c1_state * gamma[k]].
        let c1_state = t.product[q0 * ROW_STRIDE + p.elements[k0] as usize] as usize;
        let mut u_prev = vec![0.0f64; n];
        for s in 0..n {
            u_prev[s] = u[t.product[s * ROW_STRIDE + p.elements[k1] as usize] as usize];
        }
        let eps = 1e-6;
        // Two-step finite differences: pi1 first, then pi0.
        let mut c0 = vec![0.0f64; n];
        c0[q0] = 1.0;
        let pi0 = {
            let mut p0 = [0.0f64; PALETTE_SIZE];
            p0[k0] = 1.0;
            p0
        };
        for k in 0..PALETTE_SIZE {
            let mut pp = pi1;
            pp[k] += eps;
            let mut pm = pi1;
            pm[k] -= eps;
            let l_plus = loss(&convolve(&c1, &pp));
            let l_minus = loss(&convolve(&c1, &pm));
            let fd = (l_plus - l_minus) / (2.0 * eps);
            let analytic = u[t.product[c1_state * ROW_STRIDE + p.elements[k] as usize] as usize];
            assert!(
                (fd - analytic).abs() < 1e-6,
                "step-1 palette {k}: fd {fd} vs analytic {analytic}"
            );
        }
        for k in 0..PALETTE_SIZE {
            let mut pp = pi0;
            pp[k] += eps;
            let mut pm = pi0;
            pm[k] -= eps;
            let l_plus = loss(&convolve(&convolve(&c0, &pp), &pi1));
            let l_minus = loss(&convolve(&convolve(&c0, &pm), &pi1));
            let fd = (l_plus - l_minus) / (2.0 * eps);
            let analytic = u_prev[t.product[q0 * ROW_STRIDE + p.elements[k] as usize] as usize];
            assert!(
                (fd - analytic).abs() < 1e-6,
                "step-0 palette {k}: fd {fd} vs analytic {analytic}"
            );
        }
        let _ = c2;
    }

    #[test]
    fn learned_older_gradient_reaches_an_earlier_token_while_local_inputs_are_unchanged() {
        // One window; the only older token for i=2 is x[0]. Only that token's action can carry
        // older-prefix information into the i=2 prediction, and the local pair is untouched.
        let mut tr = trainer(Arm::LearnedOlder, 13);
        let windows = vec![vec![4u32, 5, 6, 7, 8, 9, 10, 11]];
        let mut cache = ParentCache::default();
        for _ in 0..24 {
            tr.train_batch(&windows, &mut cache, false)
                .expect("warm-up");
            let core = tr.hard_core().unwrap();
            if (0..64).any(|r| (0..READER_WIDTH).any(|j| core.wg.weight(r, j) != 0)) {
                break;
            }
        }
        let before = tr.a_logits.clone();
        tr.train_batch(&windows, &mut cache, true).expect("batch");
        assert_ne!(
            tr.a_logits, before,
            "older-token action credit must move actions"
        );
        // The local pair is not part of the older prefix at the earliest positions; the mask is explicit.
        assert_eq!(PrefixCore::older_len(0), 0);
        assert_eq!(PrefixCore::older_len(1), 0);
        assert_eq!(PrefixCore::older_len(2), 1);
        // Floating action-logit movement is NOT a hard transition: one update at lr 0.003 rarely
        // flips an argmax. Hard action changes/occupancy are measured across the real fit instead.
        let transitions = tr
            .hard_actions()
            .iter()
            .zip(tr.initial_actions().iter())
            .filter(|(a, b)| a != b)
            .count();
        assert!(
            transitions < 64,
            "a single update cannot rewrite every action"
        );
    }

    #[test]
    fn checkpoint_round_trips_and_resume_matches_an_uninterrupted_run() {
        let windows = vec![
            vec![1u32, 2, 3, 4, 5, 6, 7, 8],
            vec![9u32, 10, 11, 12, 13, 14, 15, 16],
            vec![17u32, 18, 19, 20, 21, 22, 23, 24],
            vec![25u32, 26, 27, 28, 29, 30, 31, 32],
        ];
        let mut a = trainer(Arm::LearnedOlder, 13);
        let mut cache = ParentCache::default();
        for _ in 0..3 {
            a.train_batch(&windows, &mut cache, true).unwrap();
        }
        let bytes = a.checkpoint_bytes();

        let mut b = trainer(Arm::LearnedOlder, 13);
        b.resume_from(&bytes).expect("resume");
        assert_eq!(b.reader_updates, a.reader_updates);
        assert_eq!(b.action_updates, a.action_updates);
        assert_eq!(b.r_master, a.r_master);
        assert_eq!(b.w_master, a.w_master);
        assert_eq!(b.a_logits, a.a_logits);

        // A resumed run continues exactly.
        let mut a2 = trainer(Arm::LearnedOlder, 13);
        a2.resume_from(&bytes).unwrap();
        let l1 = a2.train_batch(&windows, &mut cache, true).unwrap();
        let l2 = a.train_batch(&windows, &mut cache, true).unwrap();
        assert_eq!(l1, l2);
        assert_eq!(a2.a_logits, a.a_logits);
        assert_eq!(a2.r_master, a.r_master);

        // Wrong parent identity is rejected.
        let mut c = PrefixTrainer::new(
            tiny_parent(64, 32),
            palette().clone(),
            Arm::LearnedOlder,
            13,
            8,
            2,
            4,
            2,
            [9u8; 32],
        )
        .unwrap();
        assert!(c.resume_from(&bytes).is_err());
    }

    #[test]
    fn action_credit_is_zero_before_warmup_and_nonzero_after() {
        let windows = vec![vec![1u32, 2, 3, 4, 5, 6, 7, 8]];
        let mut tr = trainer(Arm::LearnedOlder, 13);
        let mut cache = ParentCache::default();
        let before = tr.a_logits.clone();
        tr.train_batch(&windows, &mut cache, false).unwrap();
        assert_eq!(tr.a_logits, before, "warm-up must not move action logits");
        assert_eq!(tr.action_updates, 0);
        assert_eq!(tr.reader_updates, 1);
        // Action credit is exactly zero until the output masters ternarize away from zero, because a
        // zero output row gives `g = 0` and therefore a zero state adjoint. This is the declared
        // warm-up, and it is why the schedule gives the reader 64 updates first.
        let mut escaped = false;
        for _ in 0..24 {
            tr.train_batch(&windows, &mut cache, false).unwrap();
            let core = tr.hard_core().unwrap();
            if (0..64).any(|r| (0..READER_WIDTH).any(|j| core.wg.weight(r, j) != 0)) {
                escaped = true;
                break;
            }
        }
        assert!(escaped, "output masters must escape the zero ternary class");
        assert_eq!(tr.action_updates, 0);
        assert_eq!(tr.a_logits, before);
        tr.train_batch(&windows, &mut cache, true).unwrap();
        assert_ne!(tr.a_logits, before, "post-warm-up must learn actions");
        assert_eq!(tr.action_updates, 1);
    }

    #[test]
    fn fixed_action_arm_never_moves_its_action_map() {
        let mut tr = trainer(Arm::FixedOlder, 13);
        let windows = vec![vec![1u32, 2, 3, 4, 5, 6, 7, 8]];
        let mut cache = ParentCache::default();
        let initial = tr.hard_actions();
        for _ in 0..3 {
            tr.train_batch(&windows, &mut cache, true).unwrap();
            assert_eq!(tr.hard_actions(), initial);
        }
        assert_eq!(tr.action_updates, 0);
    }

    #[test]
    fn two_older_prefix_arms_agree_through_warmup() {
        let windows = vec![
            vec![3u32, 8, 1, 9, 2, 7, 4, 0],
            vec![5u32, 6, 11, 12, 13, 14, 15, 16],
        ];
        let mut a = trainer(Arm::LearnedOlder, 13);
        let mut b = trainer(Arm::FixedOlder, 13);
        let mut cache = ParentCache::default();
        assert_eq!(
            a.hard_core().unwrap().int_logits(1, 2, Some(3)),
            b.hard_core().unwrap().int_logits(1, 2, Some(3))
        );
        for _ in 0..2 {
            let la = a.train_batch(&windows, &mut cache, false).unwrap();
            let lb = b.train_batch(&windows, &mut cache, false).unwrap();
            assert_eq!(la, lb);
        }
        assert_eq!(a.r_master, b.r_master);
        assert_eq!(a.w_master, b.w_master);
        assert_eq!(a.hard_actions(), b.hard_actions());
    }

    #[test]
    fn targets_iterator_is_the_shared_n_minus_one_contract() {
        let w = vec![1u32, 2, 3, 4];
        let got: Vec<(usize, usize, usize, u32)> = targets(&w, 64).collect();
        assert_eq!(got.len(), 3);
        assert_eq!(got[0], (0, 64, 1, 2));
        assert_eq!(got[2], (2, 2, 3, 4));
    }
}
