#!/usr/bin/env python3
"""
Hopf Angular Routing Demo — Reproducible Verification
======================================================

This script reproduces the core result from Table 3 of the paper:

  "Angular Manifold Routing: Sublinear Compute Reduction via Hopf-Base
   Sector Discretization"

Running this script:
  python hopf_routing_demo.py

Requirements: numpy only. No GPU. Runtime: < 60 seconds on any modern laptop.

Data required
-------------
This script requires a PPMI-SVD embedding file:
  data/ppmi_proxy.npz

If the file is not present, run the data generation script first:
  python generate_ppmi_proxy.py
which downloads WikiText-2 from the public source and builds the embedding
(requires numpy + scipy; runtime ~2 minutes on first run).

What this shows
---------------
Standard transformer routing (dense MoE gating) assigns N tokens to K experts
with approximately uniform load: effective_buckets ≈ K.

Hopf angular routing exploits the angular non-uniformity of L2-normalized token
embeddings. Tokens cluster into a sparse subset of the available sectors:
  effective_buckets(K) ≈ 2.957 × K^0.572    (HOPF, PPMI-SVD proxy)

The structure-destroyed control (column-permuted, same marginal statistics)
gives:
  effective_buckets(K) ≈ 1.664 × K^0.814    (PERM)

At K=100: Hopf routing uses ~38 effective expert paths vs 74 for permuted
control vs 100 for dense routing. At K=400: ~103 vs 228 vs 400.

Canonical result from INC-0168 (160 static runs, 5 normalization variants):
  HOPF alpha = 0.572 ± 0.001   R² = 0.963
  PERM alpha = 0.814 ± 0.002   R² = 0.993

Relationship to TurboQuant (Google, March 2026)
-----------------------------------------------
TurboQuant: random rotation → destroys angular non-uniformity → near-independent
components → optimal scalar quantization → extreme data compression.

This work: fixed Hopf map → exploits angular non-uniformity → sparse sector
usage → sublinear routing footprint → compute/hardware efficiency.

Both are consequences of the same geometric fact: L2-normalized token embeddings
on the unit hypersphere have angular non-uniformity with engineering consequences.
TurboQuant compresses what is stored; this work reduces how much is computed.

Data
----
PPMI-SVD semantic proxy (ppmi_proxy.npz, generated by generate_ppmi_proxy.py):
  - PPMI co-occurrence matrix built from WikiText-2 (Merity et al. 2016)
  - SVD-reduced to 100 dims
  - Rows = token embedding vectors, L2-normalized
  - Semantic structure preserved by construction

The column-permuted control (PERM) destroys pairwise co-occurrence structure
while preserving marginal distributions, making it an exact structural null.

References
----------
INC-0143 through INC-0169: full experimental chain (available in the artifact bundle)
TurboQuant: Google Research, March 2026
WikiText-2: Merity et al. 2016 (https://arxiv.org/abs/1609.07843)
"""

import os
import sys
import numpy as np
from collections import Counter
from typing import Tuple, List

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SEED = 42
N_TOKENS = 5000
PERM_SEED = 42
K_VALUES = [25, 50, 100, 200, 400]

# Canonical Hopf subspace dimensions (from INC-0162 through INC-0169)
DIMS = (3, 65, 2, 21)   # (dim_i, dim_j, dim_k, dim_l)

# Phase transport strength — 1.0 is the canonical TRANS regime
# At lambda=0: raw fiber alpha only (66.7% rel_diff on PPMI-SVD)
# At lambda=1: Hopf transport correction added (+2pp, INC-0147)
LAMBDA = 1.0

DATA_PATH = os.path.join(os.path.dirname(__file__),
                         "data/wikitext2_proxy/ppmi_proxy.npz")


# ---------------------------------------------------------------------------
# Core Hopf routing algorithm
# (self-contained implementation of phase4d_hopf_transport from
#  hyperbolic_router_so8.py, distilled to essential math)
# ---------------------------------------------------------------------------

def _wrap_to_pi(x: np.ndarray) -> np.ndarray:
    """Wrap angles to [-π, π]."""
    return (x + np.pi) % (2.0 * np.pi) - np.pi


def hopf_transport_sectors(
    Z: np.ndarray,
    K: int,
    dims: Tuple[int, int, int, int] = DIMS,
    lam: float = LAMBDA,
) -> np.ndarray:
    """
    Assign each token to a Hopf angular sector.

    Parameters
    ----------
    Z : (N, D) float array, L2-normalized row vectors
    K : number of routing sectors
    dims : 4-tuple of dimension indices (dim_i, dim_j, dim_k, dim_l)
    lam : phase transport strength (1.0 = canonical TRANS mode)

    Returns
    -------
    sectors : (N,) int array of sector assignments in [0, K)

    Algorithm
    ---------
    1. Project to 4D subspace z = (a, b, c, d) = Z[:, dims]
    2. Hopf base coordinates:
         chi_u = rho2² / (rho1² + rho2²)         [0..1]
         delta = arctan2(b,a) - arctan2(d,c)      [−π..π]
         alpha = 0.5 × (arctan2(b,a) + arctan2(d,c))  [−π..π]
    3. Phase transport:
         transported_alpha = alpha + (λ/2)·cos(2χ)·delta
    4. Assign to integer bins (chi, delta, alpha) with product ≤ K
    """
    a = Z[:, dims[0]]
    b = Z[:, dims[1]]
    c = Z[:, dims[2]]
    d = Z[:, dims[3]]

    rho1 = np.sqrt(a * a + b * b)
    rho2 = np.sqrt(c * c + d * d)
    denom = np.maximum(np.sqrt(rho1 ** 2 + rho2 ** 2), 1e-12)

    chi_u = np.clip((rho2 / denom) ** 2, 0.0, 1.0 - 1e-12)  # sin²(χ)
    chi = np.arcsin(np.clip(rho2 / denom, 0.0, 1.0))

    theta1 = np.arctan2(b, a)
    theta2 = np.arctan2(d, c)
    delta = _wrap_to_pi(theta1 - theta2)
    alpha = _wrap_to_pi(0.5 * (theta1 + theta2))

    # Levi-Civita connection correction (INC-0147: mechanism clarification)
    transported_alpha = _wrap_to_pi(alpha + 0.5 * lam * np.cos(2.0 * chi) * delta)

    kchi, kdelta, kalpha = _allocate_bins(K)

    bchi   = np.minimum((chi_u * kchi).astype(np.int64), kchi - 1)
    bdelta = np.minimum(((delta  + np.pi) / (2.0 * np.pi) * kdelta).astype(np.int64),
                        kdelta - 1)
    balpha = np.minimum(((transported_alpha + np.pi) / (2.0 * np.pi) * kalpha).astype(np.int64),
                        kalpha - 1)

    return (bchi * kdelta * kalpha + bdelta * kalpha + balpha).astype(np.int64)


def _allocate_bins(K: int, min_b: int = 2) -> Tuple[int, int, int]:
    """
    Find (k1, k2, k3) with k1×k2×k3 ≤ K, product maximized, spread minimized.
    Direct port of allocate_triplet_bins_budget from hyperbolic_router_so8.py.
    """
    K = max(1, int(K))
    best: Tuple[int, int, int] = (1, K, 1)
    best_score = None
    for k1 in range(min_b, K + 1):
        for k2 in range(min_b, K + 1):
            max_k3 = K // max(k1 * k2, 1)
            if max_k3 < min_b:
                break
            for k3 in range(min_b, max_k3 + 1):
                prod = k1 * k2 * k3
                favor = 1 if k2 >= k3 else 0
                spread = abs(k1 - k2) + abs(k2 - k3) + abs(k1 - k3)
                score = (prod, favor, -spread, k2, -k3)
                if best_score is None or score > best_score:
                    best_score = score
                    best = (k1, k2, k3)
    return best


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def effective_bucket_count(sectors: np.ndarray) -> float:
    """exp(H(p)) — perplexity of the sector visit distribution."""
    counts = np.array(list(Counter(sectors.tolist()).values()), dtype=np.float64)
    p = counts / counts.sum()
    return float(np.exp(-np.sum(p * np.log(p + 1e-30))))


def gini_coefficient(sectors: np.ndarray) -> float:
    """Gini coefficient of sector visit counts (0=uniform, 1=all in one)."""
    counts = np.sort(np.array(list(Counter(sectors.tolist()).values()),
                              dtype=np.float64))
    n = len(counts)
    if n <= 1:
        return 0.0
    idx = np.arange(1, n + 1, dtype=np.float64)
    return float(2.0 * np.sum(idx * counts) / (n * counts.sum()) - (n + 1) / n)


def fit_power_law(k_vals: List[int], eff_vals: List[float]) -> Tuple[float, float, float]:
    """OLS fit of log(eff) = alpha*log(K) + log(c). Returns (alpha, c, R²)."""
    log_k = np.log(np.array(k_vals, dtype=np.float64))
    log_e = np.log(np.array(eff_vals, dtype=np.float64))
    A = np.vstack([log_k, np.ones(len(log_k))]).T
    coeffs, *_ = np.linalg.lstsq(A, log_e, rcond=None)
    alpha, log_c = float(coeffs[0]), float(coeffs[1])
    c = float(np.exp(log_c))
    pred = alpha * log_k + log_c
    ss_res = float(np.sum((log_e - pred) ** 2))
    ss_tot = float(np.sum((log_e - log_e.mean()) ** 2))
    r2 = float(1.0 - ss_res / max(ss_tot, 1e-30))
    return alpha, c, r2


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 70)
    print("HOPF ANGULAR ROUTING DEMO — Reproducible Verification")
    print("=" * 70)
    print()

    # Load data
    if not os.path.exists(DATA_PATH):
        print(f"ERROR: data file not found at {DATA_PATH}")
        print()
        print("Run the data generation script first:")
        print("  python generate_ppmi_proxy.py")
        print()
        print("This downloads WikiText-2 (public dataset) and builds the PPMI-SVD")
        print("embedding (~2 minutes, requires numpy + scipy).")
        sys.exit(1)

    print(f"Loading: {DATA_PATH}")
    raw = np.load(DATA_PATH)
    X_raw = raw["x_train"].astype(np.float64)
    rng = np.random.RandomState(SEED)
    idx = rng.permutation(X_raw.shape[0])[:N_TOKENS]
    X_raw = X_raw[idx]

    # L2 normalize (canonical baseline)
    X_orig = X_raw / np.linalg.norm(X_raw, axis=1, keepdims=True)

    # Column-permuted control: destroys pairwise structure, preserves marginals
    X_perm = X_orig.copy()
    perm_rng = np.random.RandomState(PERM_SEED)
    for j in range(X_perm.shape[1]):
        X_perm[:, j] = perm_rng.permutation(X_perm[:, j])

    print(f"Tokens: {N_TOKENS}  Dims: {X_orig.shape[1]}  "
          f"Hopf subspace: dims {DIMS}  lambda={LAMBDA}")
    print()

    # Route at each K
    orig_eff, perm_eff = [], []
    print(f"{'K':>5}  {'HOPF_eff':>9}  {'PERM_eff':>9}  {'DENSE_eff':>10}  "
          f"{'PERM/HOPF':>9}  {'HOPF_gini':>10}  {'PERM_gini':>10}")
    print("-" * 70)

    for K in K_VALUES:
        s_orig = hopf_transport_sectors(X_orig, K)
        s_perm = hopf_transport_sectors(X_perm, K)

        eff_o = effective_bucket_count(s_orig)
        eff_p = effective_bucket_count(s_perm)
        gini_o = gini_coefficient(s_orig)
        gini_p = gini_coefficient(s_perm)
        ratio = eff_p / max(eff_o, 1e-9)

        orig_eff.append(eff_o)
        perm_eff.append(eff_p)

        print(f"{K:5d}  {eff_o:9.2f}  {eff_p:9.2f}  {float(K):10.1f}  "
              f"{ratio:9.3f}x  {gini_o:10.4f}  {gini_p:10.4f}")

    # Fit power laws
    alpha_o, c_o, r2_o = fit_power_law(K_VALUES, orig_eff)
    alpha_p, c_p, r2_p = fit_power_law(K_VALUES, perm_eff)
    alpha_d = 1.0  # Dense: trivially K^1.0

    print("-" * 70)
    print()
    print("POWER LAW FIT:  effective_buckets = c × K^alpha")
    print()
    print(f"  HOPF (canonical):   alpha={alpha_o:.4f}  c={c_o:.4f}  R²={r2_o:.4f}")
    print(f"  INC-0168 reference: alpha=0.5717  c=2.9569  R²=0.9628")
    print()
    print(f"  PERM control:       alpha={alpha_p:.4f}  c={c_p:.4f}  R²={r2_p:.4f}")
    print(f"  INC-0168 reference: alpha=0.8142  c=1.6637  R²=0.9929")
    print()
    print(f"  DENSE (standard):   alpha=1.0000  c=1.0000  R²=1.0000")
    print()

    # Interpret
    compute_reduction_K100 = float(K_VALUES[2]) / orig_eff[2]
    compute_reduction_K400 = float(K_VALUES[4]) / orig_eff[4]

    print("INTERPRETATION:")
    print()
    print(f"  At K=100: Hopf routing uses {orig_eff[2]:.1f} effective expert paths")
    print(f"            vs {perm_eff[2]:.1f} for structure-destroyed control")
    print(f"            vs {K_VALUES[2]:.1f} for dense (standard transformer) routing")
    print(f"            → {compute_reduction_K100:.1f}× fewer active routing paths vs dense")
    print()
    print(f"  At K=400: Hopf routing uses {orig_eff[4]:.1f} effective expert paths")
    print(f"            vs {perm_eff[4]:.1f} for structure-destroyed control")
    print(f"            vs {K_VALUES[4]:.1f} for dense (standard transformer) routing")
    print(f"            → {compute_reduction_K400:.1f}× fewer active routing paths vs dense")
    print()
    print("  The scaling advantage grows with K: at K=400 the compression ratio")
    print(f"  ({perm_eff[4]/orig_eff[4]:.2f}×) is larger than at K=100 ({perm_eff[2]/orig_eff[2]:.2f}×).")
    print()
    print("  Hardware proxy (INC-0165, 5 seeds): HOPF achieves 3.0–4.9×")
    print("  lower effective cache cost and 2.5–2.9× fewer LRU-16 cache misses")
    print("  vs the structure-destroyed control at matched learning progress.")
    print()

    # Large-K summary from INC-0170
    print("LARGE-K CAPACITY (INC-0170 static routing, K=600–5000):")
    print()
    print(f"  {'K':>5}  {'eff_ratio':>9}")
    inc0170 = {600: 2.602, 1000: 2.695, 2000: 2.803, 3000: 2.750, 5000: 2.637}
    for K, r in inc0170.items():
        print(f"  {K:5d}  {r:9.3f}×")
    print()
    print("  Compression ratio stabilises at 2.6–2.8× across K=600–5000.")
    print("  The sublinear advantage persists at production-relevant K values.")
    print()
    print("  Note: INC-0168 canonical law (alpha=0.572, fit on K=25–400) slightly")
    print("  underestimates eff_buckets at large K; the exponent over K=25–5000")
    print("  is alpha=0.657. The compression ratio does not collapse.")
    print()

    print("=" * 70)
    print("CONCLUSION")
    print("=" * 70)
    print()
    print(f"  HOPF alpha = {alpha_o:.4f}  (vs 0.5717 from INC-0168 with 160 runs)")
    print(f"  PERM alpha = {alpha_p:.4f}  (vs 0.8142 from INC-0168)")
    print(f"  DENSE alpha = 1.0000  (standard transformer routing)")
    print()
    print("  Fixed Hopf angular routing achieves sublinear effective bucket")
    print("  scaling vs both the structure-destroyed control AND dense routing.")
    print()
    print("  This is the 'same geometric insight as TurboQuant' from the compute")
    print("  direction: normalized token embeddings are angularly non-uniform,")
    print("  and a fixed geometric map can exploit this structure without")
    print("  learning any router parameters.")
    print()


if __name__ == "__main__":
    main()
