//! #718: external differential coverage for the pinned raw T5
//! `spiece.model`.
//!
//! The checked-in expectations are generated by the independent
//! `sentencepiece==0.2.2` implementation, not by this crate.  CI always
//! validates the fixture's schema and source pin.  When the real pinned model
//! is present, the host adapter and exported tagged decode-only runtime must
//! reproduce selected encode/decode cases and the SHA-256 digest of all 32,000
//! singleton decodes.  Absence is reported as UNAVAILABLE rather than hidden.

use std::path::PathBuf;

use serde::Deserialize;
use sha2::{Digest, Sha256};
use uor_r4_core::transformerless::hf_bpe::{TokenizerAdapter, TokenizerModel};
use uor_r4_core::transformerless::scenarios::{
    export_registered_runtime_tokenizer, RuntimeTokenizerExport, Tokenizer,
};
use uor_r4_core::transformerless::sentencepiece::SentencePieceUnigramTokenizer;

const FIXTURE_JSON: &str = include_str!("fixtures/t5_raw_sentencepiece_reference.json");
const FIXTURE_SCHEMA: &str = "uor-r4/t5-raw-sentencepiece-reference/1";
const SINGLETON_DOMAIN_HEX: &str =
    "756f722d72342f74352d7261772d73656e74656e636570696563652d73696e676c65746f6e2d6465636f64652f3100";
const CANONICAL_RECORDS: &str = "u32le(vocab_size), then for id=0..vocab_size-1: u32le(id) || u32le(decoded_utf8_bytes) || decoded_utf8";
const V2_ADAPTER_DIGEST: &str =
    "blake3:e56dc74051fdaf4a90a626328ad01c81b7cd26044b2b071b8d50302c07bbacd1";

#[derive(Debug, Deserialize)]
struct ReferenceFixture {
    schema: String,
    scope: String,
    source: SourcePin,
    reference: ReferenceImplementation,
    adapter: AdapterPin,
    vocab_size: u32,
    special_ids: SpecialIds,
    singleton_decode: SingletonDecode,
    encode_cases: Vec<EncodeCase>,
    decode_cases: Vec<DecodeCase>,
    out_of_range_decode: ReferenceDecodeError,
    piece_types: PieceTypes,
    generator: String,
}

#[derive(Debug, Deserialize)]
struct SourcePin {
    repository: String,
    revision: String,
    path: String,
    bytes: u64,
    sha256: String,
    blake3: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceImplementation {
    package: String,
    version: String,
}

#[derive(Debug, Deserialize)]
struct AdapterPin {
    family: String,
    version: u32,
    tokenizer_cid: String,
    adapter_digest: String,
    decision_status: String,
}

#[derive(Debug, Deserialize)]
struct SpecialIds {
    pad: i32,
    eos: i32,
    unknown: i32,
    bos: i32,
}

#[derive(Debug, Deserialize)]
struct SingletonDecode {
    algorithm: String,
    domain_hex: String,
    canonical_records: String,
    digest: String,
}

#[derive(Debug, Deserialize)]
struct EncodeCase {
    text: String,
    ids: Vec<u32>,
    decoded: String,
}

#[derive(Debug, Deserialize)]
struct DecodeCase {
    ids: Vec<u32>,
    decoded: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceDecodeError {
    ids: Vec<u32>,
    outcome: String,
    exception: String,
    message: String,
}

#[derive(Debug, Deserialize)]
struct PieceTypes {
    normal: PieceTypeRecord,
    unknown: PieceTypeRecord,
    control: PieceTypeRecord,
    user_defined: PieceTypeRecord,
    unused: PieceTypeRecord,
    byte: PieceTypeRecord,
}

#[derive(Debug, Deserialize)]
struct PieceTypeRecord {
    count: u32,
    #[serde(default)]
    ids: Vec<u32>,
}

fn fixture() -> ReferenceFixture {
    serde_json::from_str(FIXTURE_JSON).expect("T5 SentencePiece reference fixture parses")
}

/// Workspace root: `CARGO_MANIFEST_DIR` is `<root>/crates/uor-r4-core`.
fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
}

fn source_snapshot_path() -> PathBuf {
    let descriptor_path = repo_root().join("models/t5-base-tokenizer.json");
    let descriptor_bytes = std::fs::read(&descriptor_path)
        .unwrap_or_else(|error| panic!("{}: {error}", descriptor_path.display()));
    let descriptor: serde_json::Value =
        serde_json::from_slice(&descriptor_bytes).expect("T5 source descriptor parses");
    let source_directory = descriptor["source_directory"]
        .as_str()
        .expect("T5 source_directory is declared");
    repo_root().join(source_directory).join("spiece.model")
}

fn singleton_decode_digest(
    vocab_size: u32,
    domain_hex: &str,
    mut decode: impl FnMut(u32) -> String,
) -> String {
    let domain = hex::decode(domain_hex).expect("singleton-decode domain is hex");
    let mut digest = Sha256::new();
    digest.update(domain);
    digest.update(vocab_size.to_le_bytes());
    for token_id in 0..vocab_size {
        let decoded = decode(token_id);
        let bytes = decoded.as_bytes();
        digest.update(token_id.to_le_bytes());
        digest.update(
            u32::try_from(bytes.len())
                .expect("one decoded piece fits u32")
                .to_le_bytes(),
        );
        digest.update(bytes);
    }
    format!("sha256:{}", hex::encode(digest.finalize()))
}

#[test]
fn independent_fixture_is_pinned_and_non_vacuous() {
    let fixture = fixture();
    assert_eq!(fixture.schema, FIXTURE_SCHEMA);
    assert_eq!(
        fixture.scope,
        "raw spiece.model semantics only; excludes Hugging Face added tokens and post-processing"
    );
    assert_eq!(fixture.source.repository, "google-t5/t5-base");
    assert_eq!(
        fixture.source.revision,
        "a9723ea7f1b39c1eae772870f3b547bf6ef7e6c1"
    );
    assert_eq!(fixture.source.path, "spiece.model");
    assert_eq!(fixture.source.bytes, 791_656);
    assert_eq!(
        fixture.source.sha256,
        "d60acb128cf7b7f2536e8f38a5b18a05535c9e14c7a355904270e15b0945ea86"
    );
    assert!(is_lowercase_hex_64(&fixture.source.sha256));
    assert_eq!(
        fixture.source.blake3,
        "blake3:18af7072534a34d626ca166c92f5e37c7ccfcd6ce6877c3c25d325bc8201090d"
    );
    assert!(is_lowercase_blake3_address(&fixture.source.blake3));
    assert_eq!(fixture.reference.package, "sentencepiece");
    assert_eq!(fixture.reference.version, "0.2.2");
    assert_eq!(
        fixture.adapter.family,
        TokenizerAdapter::SENTENCEPIECE_UNIGRAM_FAMILY
    );
    assert_eq!(
        fixture.adapter.version,
        TokenizerAdapter::SENTENCEPIECE_UNIGRAM_V2_VERSION
    );
    assert_eq!(fixture.adapter.tokenizer_cid, fixture.source.blake3);
    assert_eq!(fixture.adapter.adapter_digest, V2_ADAPTER_DIGEST);
    assert!(is_lowercase_blake3_address(&fixture.adapter.adapter_digest));
    assert_eq!(fixture.adapter.decision_status, "pinned");
    assert_eq!(fixture.vocab_size, 32_000);
    assert_eq!(fixture.special_ids.pad, 0);
    assert_eq!(fixture.special_ids.eos, 1);
    assert_eq!(fixture.special_ids.unknown, 2);
    assert_eq!(fixture.special_ids.bos, -1);
    assert_eq!(fixture.singleton_decode.algorithm, "sha256");
    assert_eq!(fixture.singleton_decode.domain_hex, SINGLETON_DOMAIN_HEX);
    assert_eq!(
        fixture.singleton_decode.canonical_records,
        CANONICAL_RECORDS
    );
    assert!(is_lowercase_sha256_address(
        &fixture.singleton_decode.digest
    ));
    assert!(fixture.encode_cases.len() >= 17);
    assert!(fixture.decode_cases.len() >= 10);
    assert_eq!(fixture.out_of_range_decode.ids, vec![32_000]);
    assert_eq!(fixture.out_of_range_decode.outcome, "error");
    assert_eq!(fixture.out_of_range_decode.exception, "IndexError");
    assert_eq!(
        fixture.out_of_range_decode.message,
        "OUT_OF_RANGE: piece id is out of range."
    );
    assert_eq!(fixture.piece_types.normal.count, 31_997);
    assert!(fixture.piece_types.normal.ids.is_empty());
    assert_eq!(fixture.piece_types.control.count, 2);
    assert_eq!(fixture.piece_types.control.ids, vec![0, 1]);
    assert_eq!(fixture.piece_types.unknown.count, 1);
    assert_eq!(fixture.piece_types.unknown.ids, vec![2]);
    assert_eq!(fixture.piece_types.user_defined.count, 0);
    assert!(fixture.piece_types.user_defined.ids.is_empty());
    assert_eq!(fixture.piece_types.unused.count, 0);
    assert!(fixture.piece_types.unused.ids.is_empty());
    assert_eq!(fixture.piece_types.byte.count, 0);
    assert!(fixture.piece_types.byte.ids.is_empty());
    assert_eq!(fixture.generator, "scripts/gen_t5_sentencepiece_fixture.py");

    let descriptor_path = repo_root().join("models/t5-base-tokenizer.json");
    let descriptor_bytes = std::fs::read(&descriptor_path)
        .unwrap_or_else(|error| panic!("{}: {error}", descriptor_path.display()));
    let descriptor: serde_json::Value =
        serde_json::from_slice(&descriptor_bytes).expect("T5 source descriptor parses");
    assert_eq!(
        descriptor["repository"].as_str(),
        Some(fixture.source.repository.as_str())
    );
    assert_eq!(
        descriptor["revision"].as_str(),
        Some(fixture.source.revision.as_str())
    );
    assert_eq!(
        descriptor["tokenizer_bytes"].as_u64(),
        Some(fixture.source.bytes)
    );
    assert_eq!(
        descriptor["tokenizer_kappa"].as_str(),
        Some(fixture.source.blake3.as_str())
    );
}

fn is_lowercase_sha256_address(value: &str) -> bool {
    value
        .strip_prefix("sha256:")
        .is_some_and(is_lowercase_hex_64)
}

fn is_lowercase_blake3_address(value: &str) -> bool {
    value
        .strip_prefix("blake3:")
        .is_some_and(is_lowercase_hex_64)
}

fn is_lowercase_hex_64(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn export_twice(host: &dyn TokenizerModel) -> (RuntimeTokenizerExport, Tokenizer, Tokenizer) {
    let runtime_path_a = std::env::temp_dir().join(format!(
        "uor-r4-t5-sentencepiece-reference-{}-{:?}-a.bin",
        std::process::id(),
        std::thread::current().id()
    ));
    let runtime_path_b = runtime_path_a.with_file_name(format!(
        "uor-r4-t5-sentencepiece-reference-{}-{:?}-b.bin",
        std::process::id(),
        std::thread::current().id()
    ));
    let export_a = export_registered_runtime_tokenizer(host, &runtime_path_a)
        .expect("first tagged T5 decode-only export");
    let export_b = export_registered_runtime_tokenizer(host, &runtime_path_b)
        .expect("second tagged T5 decode-only export");
    assert_eq!(export_a, export_b, "export metadata is deterministic");
    let runtime_bytes_a = std::fs::read(&runtime_path_a).expect("read first tagged export");
    let runtime_bytes_b = std::fs::read(&runtime_path_b).expect("read second tagged export");
    std::fs::remove_file(&runtime_path_a).ok();
    std::fs::remove_file(&runtime_path_b).ok();
    assert_eq!(
        runtime_bytes_a, runtime_bytes_b,
        "identical host inputs produce identical tagged tokenizer bytes"
    );
    let runtime = Tokenizer::from_bytes(&runtime_bytes_a).expect("parse first tagged export");
    let runtime_again =
        Tokenizer::from_bytes(&runtime_bytes_b).expect("parse second tagged export");
    (export_a, runtime, runtime_again)
}

#[test]
fn real_t5_tagged_exports_are_deterministic_and_fail_closed() {
    let fixture = fixture();
    let snapshot = source_snapshot_path();
    if !snapshot.is_file() {
        eprintln!(
            "UNAVAILABLE: real T5 spiece.model absent at {} — tagged-export differential skipped",
            snapshot.display()
        );
        return;
    }

    let model = std::fs::read(&snapshot).expect("read pinned T5 spiece.model");
    let host = SentencePieceUnigramTokenizer::from_spiece_bytes(&model)
        .expect("pinned T5 spiece.model parses");
    let (export, runtime, runtime_again) = export_twice(&host);
    assert_eq!(export.source_byte_lengths, None);
    assert!(runtime.is_decode_only());
    assert!(runtime_again.is_decode_only());
    assert_eq!(runtime.adapter_identity(), runtime_again.adapter_identity());

    let mut token_out = [0u32; 8];
    assert_eq!(runtime.encode_into("Hello world", &mut token_out), None);
    let mut text_out = [0u8; 64];
    assert_eq!(
        runtime.decode_into(&fixture.out_of_range_decode.ids, &mut text_out),
        None,
        "tagged decode_into refuses the reference's out-of-range id"
    );
    for case in &fixture.decode_cases {
        assert_eq!(
            runtime.decode(&case.ids),
            runtime_again.decode(&case.ids),
            "deterministic exports decode ids {:?} identically",
            case.ids
        );
    }
    assert_eq!(
        singleton_decode_digest(
            fixture.vocab_size,
            &fixture.singleton_decode.domain_hex,
            |token_id| runtime.decode(&[token_id]),
        ),
        singleton_decode_digest(
            fixture.vocab_size,
            &fixture.singleton_decode.domain_hex,
            |token_id| runtime_again.decode(&[token_id]),
        ),
        "deterministic exports produce identical full-vocabulary decode results"
    );
}

#[test]
fn real_t5_host_and_tagged_runtime_match_independent_reference() {
    let fixture = fixture();
    let snapshot = source_snapshot_path();
    if !snapshot.is_file() {
        eprintln!(
            "UNAVAILABLE: real T5 spiece.model absent at {} — external differential skipped",
            snapshot.display()
        );
        return;
    }

    let model = std::fs::read(&snapshot).expect("read pinned T5 spiece.model");
    assert_eq!(model.len() as u64, fixture.source.bytes);
    assert_eq!(
        hex::encode(Sha256::digest(&model)),
        fixture.source.sha256,
        "the external fixture is scoped to these exact source bytes"
    );
    assert_eq!(
        format!("blake3:{}", blake3::hash(&model).to_hex()),
        fixture.source.blake3,
        "the external fixture is scoped to the descriptor κ"
    );

    let host = SentencePieceUnigramTokenizer::from_spiece_bytes(&model)
        .expect("pinned T5 spiece.model parses");
    assert_eq!(host.vocab_size(), fixture.vocab_size as usize);
    for case in &fixture.encode_cases {
        let actual_ids = host.encode(&case.text);
        assert_eq!(
            actual_ids, case.ids,
            "host encode differs from sentencepiece==0.2.2 for {:?}",
            case.text
        );
        assert_eq!(
            host.decode(&actual_ids),
            case.decoded,
            "host decode differs from sentencepiece==0.2.2 for {:?}",
            case.text
        );
    }
    for case in &fixture.decode_cases {
        assert_eq!(
            host.decode(&case.ids),
            case.decoded,
            "host decode differs for ids {:?}",
            case.ids
        );
    }
    assert_eq!(
        singleton_decode_digest(
            fixture.vocab_size,
            &fixture.singleton_decode.domain_hex,
            |token_id| host.decode(&[token_id]),
        ),
        fixture.singleton_decode.digest,
        "host singleton decoding drifted anywhere in the 32,000-piece vocabulary"
    );

    let (export_a, runtime, runtime_again) = export_twice(&host);
    assert_eq!(export_a.source_byte_lengths, None);

    assert!(runtime.is_decode_only());
    assert!(runtime_again.is_decode_only());
    let adapter = host.adapter();
    assert_eq!(
        runtime.adapter_key(),
        Some((
            TokenizerAdapter::SENTENCEPIECE_UNIGRAM_FAMILY,
            adapter.version,
        ))
    );
    let runtime_identity = runtime
        .adapter_identity()
        .expect("tagged runtime carries the full adapter identity");
    assert_eq!(
        runtime.adapter_identity(),
        runtime_again.adapter_identity(),
        "deterministic exports carry identical adapter identities"
    );
    assert_eq!(runtime_identity.tokenizer_cid, adapter.tokenizer_cid);
    assert_eq!(runtime_identity.adapter_digest, adapter.adapter_digest);
    assert_eq!(
        adapter.version, fixture.adapter.version,
        "fixture pins the registry version"
    );
    assert_eq!(
        adapter.adapter_digest, fixture.adapter.adapter_digest,
        "fixture pins the declared adapter policy digest"
    );

    let mut token_out = [0u32; 8];
    assert_eq!(
        runtime.encode_into("Hello world", &mut token_out),
        None,
        "the deployed SentencePiece table is explicitly decode-only"
    );
    let mut text_out = [0u8; 64];
    assert_eq!(
        runtime.decode_into(&fixture.out_of_range_decode.ids, &mut text_out),
        None,
        "tagged decode_into must refuse the reference's out-of-range id"
    );
    for case in &fixture.decode_cases {
        assert_eq!(
            runtime.decode(&case.ids),
            case.decoded,
            "tagged runtime decode differs for ids {:?}",
            case.ids
        );
        assert_eq!(
            runtime_again.decode(&case.ids),
            runtime.decode(&case.ids),
            "both deterministic exports decode ids {:?} identically",
            case.ids
        );
    }
    assert_eq!(
        singleton_decode_digest(
            fixture.vocab_size,
            &fixture.singleton_decode.domain_hex,
            |token_id| runtime.decode(&[token_id]),
        ),
        fixture.singleton_decode.digest,
        "tagged runtime singleton decoding drifted anywhere in the 32,000-piece vocabulary"
    );
    assert_eq!(
        singleton_decode_digest(
            fixture.vocab_size,
            &fixture.singleton_decode.domain_hex,
            |token_id| runtime_again.decode(&[token_id]),
        ),
        fixture.singleton_decode.digest,
        "the second deterministic export reproduces the same singleton digest"
    );
}
