#!/usr/bin/env python3
"""Read-only corrected PR1338 replay recount from saved events and bytes; no model execution."""
import collections,hashlib,json,pathlib,struct,sys
import blake3
P=pathlib.Path;ROOT=P('/Users/casey.allard/uor-r4/.uor-models/realtext-prior-2026-09-20/derived-state-decoder-principal-1');REPO=P('/Users/casey.allard/.codex/worktrees/takeover-research-reconciliation/uor-r4')
sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(p.read_text())
if not (ROOT/'manifest.json').exists():raise SystemExit('Corrected replay not sealed yet; do not treat as a result.')
r=load(ROOT/'result.json');rows=[json.loads(s) for s in (ROOT/'rows.jsonl').read_text().splitlines()];m=load(ROOT/'manifest.json');attempt=load(ROOT/'attempt.json');actual={str(p.relative_to(ROOT)) for p in ROOT.rglob('*') if p.is_file()}-{'manifest.json'};listed={x['path'] for x in m['files']};exe=P(attempt['argv'][0])
o={'schema':'uor-r4.derived-state-decoder-corrected-principal-replay-audit/1','scope':'Independent read-only saved prediction-event recount, artifact byte inspection and seal/hash verification. No new inference, fitting or builds. This is a corrected exposed replay, not fresh final evaluation.','root':str(ROOT),'result_sha256':sha((ROOT/'result.json').read_bytes()),'rows_sha256':sha((ROOT/'rows.jsonl').read_bytes()),'integrity':{'listed_files':len(listed),'missing':sorted(listed-actual),'unlisted':sorted(actual-listed),'seal_errors':[x['path'] for x in m['files'] if len((ROOT/x['path']).read_bytes())!=x['bytes'] or blake3.blake3((ROOT/x['path']).read_bytes()).hexdigest()!=x['blake3']],'observed_source_matches':{x['path']:sha((REPO/x['path']).read_bytes())==x['sha256'] for x in r['running_source']['source_files']},'executable':str(exe),'executable_matches_receipt':sha(exe.read_bytes())==r['running_source']['executable_sha256'] if exe.exists() else None,'executable_sha256':r['running_source']['executable_sha256'],'claimed_at':attempt['claimed_at'],'sealed_at':m['sealed_at']},'artifacts':{},'counts':{},'report_count_checks':{}}
def parse_model(p):
 b=p.read_bytes();c=0
 def take(n):
  nonlocal c
  z=b[c:c+n];assert len(z)==n;c+=n;return z
 def u32():return struct.unpack('<I',take(4))[0]
 assert take(4)==b'RLDS';version=u32();nt=u32();transport=list(take(nt));cyclic=bool(take(1)[0]);flags=list(take(2)) if version==2 else [0,0];domains=[];codes=[]
 for _ in range(2):n=u32();domains.append([u32() for _ in range(n)])
 for _ in range(2):n=u32();codes.append(list(take(n)))
 dl=u32();end=c+dl;assert take(4)==b'RLRD';dv=u32();ns=u32();states=[]
 for _ in range(ns):
  s,valid=take(2);nk=struct.unpack('<H',take(2))[0];ts=[u32() for _ in range(nk)];sc=[struct.unpack('<i',take(4))[0] for _ in range(nk)];idx=min(range(nk),key=lambda j:(-sc[j],ts[j])) if nk else None
  states.append({'state':s,'valid':bool(valid),'top_token':ts[idx] if idx is not None and valid else None,'top_score':sc[idx] if idx is not None and valid else 0})
 assert c==end==len(b)
 return {'sha256':sha(b),'bytes':len(b),'version':version,'cyclic':cyclic,'value_only':bool(flags[0]),'strict_operands':bool(flags[1]),'op_domain':domains[0],'value_domain':domains[1],'op_codes':codes[0],'value_codes':codes[1],'decoder_state_count':ns,'states':states}
models={p.stem:parse_model(p) for p in sorted((ROOT/'artifacts').glob('*.rlds'))}
for a in r['association_panel']['artifacts']+r['composition_panel']['artifacts']:
 z=models[a['arm']];o['artifacts'][a['arm']]={k:v for k,v in z.items() if k!='states'};o['artifacts'][a['arm']]['hash_matches_report']=z['sha256']==a['artifact_sha256'];o['artifacts'][a['arm']]['reported_full_loaded_parity_positions']=a['loaded_parity_positions'];o['artifacts'][a['arm']]['reported_loaded_object_used']=a['loaded_candidate_used_after_export']
groups=collections.defaultdict(list)
for x in rows:groups[(x['panel'],x['split'],x['arm'])].append(x)
arm_to_model={'association_derived_state':'association_derived_state','association_value_only':'association_value_only','h4_derived_state':'composition_derived_state_h4','c120_derived_state':'composition_derived_state_c120'}
for (panel,split,arm),xs in groups.items():
 actual_emitted=lambda x:x.get('arm_emitted',x['emitted']);eligible=[x for x in xs if x['read']]
 ismodel=arm in arm_to_model;md=models.get(arm_to_model.get(arm,''));states={x['state']:x for x in md['states']} if md else {}
 check={'positions':len(xs),'emitted_hits':sum(actual_emitted(x)==x['target'] for x in xs),'decoder_hits':sum(x['decoder_token']==x['target'] for x in xs) if ismodel else None,'local_hits':sum(x['local_emitted']==x['target'] for x in xs),'reads':sum(x['read'] for x in xs),'decoder_noread':sum(x['decoder_token'] is None for x in xs) if ismodel else None,'correct_occurrences':sum(x['correct_source'] for x in xs),'correct_values':sum(x['correct_value'] for x in xs),'correct_source_hits':sum(x['correct_source'] and actual_emitted(x)==x['target'] for x in xs),'wrong_source_hits':sum(not x['correct_source'] and actual_emitted(x)==x['target'] for x in xs),'correct_source_outcomes':dict(collections.Counter(x['outcome'] for x in xs if x['correct_source'])),'selected_ref_flags_match':all(x['correct_source']==(x['selected_payload_seq_abs'] is not None and x['selected_payload_seq_abs'][1]==x['intended_payload_abs']) for x in xs),'selected_value_flags_match':all(x['correct_value']==(x['selected_payload']==x['intended_payload']) for x in xs),'source_is_payload_predecessor':all(x['selected_source_seq_abs'][0]==x['selected_payload_seq_abs'][0] and x['selected_source_seq_abs'][1]+1==x['selected_payload_seq_abs'][1] for x in eligible),'outcome_counts':dict(collections.Counter(x['outcome'] for x in xs)),'all_fallbacks_preserve_local_logits':all(x['preserves_local_logits'] and actual_emitted(x)==x['local_emitted'] for x in xs if x['decoder_token'] is None) if ismodel else None,'decoder_token_matches_artifact':all(x['decoder_token']==states.get(x['s'],{}).get('top_token') for x in xs if x['s'] is not None) if ismodel else None,'decoder_score_matches_artifact':all(x['decoder_score']==states.get(x['s'],{}).get('top_score',0) for x in xs if x['s'] is not None) if ismodel else None,'all_read_query_roles_in_declared_domain':all(x['query_role'] in md['op_domain'] or md['value_only'] for x in eligible) if ismodel else None}
 if panel=='association':
  pair=collections.defaultdict(list)
  for x in xs:pair[x['pair']].append(x)
  check['pairs_both_correct']=sum(len(v)==2 and all(actual_emitted(x)==x['target'] for x in v) for v in pair.values());check['dictionary_hits']=sum(x['categorical_selected_value_prediction']==x['target'] for x in xs);check['matches_dictionary_every_position']=all(actual_emitted(x)==x['categorical_selected_value_prediction'] for x in xs)
 else:
  cells=collections.defaultdict(list)
  for x in xs:cells[(x['op'],x['value_index'])].append(x)
  check['unique_cells']=len(cells);check['cells_all_contexts_correct']=sum(all(actual_emitted(x)==x['target'] for x in v) for v in cells.values());check['by_operation']={op:{'positions':sum(x['op']==op for x in xs),'hits':sum(x['op']==op and actual_emitted(x)==x['target'] for x in xs)} for op in sorted({x['op'] for x in xs})}
 o['counts'][f'{panel}/{split}/{arm}']=check
for a in r['association_panel']['arms']:
 s=a['split'];full=o['counts'][f'association/{s}/association_derived_state'];value=o['counts'][f'association/{s}/association_value_only']
 o['report_count_checks'][f'association/{s}']={'full_decoder':full['decoder_hits']==a['decoder_hits'],'full_emitted':full['emitted_hits']==a['emitted_hits'],'value_decoder':value['decoder_hits']==a['value_only_decoder_hits'],'value_emitted':value['emitted_hits']==a['value_only_emitted_hits'],'dictionary':value['dictionary_hits']==a['selected_value_dictionary_hits'],'noread':full['decoder_noread']==a['no_read_positions']}
for a in r['composition_panel']['arms']:
 key=f"composition/{a['split']}/{a['arm']}";c=o['counts'][key];o['report_count_checks'][key]={'hits':c['emitted_hits']==a['hits'],'reads':c['reads']==a['reads'],'positions':c['positions']==a['positions']}
o['interventions']=r['composition_panel']['interventions'];iv=o['interventions'];op=iv['operation_changed_fixed_evidence'];o['intervention_recount']={'operation_changed_indices':[i for i,(a,b) in enumerate(zip(op['prefix_a'],op['prefix_b'])) if a!=b],'operation_evidence_identical':op['prefix_a'][:3]==op['prefix_b'][:3],'operation_expected_recount':op['emitted_a']==op['expected_a'] and op['emitted_b']==op['expected_b'],'payload_expected_recount':iv['payload_changed_identical_query']['emitted_a']==iv['payload_changed_identical_query']['expected_a'] and iv['payload_changed_identical_query']['emitted_b']==iv['payload_changed_identical_query']['expected_b'],'distractor_preserved_recount':iv['irrelevant_distractor_changed']['emitted_a']==iv['irrelevant_distractor_changed']['emitted_b'],'identity_flag_correct':iv['fixture_class_zero_versus_absence']['is_actual_group_identity']==(iv['fixture_class_zero_versus_absence']['actual_computed_state']==iv['fixture_class_zero_versus_absence']['actual_group_identity']),'local_logit_equalities':'Reported actual vector comparisons; vectors not stored in intervention result. Source-reviewed, not independently recomputed here.'}
o['generation']=[]
for g in r['composition_panel']['generated']:
 arm={'value_only':'association_value_only','h4':'h4_derived_state','c120':'c120_derived_state'}[g['arm']];split='final' if g['panel']=='association' else 'held_out_cells';same=[x for x in groups[(g['panel'],split,arm)] if x['prefix']==g['prefix'] and x['target']==g['answer']];o['generation'].append({'panel':g['panel'],'arm':g['arm'],'answer':g['answer'],'emitted':g['emitted'],'decoded':g['decoded'],'first_correct_recomputed':g['emitted'][0]==g['answer'],'first_correct_flag_matches':g['first_correct']==(g['emitted'][0]==g['answer']),'steps_match_emissions':g['emitted']==[x['emitted'] for x in g['steps']],'first_matches_saved_evaluation':len(same)>0 and all(x.get('arm_emitted',x['emitted'])==g['emitted'][0] for x in same),'steps':g['steps']})
o['screen']=r['screen'];o['interpretation']=['The value-only artifact is now retained, independently loaded and evaluated through the actual step; all420 served decisions equal the development-fitted dictionary decisions, including104/120 reused-final answers and52/60 pairs.','The corrected composition failure persists with all8 operation tokens in both model domains. H4 has56/58 correct-source heldout positions missing decoder states and only2 correct-source hits; its third hit comes from a wrong source. C120 has54/58 correct-source positions missing states and4 correct-source hits.','H4 heldout hits occupy one cell(op3,value2) and no cell has all4 contexts correct. C120 gets all4 contexts of one cell(op7,value2). Both trail the8/64 constant/table reference.','Operation-only end-to-end change loses source selection and fails, while a separately scoped fixed-selected-computation probe answers both operations correctly. This localizes a binding/operation interface issue on that example without proving general computation.','Association generation has3/3 correct first tokens, then local/unknown-value fallback. Composition has0/3 correct first tokens for each algebra, all from repeated contexts of the same cell. No complete prose or response claim.'];o['all_report_counts_match']=all(all(c.values()) for c in o['report_count_checks'].values());o['source_receipt']=r['running_source'];o['resource_scope']={'saved_elapsed_s':r['elapsed_s'],'audit_runs_model':False,'inference_timing':'NOT_MEASURED','physical_energy':'UNAVAILABLE'};o['limits']=['Corrected exposed-population replay; no fresh final model selection evidence.','Short three-token rollouts; no learned stop, complete answer+EOS, ordinary prose or coding qualification.','Direct decoder forcibly selects its label over local argmax; count score is not calibrated probability.','Comparator fitting scopes differ: table uses full development, model decoder uses grounded fit subset with supervised outer map objective.','Independent recount confirms recorded predictions and parameter-table consistency; it is not a second predictor execution or full-logit inference replay.','Operation intervention and fixed-selected-computation probe have different scopes; evaluate reported correct outputs, not mere token change.']
o['script_sha256']=sha(P(__file__).read_bytes());dest=P('/tmp/uor-pr1338-corrected-replay-audit.json');dest.write_text(json.dumps(o,indent=2)+'\n');print(json.dumps({'output':str(dest),'integrity':o['integrity'],'all_report_counts_match':o['all_report_counts_match'],'counts':o['counts'],'interventions':o['interventions'],'generation':o['generation']},indent=2))
