# SPDX-License-Identifier: Apache-2.0
"""Resumable stock-DataLoader row order across source-clock boundaries.

A source-clock block is not a traversal of the smaller transfer population.
The active permutation therefore survives development evaluation and checkpoint
round trips. New traversals retain stock DataLoader's global RNG seed draws;
the permutation itself is generated by its private RandomSampler generator.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

import torch
from torch import Tensor
from torch.utils.data import DataLoader, TensorDataset


class CyclingBatches:
    """Cycle complete, shuffled traversals without resetting at block boundaries.

    ``cycles`` counts traversals started, not source-clock blocks. ``cursor``
    is the next row offset within the stored permutation. An exhausted cursor
    remains at the population size until another training batch is requested:
    an intervening development iterator must consume its RNG draws first.

    Global Torch RNG state belongs to the training checkpoint, not this class.
    Construction, state export, and state restoration consume no random draws.
    """

    def __init__(self, tensors: Mapping[str, Tensor], batch_size: int = 512) -> None:
        if (
            isinstance(batch_size, bool)
            or not isinstance(batch_size, int)
            or batch_size < 1
        ):
            raise ValueError("cycling batch size must be a positive integer")
        names = ("train_inputs", "train_positions", "train_targets")
        if any(name not in tensors for name in names):
            raise ValueError("cycling batches require the three training tensors")
        values = tuple(tensors[name] for name in names)
        if any(
            not isinstance(value, Tensor)
            or value.device.type != "cpu"
            or value.dtype != torch.long
            or value.ndim != 2
            for value in values
        ):
            raise ValueError("cycling tensors must be CPU int64 matrices")
        inputs, positions, targets = values
        rows = inputs.shape[0]
        if (
            rows < 1
            or inputs.shape[1] < 1
            or positions.shape[0] != rows
            or positions.shape[1] < 1
            or targets.shape != positions.shape
            or rows % batch_size != 0
        ):
            raise ValueError(
                "cycling tensor shapes must admit aligned full-size batches"
            )
        self._values = values
        self._batch_size = batch_size
        self._rows = rows
        self._row_ids = torch.arange(rows, dtype=torch.long)
        self._permutation: Tensor | None = None
        self._cursor = 0
        self._cycles = 0

    def _start_traversal(self) -> None:
        # The index-only loader has the same shuffle RNG semantics as the old
        # tensor loader: iterator base seed, sampler seed, then private randperm.
        # Materializing its permutation consumes no model/dropout random draws.
        loader = DataLoader(
            TensorDataset(self._row_ids),
            batch_size=self._rows,
            shuffle=True,
            num_workers=0,
        )
        (self._permutation,) = next(iter(loader))
        self._cursor = 0
        self._cycles += 1

    def next_batch(self) -> tuple[Tensor, Tensor, Tensor]:
        """Return the next complete batch, lazily opening a traversal if needed."""

        if self._permutation is None or self._cursor == self._rows:
            self._start_traversal()
        if self._permutation is None:
            raise RuntimeError("cycling traversal failed to initialize")
        end = self._cursor + self._batch_size
        indices = self._permutation[self._cursor : end]
        inputs, positions, targets = (
            value.index_select(0, indices) for value in self._values
        )
        self._cursor = end
        return inputs, positions, targets

    def state_dict(self) -> dict[str, Any]:
        """Export an independently owned sampler snapshot, without RNG draws."""

        return {
            "permutation": (
                None if self._permutation is None else self._permutation.clone()
            ),
            "cursor": self._cursor,
            "cycles": self._cycles,
        }

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        """Restore a validated snapshot atomically, without consuming RNG."""

        if not isinstance(state, Mapping) or set(state) != {
            "permutation",
            "cursor",
            "cycles",
        }:
            raise ValueError("cycling state fields differ")
        cursor, cycles = state["cursor"], state["cycles"]
        if any(
            isinstance(value, bool) or not isinstance(value, int) or value < 0
            for value in (cursor, cycles)
        ):
            raise ValueError("cycling cursor and cycles must be nonnegative integers")
        permutation = state["permutation"]
        if permutation is None:
            if cursor != 0 or cycles != 0:
                raise ValueError("unstarted cycling state must have zero cursor/cycles")
            restored = None
        else:
            if (
                not isinstance(permutation, Tensor)
                or permutation.device.type != "cpu"
                or permutation.dtype != torch.long
                or tuple(permutation.shape) != (self._rows,)
                or not torch.equal(permutation.sort().values, self._row_ids)
            ):
                raise ValueError("cycling permutation must contain every row once")
            if (
                cycles < 1
                or not self._batch_size <= cursor <= self._rows
                or cursor % self._batch_size != 0
            ):
                raise ValueError(
                    "cycling cursor/cycles do not describe delivered batches"
                )
            restored = permutation.clone()
        self._permutation = restored
        self._cursor = cursor
        self._cycles = cycles
