"""E1: exact 2I (binary icosahedral) group, SL(2,5)/A5 structure, icosian ring = E8,
and multiplier-free exact Z[phi] action with coefficient-growth measurements.

Representation: a Z[phi] element is (a, b) meaning a + b*phi, phi^2 = phi + 1.
A quaternion X is stored DOUBLED: X = 2x in Z[phi]^4 (so 2I elements have integer coords).
"""
import itertools, random, math, sys
from collections import Counter
import numpy as np

# ---------- Z[phi] exact arithmetic ----------
def zadd(p, q): return (p[0] + q[0], p[1] + q[1])
def zsub(p, q): return (p[0] - q[0], p[1] - q[1])
def zneg(p): return (-p[0], -p[1])
def zmul(p, q):
    a, b = p; c, d = q
    # (a + b phi)(c + d phi) = ac + (ad + bc) phi + bd (phi + 1)
    return (a * c + b * d, a * d + b * c + b * d)
def zconj(p):  # Galois: phi -> 1 - phi
    a, b = p
    return (a + b, -b)
def zval(p, conj=False):
    ph = (1 + 5 ** 0.5) / 2
    if conj:
        ph = (1 - 5 ** 0.5) / 2
    return p[0] + p[1] * ph
def zhalf(p):
    assert p[0] % 2 == 0 and p[1] % 2 == 0, p
    return (p[0] // 2, p[1] // 2)

ZERO, ONE, TWO = (0, 0), (1, 0), (2, 0)
PHI, PHIINV = (0, 1), (-1, 1)  # phi, phi - 1 = 1/phi

def qmul_doubled(P, Q):
    """P = 2p, Q = 2q (Z[phi]^4). Returns 2(pq) = (P*Q)/2 exactly (must be divisible)."""
    a0, a1, a2, a3 = P; b0, b1, b2, b3 = Q
    m = zmul
    r0 = zsub(zsub(zsub(m(a0, b0), m(a1, b1)), m(a2, b2)), m(a3, b3))
    r1 = zsub(zadd(zadd(m(a0, b1), m(a1, b0)), m(a2, b3)), m(a3, b2))
    r2 = zadd(zadd(zsub(m(a0, b2), m(a1, b3)), m(a2, b0)), m(a3, b1))
    r3 = zadd(zsub(zadd(m(a0, b3), m(a1, b2)), m(a2, b1)), m(a3, b0))
    return tuple(zhalf(r) for r in (r0, r1, r2, r3))

def build_2I():
    els = set()
    # 8: +-2 e_k  (doubled +-1, +-i, +-j, +-k)
    for k in range(4):
        for s in (1, -1):
            v = [ZERO] * 4; v[k] = (2 * s, 0); els.add(tuple(v))
    # 16: (+-1, +-1, +-1, +-1)
    for signs in itertools.product((1, -1), repeat=4):
        els.add(tuple((s, 0) for s in signs))
    # 96: even perms of (0, +-1, +-phi, +-(phi-1))
    base = [ZERO, ONE, PHI, PHIINV]
    perms = [p for p in itertools.permutations(range(4))
             if sum(1 for i in range(4) for j in range(i + 1, 4) if p[i] > p[j]) % 2 == 0]
    for p in perms:
        for s1, s2, s3 in itertools.product((1, -1), repeat=3):
            signed = [ZERO, (s1 * ONE[0], s1 * ONE[1]), (s2 * PHI[0], s2 * PHI[1]),
                      (s3 * PHIINV[0], s3 * PHIINV[1])]
            v = [None] * 4
            for slot in range(4):
                v[slot] = signed[p[slot]]
            els.add(tuple(v))
    els = sorted(els)
    return els

G = build_2I()
N = len(G)
idx = {g: i for i, g in enumerate(G)}
print(f"|2I| = {N}")
# norms: sum X_k^2 = 4 (doubled)
for g in G:
    n2 = ZERO
    for c in g:
        n2 = zadd(n2, zmul(c, c))
    assert n2 == (4, 0), n2
T = np.zeros((N, N), dtype=np.int64)
for i, a in enumerate(G):
    for j, b in enumerate(G):
        p = qmul_doubled(a, b)
        assert p in idx, "not closed"
        T[i, j] = idx[p]
print("closure: OK (exact Z[phi] arithmetic)")
# associativity over all triples (vectorized)
left = T[T, :]                     # left[a,b,c] = T[T[a,b], c]
right = T[np.arange(N)[:, None, None], T[None, :, :]]  # T[a, T[b,c]]
print("associativity over all", N ** 3, "triples:", bool((left == right).all()))
e = idx[((2, 0), ZERO, ZERO, ZERO)]
inv = np.array([int(np.where(T[a] == e)[0][0]) for a in range(N)])
print("identity index", e, "; every element has a two-sided inverse:",
      all(T[a, inv[a]] == e and T[inv[a], a] == e for a in range(N)))
# element orders
def order(a):
    x, k = a, 1
    while x != e:
        x = T[x, a]; k += 1
    return k
orders = Counter(order(a) for a in range(N))
print("element orders:", dict(sorted(orders.items())))
# conjugacy classes
classes, seen = [], set()
for a in range(N):
    if a in seen: continue
    cl = {int(T[T[g, a], inv[g]]) for g in range(N)}
    seen |= cl; classes.append(sorted(cl))
print("conjugacy classes:", len(classes), "sizes", sorted(len(c) for c in classes))
# real parts (doubled, as Z[phi]) of class representatives -> trace classes
reps = sorted({G[c[0]][0] for c in classes}, key=lambda z: zval(z))
print("Re(2g) by class:", [round(zval(z) / 2, 4) for z in reps])
# center
center = [a for a in range(N) if all(T[a, g] == T[g, a] for g in range(N))]
print("center size:", len(center), "(expect 2: {+1,-1})")
# derived subgroup: generated by commutators
comm = {int(T[T[T[a, b], inv[a]], inv[b]]) for a in range(N) for b in range(N)}
H = set(comm)
while True:
    new = {int(T[x, y]) for x in H for y in H} | H
    if new == H: break
    H = new
print("derived subgroup order:", len(H), "(120 => 2I is perfect, hence non-solvable)")
# quotient by center -> A5: classes of 2I/{+-1}
m1 = idx[((-2, 0), ZERO, ZERO, ZERO)]
cos = {}
for a in range(N):
    key = min(a, int(T[a, m1])); cos[a] = key
reps60 = sorted(set(cos.values()))
print("|2I/{+-1}| =", len(reps60))
# conjugacy classes in the quotient
qclasses, seen = [], set()
for a in reps60:
    if a in seen: continue
    cl = {cos[int(T[T[g, a], inv[g]])] for g in range(N)}
    seen |= cl; qclasses.append(cl)
print("quotient class sizes:", sorted(len(c) for c in qclasses), "(A5: 1,12,12,15,20)")
# a normal subgroup of the quotient is a union of classes containing identity whose size divides 60
sizes = sorted(len(c) for c in qclasses)
possible = set()
for r in range(1, len(sizes) + 1):
    for comb in itertools.combinations(range(len(sizes)), r):
        if 0 in [sizes.index(1)] and sizes.index(1) in comb:
            s = sum(sizes[i] for i in comb)
            if 60 % s == 0: possible.add(s)
print("class-union sizes containing identity dividing 60:", sorted(possible),
      "(only 1 and 60 => quotient simple)")

# ---------- Cayley-graph (word metric) levels -> why 'least energy' ties ----------
def word_metric(gens):
    dist = {e: 0}; frontier = [e]
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = int(T[x, g])
                if y not in dist:
                    dist[y] = dist[x] + 1; nxt.append(y)
        frontier = nxt
    return dist
# natural generating sets
def find(realpart_doubled):
    return [a for a in range(N) if G[a][0] == realpart_doubled]
ord10 = find(PHI)            # Re = phi/2 -> 36 degrees, order 10 (12 of them)
ord6 = find((1, 0))          # Re = 1/2 -> 60 degrees, order 6 (20 of them)
for name, gens in [("12 elements of angle 36deg (+inverses)", ord10),
                   ("20 elements of angle 60deg", ord6),
                   ("2 generators s,t (+inverses)", [ord6[0], ord10[3], int(inv[ord6[0]]), int(inv[ord10[3]])])]:
    d = word_metric(gens)
    if len(d) < N:
        print(f"word metric [{name}]: generates subgroup of order {len(d)}")
        continue
    c = Counter(d.values())
    print(f"word metric [{name}]: diameter {max(c)}, level sizes {dict(sorted(c.items()))}")

# ---------- Galois conjugate group ----------
Gs = [tuple(zconj(c) for c in g) for g in G]
ok = True
for g in Gs:
    n2 = ZERO
    for c in g: n2 = zadd(n2, zmul(c, c))
    ok &= (n2 == (4, 0))
print("Galois conjugates sigma(2I) are again unit quaternions (norm exactly 1):", ok)

# ---------- icosian ring = Z-span of 2I ; E8 check ----------
# coordinates: x = X/2, X in Z[phi]^4 -> integer vector (a0,b0,...,a3,b3) of X (scale 1/2)
def vec(g):
    return [c for z in g for c in z]
M = [vec(g) for g in G]
def hnf_rows(rows):
    """Integer row-echelon (Hermite-like) basis of the Z-span."""
    rows = [list(r) for r in rows]
    basis = []
    ncol = len(rows[0]); col = 0
    while rows and col < ncol:
        rows = [r for r in rows if any(r)]
        piv = [r for r in rows if r[col] != 0]
        if not piv:
            col += 1; continue
        while len([r for r in rows if r[col] != 0]) > 1:
            piv = sorted([r for r in rows if r[col] != 0], key=lambda r: abs(r[col]))
            p = piv[0]
            for r in piv[1:]:
                q = r[col] // p[col]
                for k in range(ncol): r[k] -= q * p[k]
        p = [r for r in rows if r[col] != 0][0]
        basis.append(p); rows.remove(p); col += 1
    return basis
B = hnf_rows(M)
print("rank of Z-span of 2I (icosian ring):", len(B))
def to_quat(v):  # doubled coords
    return tuple((v[2 * k], v[2 * k + 1]) for k in range(4))
def Qform(v):
    """x = X/2; N(x) = sum x_k^2 = (sum X_k^2)/4 = a + b phi ; Q = a + b (Conway-Sloane)."""
    X = to_quat(v); s = ZERO
    for c in X: s = zadd(s, zmul(c, c))
    assert s[0] % 4 == 0 and s[1] % 4 == 0 or True
    return (s[0] + s[1]) / 4.0
def Bform(u, v):
    w = [a + b for a, b in zip(u, v)]
    return Qform(w) - Qform(u) - Qform(v)
Gram = np.array([[Bform(u, v) for v in B] for u in B])
print("Gram(2Q) diagonal:", Gram.diagonal().tolist())
print("Gram entries all integers:", bool(np.allclose(Gram, np.round(Gram))),
      "; det =", round(float(np.linalg.det(Gram)), 6),
      "; even diagonal:", bool(all(int(round(x)) % 2 == 0 for x in Gram.diagonal())),
      "; positive definite:", bool(np.all(np.linalg.eigvalsh(Gram) > 0)))
# count minimal vectors (2Q = 2) by enumeration with small coefficients
Gi = np.round(Gram).astype(float)
# Fincke-Pohst enumeration of all lattice vectors with 2Q <= 2
L = np.linalg.cholesky(Gi)          # Gi = L L^T ; x^T Gi x = |L^T x|^2
R = L.T                              # upper triangular
n = 8; bound = 2.0 + 1e-9; count = [0]
def enum(k, x, partial):
    # choose x[k] given x[k+1:], with partial = sum_{i>k} (R x)_i^2
    c = -sum(R[k, j] * x[j] for j in range(k + 1, n)) / R[k, k]
    r = math.sqrt(max(bound - partial, 0)) / abs(R[k, k])
    for v in range(math.ceil(c - r), math.floor(c + r) + 1):
        x[k] = v
        t = R[k, k] * v + sum(R[k, j] * x[j] for j in range(k + 1, n))
        p = partial + t * t
        if p > bound: continue
        if k == 0:
            if any(x): count[0] += 1
        else:
            enum(k - 1, x, p)
    x[k] = 0
enum(n - 1, [0] * n, 0.0)
print("all lattice vectors with 2Q = 2 (Fincke-Pohst):", count[0], "(E8 has exactly 240 roots)")

# ---------- multiplier-free exact action of 2I on (doubled) icosians ----------
OPS = Counter()
def times_coef(c, X):
    """c in {0,+-1,+-2,+-phi,+-(phi-1)} (a coordinate of 2g); X Zphi; count integer ops."""
    if c == ZERO: return None
    s = 1
    if zval(c) < 0:
        s = -1; c = zneg(c)
    if c == ONE: r = X
    elif c == TWO: r = (X[0] << 1, X[1] << 1); OPS['shift'] += 2
    elif c == PHI: r = (X[1], X[0] + X[1]); OPS['add'] += 1
    elif c == PHIINV: r = (X[1] - X[0], X[0]); OPS['add'] += 1
    else: raise ValueError(c)
    return (s, r)
def act(Gd, X):
    """returns (2g)X/2 using only add/sub/shift; Gd = 2g, X = 2x (doubled icosian)"""
    a = Gd
    # Hamilton product rows: (coef index, x index, sign)
    rows = [[(0, 0, 1), (1, 1, -1), (2, 2, -1), (3, 3, -1)],
            [(0, 1, 1), (1, 0, 1), (2, 3, 1), (3, 2, -1)],
            [(0, 2, 1), (1, 3, -1), (2, 0, 1), (3, 1, 1)],
            [(0, 3, 1), (1, 2, 1), (2, 1, -1), (3, 0, 1)]]
    out = []
    for row in rows:
        acc = None
        for ci, xi, sg in row:
            t = times_coef(a[ci], X[xi])
            if t is None: continue
            s, r = t; s *= sg
            if acc is None:
                acc = r if s > 0 else zneg(r)
                if s < 0: OPS['neg'] += 2
            else:
                acc = zadd(acc, r) if s > 0 else zsub(acc, r); OPS['add'] += 2
        assert acc[0] % 2 == 0 and acc[1] % 2 == 0
        out.append((acc[0] >> 1, acc[1] >> 1)); OPS['shift'] += 2
    return tuple(out)
# verify against exact multiplication, count ops per element type
types = {}
for g in G:
    nz = sum(1 for c in g if c != ZERO)
    t = {1: 'type1 (+-1,+-i,+-j,+-k)', 4: 'type2 (+-1+-i+-j+-k)/2', 3: 'type3 (0,1,phi,1/phi)/2 perms'}[nz]
    types.setdefault(t, []).append(g)
X0 = G[5]
for t, gs in types.items():
    OPS.clear()
    for g in gs:
        assert act(g, X0) == qmul_doubled(g, X0)
    per = {k: v / len(gs) for k, v in OPS.items()}
    print(f"{t}: {len(gs)} elements; mean integer ops per 4-D rotation: {per}")

# ---------- coefficient growth: s_{t+1} = g_t s_t + u_t (exact) ----------
random.seed(1)
def grow(Tsteps, contract=False):
    S = (ZERO,) * 4
    maxbits = []
    for t in range(1, Tsteps + 1):
        g = random.choice(G); u = random.choice(G)   # input from 2I too
        S = qmul_doubled(g, S) if any(c != ZERO for c in S) else S
        if contract:  # multiply by 1/phi = phi - 1 (a contraction in the real embedding)
            S = tuple(zmul(PHIINV, c) for c in S)
        S = tuple(zadd(a, b) for a, b in zip(S, u))
        if t in (16, 64, 256, 1024, 4096):
            m = max(max(abs(c[0]), abs(c[1])) for c in S)
            import mpmath
            mpmath.mp.dps = 2000
            ph = (1 + mpmath.sqrt(5)) / 2; phc = (1 - mpmath.sqrt(5)) / 2
            real = float(mpmath.sqrt(sum((c[0] + c[1] * ph) ** 2 for c in S)) / 2)
            conjv = mpmath.sqrt(sum((c[0] + c[1] * phc) ** 2 for c in S)) / 2
            conj = float(conjv) if conjv < 1e300 else ('2^%d' % int(mpmath.log(conjv, 2)))
            maxbits.append((t, m, round(math.log2(max(m, 1)), 1), round(real, 2), round(conj, 2)))
    return maxbits
print("isometric recurrence  (t, max|coef|, bits, |s|, |sigma(s)|):", grow(4096))
print("contracting (x1/phi) recurrence:", grow(1024, True))
