//! Build script — generate `include/uor_addr.h` via cbindgen from the
//! `extern "C"` surface in `src/lib.rs`.

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let crate_path = PathBuf::from(&crate_dir);
    let out_dir = crate_path.join("include");
    let header_path = out_dir.join("uor_addr.h");

    std::fs::create_dir_all(&out_dir).expect("create include dir");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        style: cbindgen::Style::Both,
        pragma_once: true,
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::C99,
        header: Some(
            "/* uor-addr-c — C ABI bindings for the uor-addr crate.\n\
             * Auto-generated by cbindgen. Do not edit by hand.\n\
             *\n\
             * Apache-2.0 — https://github.com/UOR-Foundation/uor-addr\n\
             */"
            .to_string(),
        ),
        include_guard: Some("UOR_ADDR_H".to_string()),
        ..cbindgen::Config::default()
    };

    if let Ok(builder) = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
    {
        builder.write_to_file(&header_path);
    } else {
        eprintln!("cbindgen failed; skipping header generation");
    }

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
