//! Whole-task joint prose/Rust data and open development on one native artifact.
//! `prepare --output-dir DIR` writes balanced JSONL for the existing CLI.
//! `evaluate --source DIR/source.json --model MODEL --output-dir RESULTS`
//! records unmodified generation, completion coverage and optional compilation.
//! This is deliberately a small synthetic development population, not alpha or
//! an independent held-out assessment. No task parser enters model inference.

use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fs::{self, OpenOptions};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use uor_r4_core::native_geometric::{
    Control, Document, MemoryReadSupervision, MemoryReadTokenSpan, Model, BOS,
};

type ProbeResult<T> = Result<T, Box<dyn Error>>;
const SOURCE_SCHEMA: &str = "uor-r4.native-joint-composition-source/1";
const MAX_SOURCE_BYTES: usize = 32 * 1024 * 1024;

#[derive(Clone, Debug, Serialize)]
struct Options {
    mode: String,
    output_dir: PathBuf,
    source: Option<PathBuf>,
    model: Option<PathBuf>,
    construction_worlds: usize,
    fit_worlds: usize,
    development_worlds: usize,
    generated_tokens: usize,
    max_seconds: u64,
    compiler_cases: usize,
    repair_cases: usize,
}

impl Options {
    fn parse() -> ProbeResult<Self> {
        let mut args = std::env::args().skip(1);
        let mut result = Self {
            mode: args.next().unwrap_or_else(|| "--help".into()),
            output_dir: PathBuf::new(),
            source: None,
            model: None,
            construction_worlds: 128,
            fit_worlds: 128,
            development_worlds: 16,
            generated_tokens: 96,
            max_seconds: 120,
            compiler_cases: 0,
            repair_cases: 0,
        };
        if ["--help", "-h"].contains(&result.mode.as_str()) {
            println!("native_geometric_joint_probe prepare|evaluate --output-dir NEW_DIRECTORY\n\
                prepare: --construction-worlds 1..1024 --fit-worlds 1..1024 --development-worlds 1..64\n\
                Optional prepare --model BASELINE writes exact completion-plus-EOS supervision.json.\n\
                evaluate: --source source.json --model model.json --generated-tokens 1..512\n\
                --max-seconds N --compiler-cases 0..64 --repair-cases 0..8\n\
                Counts are per family; prose and Rust are interleaved in every split.\n\
                Compilation consumes exact prompt plus generated bytes. Only exact safe fixture\n\
                matches are linked/executed; failed compilation may receive one actual-feedback repair.\n\
                Evaluation records Full and MemoryDisabled on the same artifact. No fitting occurs.");
            std::process::exit(0);
        }
        while let Some(flag) = args.next() {
            let value = args
                .next()
                .ok_or_else(|| format!("missing value for {flag}"))?;
            match flag.as_str() {
                "--output-dir" => result.output_dir = value.into(),
                "--source" => result.source = Some(value.into()),
                "--model" => result.model = Some(value.into()),
                "--construction-worlds" => result.construction_worlds = value.parse()?,
                "--fit-worlds" => result.fit_worlds = value.parse()?,
                "--development-worlds" => result.development_worlds = value.parse()?,
                "--generated-tokens" => result.generated_tokens = value.parse()?,
                "--max-seconds" => result.max_seconds = value.parse()?,
                "--compiler-cases" => result.compiler_cases = value.parse()?,
                "--repair-cases" => result.repair_cases = value.parse()?,
                _ => return Err(format!("unknown option {flag}").into()),
            }
        }
        if !["prepare", "evaluate"].contains(&result.mode.as_str())
            || result.output_dir.as_os_str().is_empty()
            || !(1..=1024).contains(&result.construction_worlds)
            || !(1..=1024).contains(&result.fit_worlds)
            || !(1..=64).contains(&result.development_worlds)
            || !(1..=512).contains(&result.generated_tokens)
            || result.max_seconds == 0
            || result.compiler_cases > 64
            || result.repair_cases > 8
            || (result.mode == "evaluate" && (result.source.is_none() || result.model.is_none()))
            || (result.mode == "prepare" && result.source.is_some())
        {
            return Err("unsupported options; see --help".into());
        }
        Ok(result)
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Case {
    id: String,
    family: String,
    task: String,
    world: usize,
    fresh_names: bool,
    fresh_form: bool,
    filler_units: usize,
    prompt: String,
    completion: String,
}

impl Case {
    fn document(&self) -> Document {
        Document {
            id: self.id.clone(),
            text: format!("{}{}", self.prompt, self.completion),
        }
    }
}

#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Source {
    schema: String,
    provenance: String,
    split_policy: String,
    construction: Vec<Case>,
    fit: Vec<Case>,
    development: Vec<Case>,
}

fn make_case(world: usize, split: &str, rust: bool) -> Case {
    let fresh = split == "development" && (world / 4).is_multiple_of(2);
    let fresh_form = split == "development" && !(world / 4).is_multiple_of(2);
    let names = if fresh {
        ["mira", "tavi", "lena", "niko", "suri", "orin"]
    } else {
        ["ada", "ben", "cyra", "dara", "eli", "finn"]
    };
    let first = names[(world / 4) % names.len()];
    let second = names[(world / 4 + 1) % names.len()];
    let third = names[(world / 4 + 3) % names.len()];
    let colors = ["red", "blue", "green", "gold", "white", "black", "silver"];
    let old = colors[(world / 4) % colors.len()];
    let current = colors[(world / 4 + 1) % colors.len()];
    let other = colors[(world / 4 + 3) % colors.len()];
    let number = 2 + (world * 17) % 89;
    let increment = 1 + (world / 4) % 7;
    let filler_units = (world / 8) % 3;
    let filler = if rust {
        "    let _ = 0;\n"
    } else {
        "The wind moves outside. "
    }
    .repeat(filler_units);
    let variant = (world / 12) % 2;
    let (task, prompt, completion) = if rust {
        match world % 4 {
            0 => ("dependency_update", format!("fn main() {{\n    let mut {first} = {number};\n    let {second} = {first} + {increment};\n    {first} = {};\n{filler}    assert_eq!({second},", number + 11),
                format!(" {});\n    assert_eq!({first}, {});\n}}\n", number + increment, number + 11)),
            1 => {
                let expression = if fresh_form { format!("raise(twice({first}))") } else { format!("twice(raise({first}))") };
                let answer = if fresh_form { number * 2 + increment } else { (number + increment) * 2 };
                ("function_composition", format!("fn raise(value: i32) -> i32 {{ value + {increment} }}\nfn twice(value: i32) -> i32 {{ value * 2 }}\nfn main() {{\n    let {first} = {number};\n    let {second} = {expression};\n{filler}    assert_eq!({second},"),
                format!(" {answer});\n}}\n"))
            },
            2 if split == "development" => ("compose_function_body", format!("// Return the input doubled, then add {increment}.\nfn combine(value: i32) -> i32 {{\n    let doubled = value * 2;\n    doubled"),
                format!(" + {increment}\n}}\nfn main() {{\n    assert_eq!(combine({number}), {});\n}}\n", number * 2 + increment)),
            2 => ("compose_function_body", format!("// Return the input plus {increment}, then doubled.\nfn combine(value: i32) -> i32 {{\n    let shifted = value + {increment};\n    shifted"),
                format!(" * 2\n}}\nfn main() {{\n    assert_eq!(combine({number}), {});\n}}\n", (number + increment) * 2)),
            _ if split == "development" => ("repair_instruction", format!("// Repair the addition: the result must subtract {increment} from the input.\n// Before: fn step(value: i32) -> i32 {{ value + {increment} }}\nfn step(value: i32) -> i32 {{\n    value"),
                format!(" - {increment}\n}}\nfn main() {{\n    assert_eq!(step({number}), {});\n}}\n", number as i32 - increment as i32)),
            _ => ("repair_instruction", format!("// Repair the subtraction: the result must add {increment} to the input.\n// Before: fn step(value: i32) -> i32 {{ value - {increment} }}\nfn step(value: i32) -> i32 {{\n    value"),
                format!(" + {increment}\n}}\nfn main() {{\n    assert_eq!(step({number}), {});\n}}\n", number + increment)),
        }
    } else {
        let facts = if variant == 0 {
            format!("User: {first} has a {old} badge. {second} has a {other} badge. {third} has {number} coins.\nUser: Update: {first} now has a {current} badge.\n")
        } else {
            format!("User: {second}'s badge is {other}. {third} holds {number} coins. {first}'s badge was {old}.\nUser: Correction: {first}'s badge is {current} now.\n")
        };
        match world % 4 {
            0 => {
                let question = if fresh_form { format!("Tell me the current badge color for {first}.") } else { format!("What color is {first}'s badge now?") };
                ("updated_fact", format!("{facts}{filler}User: {question}\nAssistant:"), format!(" {current}.\n"))
            },
            1 => ("two_fact_composition", format!("{facts}{filler}User: Give the badge colors for {second}, then {first}.\nAssistant:"), format!(" {second} has {other}; {first} has {current}.\n")),
            2 => ("contradiction", format!("{facts}User: {first}'s badge is still {old}, correct?\n{filler}Assistant:"), format!(" No. {first}'s badge is {current} now.\n")),
            _ => ("unsupported_answer", format!("{facts}{filler}User: What city does {third} live in?\nAssistant:"), " Unknown. The conversation does not give a city.\n".into()),
        }
    };
    Case {
        id: format!(
            "joint-v1/{split}/{}/{world}",
            if rust { "rust" } else { "prose" }
        ),
        family: if rust { "rust" } else { "prose" }.into(),
        task: task.into(),
        world,
        fresh_names: fresh && (!rust || world % 4 < 2),
        fresh_form: (fresh_form && (!rust && world.is_multiple_of(4) || rust && world % 4 == 1))
            || (split == "development" && rust && world % 4 >= 2),
        filler_units,
        prompt,
        completion,
    }
}

fn source(options: &Options) -> Source {
    let make = |split: &str, offset: usize, count: usize| {
        (offset..offset + count)
            .flat_map(|world| {
                [
                    make_case(world, split, false),
                    make_case(world, split, true),
                ]
            })
            .collect()
    };
    Source {
        schema: SOURCE_SCHEMA.into(),
        provenance: "Authored deterministic synthetic task templates native_geometric_joint_probe/1. All answers are construction/evaluation labels from finite supplied facts and integer arithmetic. Repair training contains explicit edit instructions, not invented compiler observations. Actual compiler-feedback repairs are generated only during requested evaluation. No external corpus or provider.".into(),
        split_policy: "Whole task documents; one prose and one Rust case per world, interleaved. Disjoint world IDs and exact document bytes across construction, fit and open development. Development mixes fresh names with shared names and fresh fact/number combinations; templates and finite grammar are shared. Construction builds vocabulary/counts; fit is separate supervised training; development labels never enter fitting. No final held-out claim.".into(),
        construction: make("construction", 0, options.construction_worlds),
        fit: make("fit", options.construction_worlds, options.fit_worlds),
        development: make("development", 100_000, options.development_worlds),
    }
}

fn write_new(path: &Path, bytes: &[u8]) -> ProbeResult<()> {
    OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)?
        .write_all(bytes)?;
    Ok(())
}

fn read_bounded(path: &Path, bound: usize) -> ProbeResult<Vec<u8>> {
    let file = fs::File::open(path)?;
    if file.metadata()?.len() > bound as u64 {
        return Err("input exceeds byte bound".into());
    }
    let mut bytes = Vec::new();
    file.take(bound as u64 + 1).read_to_end(&mut bytes)?;
    if bytes.len() > bound {
        return Err("input grew beyond byte bound".into());
    }
    Ok(bytes)
}

fn validate(source: &Source, model: Option<&Model>) -> ProbeResult<Value> {
    if source.schema != SOURCE_SCHEMA
        || source.construction.is_empty()
        || source.fit.is_empty()
        || source.development.is_empty()
        || source.construction.len() > 2048
        || source.fit.len() > 2048
        || source.development.len() > 128
    {
        return Err("invalid source schema or split sizes".into());
    }
    let mut texts = BTreeSet::new();
    let mut ids = BTreeSet::new();
    let mut counts: BTreeMap<String, Value> = BTreeMap::new();
    for (split, cases) in [
        ("construction", &source.construction),
        ("fit", &source.fit),
        ("development", &source.development),
    ] {
        for case in cases {
            let document = case.document();
            if !["prose", "rust"].contains(&case.family.as_str())
                || case.id.is_empty()
                || case.prompt.is_empty()
                || case.completion.is_empty()
                || document.text.len() > 16384
                || case.world > 101_024
                || !ids.insert(&case.id)
                || !texts.insert(document.text.clone())
            {
                return Err(format!("duplicate or invalid source case {}", case.id).into());
            }
            // This example accepts only its versioned authored finite source.
            // In particular, an externally edited expected completion must not
            // become an execution allow-list merely by matching model output.
            if case != &make_case(case.world, split, case.family == "rust") {
                return Err(
                    format!("case differs from authored source generator: {}", case.id).into(),
                );
            }
            if let Some(model) = model {
                let prompt = model.encode(&case.prompt)?;
                let full = model.encode(&document.text)?;
                if !full.starts_with(&prompt)
                    || full.len() == prompt.len()
                    || model.decode(&full[prompt.len()..])? != case.completion.as_bytes()
                {
                    return Err(format!("native lexical boundary mismatch in {}", case.id).into());
                }
                if split == "development" {
                    let cid = format!("blake3:{}", blake3::hash(document.text.as_bytes()));
                    if model
                        .construction()
                        .iter()
                        .chain(model.readout_training())
                        .chain(model.memory_read_training())
                        .any(|known| known.id == case.id || known.text_cid == cid)
                    {
                        return Err(
                            format!("development overlaps artifact training: {}", case.id).into(),
                        );
                    }
                }
            }
        }
        for family in ["prose", "rust"] {
            let selected: Vec<_> = cases.iter().filter(|c| c.family == family).collect();
            let mut positions = 0;
            let mut completion_positions = 0;
            let mut max_context = 0;
            let mut over_context = 0;
            if let Some(model) = model {
                for case in &selected {
                    let full = model.encode(&case.document().text)?.len();
                    let prompt = model.encode(&case.prompt)?.len();
                    positions += full + 1;
                    completion_positions += full - prompt;
                    max_context = max_context.max(prompt + 1);
                    over_context += usize::from(prompt + 1 > model.config().context_tokens);
                }
            }
            counts.insert(format!("{split}/{family}"), json!({"documents":selected.len(),
                "text_bytes":selected.iter().map(|c| c.document().text.len()).sum::<usize>(),
                "available_supervised_positions_including_eos":model.map(|_| positions),
                "available_completion_positions_excluding_eos":model.map(|_| completion_positions),
                "max_prompt_context_including_bos":model.map(|_| max_context),
                "prompts_longer_than_context":model.map(|_| over_context),
                "sampled_fit_completion_positions":"NOT_MEASURED: requires fitter selection trace, not inferred from available positions"}));
        }
    }
    Ok(
        json!({"id_and_exact_document_overlap":"PASS", "lexical_boundaries":if model.is_some() {"PASS"} else {"NOT_RUN: requires artifact codec"}, "families":counts}),
    )
}

fn prepare(options: &Options) -> ProbeResult<Value> {
    let source = source(options);
    let baseline = options
        .model
        .as_deref()
        .map(|path| -> ProbeResult<Model> {
            Ok(Model::from_bytes(&read_bounded(path, 256 * 1024 * 1024)?)?)
        })
        .transpose()?;
    let audit = validate(&source, baseline.as_ref())?;
    let bytes = serde_json::to_vec_pretty(&source)?;
    write_new(&options.output_dir.join("source.json"), &bytes)?;
    for (name, cases) in [
        ("construction", &source.construction),
        ("fit", &source.fit),
        ("development", &source.development),
    ] {
        let mut output = Vec::new();
        for case in cases {
            serde_json::to_writer(&mut output, &case.document())?;
            output.push(b'\n');
        }
        write_new(&options.output_dir.join(format!("{name}.jsonl")), &output)?;
    }
    let supervision = if let Some(model) = &baseline {
        let documents: Vec<_> = source.fit.iter().map(Case::document).collect();
        let spans: Vec<Vec<MemoryReadTokenSpan>> = source
            .fit
            .iter()
            .map(|case| {
                let start = model.encode(&case.prompt)?.len();
                let end = model.encode(&case.document().text)?.len() + 1;
                Ok(vec![MemoryReadTokenSpan { start, end }])
            })
            .collect::<ProbeResult<_>>()?;
        let positions = spans
            .iter()
            .flatten()
            .map(|span| span.end - span.start)
            .sum::<usize>();
        let supervision = MemoryReadSupervision::new(model, &documents, spans)?;
        let bytes = serde_json::to_vec_pretty(&supervision)?;
        write_new(&options.output_dir.join("supervision.json"), &bytes)?;
        json!({"status":"written","path":options.output_dir.join("supervision.json"),
            "blake3":blake3::hash(&bytes).to_hex().to_string(),"baseline_artifact":model.artifact_cid(),
            "documents":documents.len(),"selected_completion_and_eos_positions":positions,
            "scope":"Exact model-codec token spans; BOS excluded, completion start inclusive, EOS included. Whole documents still supply causal context. Generic external loss metadata only, with no expected-answer parser or runtime behavior change."})
    } else {
        json!({"status":"not_requested","reason":"prepare --model required for exact codec-bound supervision"})
    };
    Ok(
        json!({"schema":SOURCE_SCHEMA,"status":"completed","source_blake3":blake3::hash(&bytes).to_hex().to_string(),
        "audit":audit,"supervision":supervision,"provenance":source.provenance,"split_policy":source.split_policy,
        "usage":"Pass construction.jsonl and fit.jsonl directly to native training/fitting CLI with a sufficient input byte budget and document-bytes >=16384. Do not repartition or truncate the whole tasks."}),
    )
}

fn remaining(options: &Options, started: Instant) -> Duration {
    Duration::from_secs(options.max_seconds).saturating_sub(started.elapsed())
}

// Host assessment only. Time and diagnostic-size limits are monitored; this is
// not an OS/process-tree sandbox. Executed programs must be exact authored safe
// source matches. Failed or alternate generated programs are metadata-only.
fn bounded_command(
    mut command: Command,
    directory: &Path,
    name: &str,
    limit: Duration,
) -> ProbeResult<Value> {
    if limit.is_zero() {
        return Ok(json!({"status":"not_run_budget","success":null}));
    }
    let stdout_path = directory.join(format!("{name}.stdout"));
    let stderr_path = directory.join(format!("{name}.stderr"));
    let stdout = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&stdout_path)?;
    let stderr = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&stderr_path)?;
    let started = Instant::now();
    let mut child = match command
        .stdin(Stdio::null())
        .stdout(stdout)
        .stderr(stderr)
        .spawn()
    {
        Ok(child) => child,
        Err(error) => {
            return Ok(json!({"status":"unavailable","success":null,"error":error.to_string()}))
        }
    };
    let mut reason = "completed";
    let status = loop {
        if let Some(status) = child.try_wait()? {
            break status;
        }
        let large = [&stdout_path, &stderr_path]
            .iter()
            .any(|p| fs::metadata(p).is_ok_and(|m| m.len() > 262144));
        if started.elapsed() >= limit || large {
            reason = if large {
                "diagnostic_limit"
            } else {
                "time_limit"
            };
            let _ = child.kill();
            break child.wait()?;
        }
        std::thread::sleep(Duration::from_millis(10));
    };
    let mut diagnostics = Vec::new();
    fs::File::open(&stderr_path)?
        .take(16384)
        .read_to_end(&mut diagnostics)?;
    let mut stdout_text = Vec::new();
    fs::File::open(&stdout_path)?
        .take(16384)
        .read_to_end(&mut stdout_text)?;
    Ok(
        json!({"status":reason,"success":(reason == "completed").then_some(status.success()),
        "exit_code":status.code(),"elapsed_ms":started.elapsed().as_millis(),"limit_ms":limit.as_millis(),
        "stdout":stdout_path,"stdout_text":String::from_utf8_lossy(&stdout_text),
        "stderr":stderr_path,"diagnostics":String::from_utf8_lossy(&diagnostics),
        "diagnostics_truncated":fs::metadata(&stderr_path)?.len() > diagnostics.len() as u64}),
    )
}

fn pinned_toolchain() -> ProbeResult<&'static str> {
    include_str!("../../../rust-toolchain.toml")
        .lines()
        .filter_map(|line| line.split_once('='))
        .find(|(key, _)| key.trim() == "channel")
        .and_then(|(_, value)| value.trim().strip_prefix('"')?.strip_suffix('"'))
        .ok_or_else(|| "missing quoted channel in compiled repository toolchain pin".into())
}

fn compiler(directory: &Path) -> ProbeResult<Command> {
    let user_home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or("HOME unavailable")?;
    let cargo_home = std::env::var_os("CARGO_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| user_home.join(".cargo"));
    let rustup_home = std::env::var_os("RUSTUP_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| user_home.join(".rustup"));
    let mut command = Command::new(cargo_home.join("bin/rustc"));
    command
        .current_dir(directory)
        .env_clear()
        .env("HOME", user_home)
        .env("RUSTUP_HOME", rustup_home)
        .env("CARGO_HOME", &cargo_home)
        .env("RUSTUP_TOOLCHAIN", pinned_toolchain()?)
        .env(
            "PATH",
            std::env::join_paths([
                cargo_home.join("bin"),
                PathBuf::from("/usr/bin"),
                PathBuf::from("/bin"),
            ])?,
        )
        .args([
            "--edition=2021",
            "--crate-name=joint_generated",
            "--crate-type=bin",
        ]);
    Ok(command)
}

fn assess_rust(
    options: &Options,
    started: Instant,
    name: &str,
    bytes: &[u8],
    authored: &[u8],
) -> ProbeResult<Value> {
    let directory = options.output_dir.join("rust").join(name);
    fs::create_dir_all(&directory)?;
    let directory = fs::canonicalize(directory)?;
    write_new(&directory.join("generated.rs"), bytes)?;
    let mut command = compiler(&directory)?;
    command.args(["--emit=metadata", "generated.rs", "-o", "generated.rmeta"]);
    let compilation = bounded_command(
        command,
        &directory,
        "compile",
        remaining(options, started).min(Duration::from_secs(10)),
    )?;
    let exact_safe = bytes == authored;
    let mut execution = json!({"status":"not_run","reason":if exact_safe {"compilation_failed"} else {"not_exact_authored_safe_source"}});
    let mut link = Value::Null;
    if compilation["success"] == true && exact_safe {
        let mut command = compiler(&directory)?;
        command.args(["generated.rs", "-o", "generated-bin"]);
        link = bounded_command(
            command,
            &directory,
            "link",
            remaining(options, started).min(Duration::from_secs(10)),
        )?;
        if link["success"] == true {
            let mut command = Command::new(directory.join("generated-bin"));
            command.current_dir(&directory).env_clear();
            execution = bounded_command(
                command,
                &directory,
                "execute",
                remaining(options, started).min(Duration::from_secs(2)),
            )?;
        }
    }
    Ok(
        json!({"source":directory.join("generated.rs"),"source_blake3":blake3::hash(bytes).to_hex().to_string(),
        "exact_authored_safe_source":exact_safe,"compilation":compilation,"link":link,"execution":execution,
        "scope":"Exact generated bytes; no extraction, answer insertion or closing suffix. Metadata checks all selected outputs. Linking/execution only exact safe authored fixture matches, so alternative correct programs are not semantically assessed. Monitored child timeout; not an OS/process-tree sandbox."}),
    )
}

fn evaluate_case(
    model: &Model,
    case: &Case,
    control: Control,
    options: &Options,
) -> ProbeResult<Value> {
    let prompt_tokens = model.encode(&case.prompt)?;
    let full = model.encode(&case.document().text)?;
    let expected = &full[prompt_tokens.len()..];
    let mut session = model.session(control)?;
    session.observe(model, BOS)?;
    for &token in &prompt_tokens {
        session.observe(model, token)?;
    }
    let first = session.predict(model)?;
    let query_state = session.state();
    let first_available = session.candidates().iter().any(|c| c.token == expected[0]);
    let memory_diagnostic = if control != Control::MemoryDisabled
        && model
            .memory_read_version()
            .is_some_and(|version| version.ends_with("/3"))
    {
        session.memory_read_diagnostic(model, expected[0])?
    } else {
        None
    };
    let mut completion_correct = 0;
    let mut completion_available = 0;
    let mut targets = Vec::new();
    for &target in expected {
        let prediction = session.predict(model)?;
        let available = session.candidates().iter().any(|c| c.token == target);
        completion_correct += usize::from(prediction.token == target);
        completion_available += usize::from(available);
        targets.push(
            json!({"target":target,"predicted":prediction.token,"target_in_shortlist":available}),
        );
        session.observe(model, target)?;
    }
    let generation = model.generate(&case.prompt, options.generated_tokens, control)?;
    Ok(
        json!({"id":case.id,"family":case.family,"task":case.task,"world":case.world,
        "fresh_names":case.fresh_names,"fresh_form":case.fresh_form,"filler_units":case.filler_units,"prompt":case.prompt,
        "expected_completion":case.completion,"prompt_tokens":prompt_tokens.len(),"completion_tokens":expected.len(),
        "first_prediction":first,"first_prediction_text":String::from_utf8_lossy(&model.decode(&[first.token])?),
        "first_target_in_shortlist":first_available,"first_correct":first.token == expected[0],
        "first_failure_class":if first.token == expected[0] {"correct"} else if first_available {"shortlisted_scored_incorrectly"} else {"outside_scored_shortlist_admission_unknown"},
        "query_state":query_state,"completion_teacher_forced_correct":completion_correct,
        "completion_teacher_forced_available":completion_available,"completion_targets":targets,
        "generated_completion_prefix_correct":generation.bytes.starts_with(case.completion.as_bytes()),
        "generated_completion_exact":generation.bytes == case.completion.as_bytes(),"generation":generation,
        "shortlist_scope":"Combined post-score top candidate_limit tokens; absence can reflect score-based truncation and does not establish an admission failure.",
        "first_memory_target_admitted":memory_diagnostic.as_ref().map(|diagnostic| diagnostic.target_routes > 0),
        "memory_diagnostic":memory_diagnostic,
        "memory_diagnostic_scope":"Host-only recomputation of prediction. Target routes measure memory admission before combined score truncation. Registered query rows do not establish gradient updates or useful learning; missing query rows do not imply absence of all other feature weights. None means this control/artifact has no active schema-3 diagnostic."}),
    )
}

fn evaluate(options: &Options, started: Instant) -> ProbeResult<Value> {
    let source_bytes = read_bounded(
        options.source.as_deref().ok_or("source required")?,
        MAX_SOURCE_BYTES,
    )?;
    let source: Source = serde_json::from_slice(&source_bytes)?;
    let model = Model::from_bytes(&read_bounded(
        options.model.as_deref().ok_or("model required")?,
        256 * 1024 * 1024,
    )?)?;
    let audit = validate(&source, Some(&model))?;
    let compiler_identity = if options.compiler_cases > 0 {
        let directory = fs::canonicalize(&options.output_dir)?;
        let mut command = compiler(&directory)?;
        command.arg("-vV");
        bounded_command(
            command,
            &directory,
            "compiler-version",
            remaining(options, started).min(Duration::from_secs(10)),
        )?
    } else {
        json!({"status":"not_requested"})
    };
    let mut arms = Vec::new();
    let mut compiled = 0;
    let mut repaired = 0;
    let mut complete = true;
    for control in [Control::Full, Control::MemoryDisabled] {
        let mut cases = Vec::new();
        for case in &source.development {
            if remaining(options, started).is_zero() {
                complete = false;
                break;
            }
            let mut result = evaluate_case(&model, case, control, options)?;
            if control == Control::Full
                && case.family == "rust"
                && compiled < options.compiler_cases
            {
                let continuation: Vec<u8> =
                    serde_json::from_value(result["generation"]["bytes"].clone())?;
                let mut generated = case.prompt.as_bytes().to_vec();
                generated.extend_from_slice(&continuation);
                let assessment = assess_rust(
                    options,
                    started,
                    &format!("case-{compiled}"),
                    &generated,
                    case.document().text.as_bytes(),
                )?;
                if assessment["compilation"]["success"] == false
                    && repaired < options.repair_cases
                    && !remaining(options, started).is_zero()
                {
                    let diagnostics = assessment["compilation"]["diagnostics"]
                        .as_str()
                        .unwrap_or("");
                    let prompt = format!("Repair this Rust program using the actual compiler feedback. Return only the complete corrected Rust source.\nProgram:\n{}\nCompiler feedback:\n{diagnostics}\nCorrected Rust:\n", String::from_utf8_lossy(&generated));
                    let repair =
                        model.generate(&prompt, options.generated_tokens, Control::Full)?;
                    let assessment = assess_rust(
                        options,
                        started,
                        &format!("repair-{repaired}"),
                        &repair.bytes,
                        case.document().text.as_bytes(),
                    )?;
                    result["repair"] = json!({"prompt":prompt,"generation":repair,"assessment":assessment,
                        "scope":"One actual-compiler-feedback continuation; generated bytes are a standalone source file without extraction or wrapper. Expected output is never included in the repair prompt."});
                    repaired += 1;
                }
                result["rust_assessment"] = assessment;
                compiled += 1;
            }
            cases.push(result);
        }
        let families: Vec<_> = ["prose", "rust"].iter().map(|family| {
            let selected: Vec<_> = cases.iter().filter(|case| case["family"] == *family).collect();
            json!({"family":family,"cases":selected.len(),
                "first_correct":selected.iter().filter(|c| c["first_correct"] == true).count(),
                "first_target_in_shortlist":selected.iter().filter(|c| c["first_target_in_shortlist"] == true).count(),
                "first_memory_target_admitted":selected.iter().filter(|c| c["first_memory_target_admitted"] == true).count(),
                "first_memory_target_not_admitted":selected.iter().filter(|c| c["first_memory_target_admitted"] == false).count(),
                "query_context_routes_with_registered_row":selected.iter().filter_map(|c| c["memory_diagnostic"]["query_context_routes_with_registered_row"].as_u64()).sum::<u64>(),
                "query_context_routes_without_registered_row":selected.iter().filter_map(|c| c["memory_diagnostic"]["query_context_routes_without_registered_row"].as_u64()).sum::<u64>(),
                "generated_completion_prefix_correct":selected.iter().filter(|c| c["generated_completion_prefix_correct"] == true).count(),
                "generated_completion_exact":selected.iter().filter(|c| c["generated_completion_exact"] == true).count(),
                "completion_positions":selected.iter().filter_map(|c| c["completion_tokens"].as_u64()).sum::<u64>(),
                "completion_teacher_forced_correct":selected.iter().filter_map(|c| c["completion_teacher_forced_correct"].as_u64()).sum::<u64>(),
                "completion_teacher_forced_available":selected.iter().filter_map(|c| c["completion_teacher_forced_available"].as_u64()).sum::<u64>(),
                "compiled":selected.iter().filter(|c| c["rust_assessment"]["compilation"]["success"] == true).count(),
                "executed_successfully":selected.iter().filter(|c| c["rust_assessment"]["execution"]["success"] == true).count()})
        }).collect();
        arms.push(json!({"control":control,"families":families,"cases":cases}));
        if !complete {
            break;
        }
    }
    Ok(
        json!({"schema":"uor-r4.native-joint-composition-probe/1","status":if complete {"completed"} else {"budget_stopped"},
        "source_blake3":blake3::hash(&source_bytes).to_hex().to_string(),"artifact_cid":model.artifact_cid(),
        "model_config":model.config(),"memory_read_version":model.memory_read_version(),"audit":audit,
        "scope":"Balanced synthetic open development. Teacher-forced completion diagnostics and free generation are separate. Same artifact in both task families and matched memory control. No final held-out, natural language, geometric advantage or alpha qualification.",
        "compiler_cases_used":compiled,"repair_cases_used":repaired,"arms":arms,
        "compiler_toolchain_pin":pinned_toolchain()?,"compiler_identity":compiler_identity,
        "resources":{"elapsed_ms":started.elapsed().as_millis(),"max_seconds":options.max_seconds,
            "peak_rss":"NOT_MEASURED: use external host monitor","threads":1,
            "time_boundary":"Monitored between finite cases; source validation/artifact loading and individual generation are bounded by input/token limits but can overrun remaining time. Compiler children have separate timeout checks."}}),
    )
}

fn main() -> ProbeResult<()> {
    let options = Options::parse()?;
    let started = Instant::now();
    fs::create_dir(&options.output_dir)?;
    let outcome = if options.mode == "prepare" {
        prepare(&options)
    } else {
        evaluate(&options, started)
    };
    let succeeded = outcome.is_ok();
    let mut report =
        outcome.unwrap_or_else(|error| json!({"status":"incomplete","error":error.to_string()}));
    report["options"] = json!(options);
    report["elapsed_ms"] = json!(started.elapsed().as_millis());
    write_new(
        &options.output_dir.join("report.json"),
        &serde_json::to_vec_pretty(&report)?,
    )?;
    println!("{}", serde_json::to_string_pretty(&report)?);
    if succeeded {
        Ok(())
    } else {
        Err("joint probe incomplete; inspect report.json".into())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn options() -> Options {
        Options {
            mode: "prepare".into(),
            output_dir: PathBuf::new(),
            source: None,
            model: None,
            construction_worlds: 128,
            fit_worlds: 128,
            development_worlds: 16,
            generated_tokens: 96,
            max_seconds: 120,
            compiler_cases: 0,
            repair_cases: 0,
        }
    }

    #[test]
    fn whole_task_splits_are_disjoint_balanced_and_vary_development() {
        let source = source(&options());
        validate(&source, None).unwrap();
        for cases in [&source.construction, &source.fit, &source.development] {
            for pair in cases.chunks_exact(2) {
                assert_eq!(pair[0].family, "prose");
                assert_eq!(pair[1].family, "rust");
                assert_eq!(pair[0].world, pair[1].world);
            }
        }
        for family in ["prose", "rust"] {
            assert!(source
                .development
                .iter()
                .any(|case| case.family == family && case.fresh_names));
            assert!(source
                .development
                .iter()
                .any(|case| case.family == family && case.fresh_form));
        }
    }

    #[test]
    fn edited_expected_source_cannot_authorize_execution() {
        let mut source = source(&options());
        source.development[1].completion = " std::process::exit(0); }".into();
        assert!(validate(&source, None)
            .unwrap_err()
            .to_string()
            .contains("authored source generator"));
    }

    #[test]
    fn duplicate_documents_are_rejected() {
        let mut source = source(&options());
        source.fit.push(source.construction[0].clone());
        assert!(validate(&source, None).is_err());
    }

    #[test]
    fn expanded_joint_population_preserves_semantic_source_separation() {
        let mut options = options();
        options.construction_worlds = 256;
        options.fit_worlds = 256;
        options.development_worlds = 32;
        let source = source(&options);
        validate(&source, None).unwrap();
        let case = source
            .development
            .iter()
            .find(|case| case.family == "rust" && case.world == 100_002)
            .unwrap();
        assert!(case.prompt.contains("let doubled = value * 2"));
        assert!(case.completion.starts_with(" + "));
    }
}
