#!/usr/bin/env python3
"""Render manuscript-facing LaTeX inputs and figures for the arXiv-facing rebuild."""

from __future__ import annotations

import csv
import json
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "paper1_assets"
TABLES = ASSETS / "tables"
DATA = ASSETS / "data"
ANALYSIS = ROOT / "router-research" / "results" / "analysis"
DRAFT = ROOT / "paper1_arxiv_rebuild_v2"
GENERATED = DRAFT / "generated"
FIGURES = DRAFT / "figures"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def fmt(value, digits: int = 2, signed: bool = False) -> str:
    number = float(value)
    if signed:
        return f"{number:+.{digits}f}"
    return f"{number:.{digits}f}"


def latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


def route_stats_by_id(doc: dict) -> dict[str, dict]:
    return {row["route_id"]: row for row in doc["route_stats"]}


def render_metrics() -> None:
    fit = read_json(DATA / "scaling_fit_params.json")
    cross = {row["metric"]: row for row in read_csv(TABLES / "cross_dataset_summary.csv")}
    controls = read_csv(TABLES / "key_control_null_result.csv")
    aux_row = next(row for row in controls if row["control_case"] == "Baseline_rationale_aux_loss_control")

    ptb = {row["condition"]: row for row in read_csv(TABLES / "ptb_results.csv")}
    wt2 = {row["condition"]: row for row in read_csv(TABLES / "wt2_results.csv")}

    inc0170 = read_json(ANALYSIS / "inc0170_large_k.json")
    inc0143 = route_stats_by_id(read_json(ANALYSIS / "inc0143_ppmi_semantic_finalize.json"))
    inc0144 = route_stats_by_id(read_json(ANALYSIS / "inc0144_hopf_vs_kmeans_stage3_confirm.json"))
    inc0168 = read_json(ANALYSIS / "inc0168_norm_geometry.json")

    invariance_span = max(
        inc0168[exp]["scaling_exponents"]["TRANS_ORIG"]["alpha"]
        for exp in ["ExpA_L2", "ExpB1_L1_canonicalDeltaR", "ExpC1_L3", "ExpC2_L4"]
    ) - min(
        inc0168[exp]["scaling_exponents"]["TRANS_ORIG"]["alpha"]
        for exp in ["ExpA_L2", "ExpB1_L1_canonicalDeltaR", "ExpC1_L3", "ExpC2_L4"]
    )

    lines = [
        "% Auto-generated by scripts/render_manuscript_inputs.py",
        rf"\newcommand{{\PaperHopfScalingA}}{{{fit['anchor_fit_reference']['TRANS_ORIG']['c']:.3f}}}",
        rf"\newcommand{{\PaperHopfScalingAlpha}}{{{fit['anchor_fit_reference']['TRANS_ORIG']['alpha']:.3f}}}",
        rf"\newcommand{{\PaperPermScalingAlpha}}{{{fit['anchor_fit_reference']['TRANS_PERM']['alpha']:.3f}}}",
        rf"\newcommand{{\PaperHopfLargeKAlpha}}{{{fit['large_k_fit_reference']['TRANS_ORIG']['alpha']:.3f}}}",
        rf"\newcommand{{\PaperRatioAtFourHundred}}{{{inc0170['compression_by_K']['400']['eff_ratio_PERM_over_ORIG']:.2f}}}",
        rf"\newcommand{{\PaperRatioAtFiveThousand}}{{{inc0170['compression_by_K']['5000']['eff_ratio_PERM_over_ORIG']:.2f}}}",
        rf"\newcommand{{\PaperPTBHopfBaselineRatio}}{{{fmt(cross['hopf_vs_baseline_ppl_ratio']['PTB'], 3)}}}",
        rf"\newcommand{{\PaperWTTwoHopfBaselineRatio}}{{{fmt(cross['hopf_vs_baseline_ppl_ratio']['WT2'], 3)}}}",
        rf"\newcommand{{\PaperPTBHopfPermDelta}}{{{fmt(cross['hopf_vs_permuted_delta_ppl']['PTB'], 2, signed=True)}}}",
        rf"\newcommand{{\PaperWTTwoHopfPermDelta}}{{{fmt(cross['hopf_vs_permuted_delta_ppl']['WT2'], 2, signed=True)}}}",
        rf"\newcommand{{\PaperPTBHopfEff}}{{{fmt(ptb['HOPF']['mean_eff_buckets'], 1)}}}",
        rf"\newcommand{{\PaperWTTwoHopfEff}}{{{fmt(wt2['HOPF']['mean_eff_buckets'], 1)}}}",
        rf"\newcommand{{\PaperAuxSparseEff}}{{{fmt(aux_row['learned_sparse_mean_eff_b'], 1)}}}",
        rf"\newcommand{{\PaperStructuredPmax}}{{{fmt(inc0143['SEM_ORIG']['mean_sector_pmax'], 3)}}}",
        rf"\newcommand{{\PaperColPermPmax}}{{{fmt(inc0143['SEM_COL_PERM']['mean_sector_pmax'], 3)}}}",
        rf"\newcommand{{\PaperHopfControlPmax}}{{{fmt(inc0144['HOPF_ORIG']['mean_sector_pmax'], 3)}}}",
        rf"\newcommand{{\PaperKMeansPmax}}{{{fmt(inc0144['KMEANS_ORIG']['mean_sector_pmax'], 3)}}}",
        rf"\newcommand{{\PaperNormInvariantSpan}}{{{invariance_span:.3f}}}",
    ]
    write(GENERATED / "metrics.tex", "\n".join(lines))


def render_setup_main_table() -> None:
    content = r"""
\begin{tabular}{p{0.17\linewidth}p{0.18\linewidth}p{0.21\linewidth}p{0.16\linewidth}p{0.20\linewidth}}
\toprule
Setting & Data & Model / routing regime & Budget / seeds & Main outputs \\
\midrule
Semantic proxy & WikiText-2-derived PPMI-SVD embeddings & Fixed Hopf-derived sector map on normalized static embeddings & $K=25$--$5000$; finalized multi-run analysis chain & Effective routing footprint, concentration statistics, scaling laws \\
Toy LM transfer & PTB and WT2 & 2-layer transformer-like LM with learned top-1, fixed HOPF, or fixed PERMUTED routing & $K=64$; 4000 steps; 2 seeds / dataset & Validation perplexity and effective expert-path count \\
\bottomrule
\end{tabular}
"""
    write(GENERATED / "table_setup_main.tex", content)


def render_setup_appendix_table() -> None:
    content = r"""
\begin{tabular}{ll}
\toprule
Hyperparameter & Value \\
\midrule
Layers & 2 \\
Hidden dimension & 128 \\
Attention heads & 4 \\
Vocabulary size & 5000 \\
Sequence length & 32 \\
Experts & 64 \\
Expert dimension & 128 \\
Training steps & 4000 \\
Datasets & Penn Treebank, WikiText-2 \\
Conditions & BASELINE, HOPF, PERMUTED \\
\bottomrule
\end{tabular}
"""
    write(GENERATED / "table_setup_appendix.tex", content)


def render_lm_tables() -> None:
    ptb = read_csv(TABLES / "ptb_results.csv")
    wt2 = read_csv(TABLES / "wt2_results.csv")

    combined = [
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"Dataset & Condition & Val.\ PPL & Eff.\ paths & $64/\mathrm{eff}_b$ \\",
        r"\midrule",
    ]
    for dataset, rows in [("PTB", ptb), ("WT2", wt2)]:
        for row in rows:
            combined.append(
                f"{dataset} & {row['condition']} & {fmt(row['mean_val_ppl'])} & "
                f"{fmt(row['mean_eff_buckets'])} & {fmt(row['eff_ratio_vs_dense'])}$\\times$ \\\\"
            )
        if dataset == "PTB":
            combined.append(r"\midrule")
    combined.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_lm_combined.tex", "\n".join(combined))

    def detail(rows: list[dict[str, str]], include_std: bool, out_name: str) -> None:
        if include_std:
            header = r"\begin{tabular}{lcccc}"
            lines = [header, r"\toprule", r"Condition & Val.\ PPL & Std.\ PPL & Eff.\ paths & $64/\mathrm{eff}_b$ \\", r"\midrule"]
            for row in rows:
                lines.append(
                    f"{row['condition']} & {fmt(row['mean_val_ppl'])} & {fmt(row['std_val_ppl'])} & "
                    f"{fmt(row['mean_eff_buckets'])} & {fmt(row['eff_ratio_vs_dense'])}$\\times$ \\\\"
                )
        else:
            header = r"\begin{tabular}{lcccc}"
            lines = [header, r"\toprule", r"Condition & Val.\ PPL & Eff.\ paths & $64/\mathrm{eff}_b$ & Params \\", r"\midrule"]
            for row in rows:
                params_m = float(row["n_params"]) / 1_000_000.0
                lines.append(
                    f"{row['condition']} & {fmt(row['mean_val_ppl'])} & {fmt(row['mean_eff_buckets'])} & "
                    f"{fmt(row['eff_ratio_vs_dense'])}$\\times$ & {params_m:.2f}M \\\\"
                )
        lines.extend([r"\bottomrule", r"\end{tabular}"])
        write(GENERATED / out_name, "\n".join(lines))

    detail(ptb, include_std=False, out_name="table_ptb_results.tex")
    detail(wt2, include_std=True, out_name="table_wt2_results.tex")


def render_cross_and_null_tables() -> None:
    cross = {row["metric"]: row for row in read_csv(TABLES / "cross_dataset_summary.csv")}
    controls = read_csv(TABLES / "key_control_null_result.csv")

    cross_rows = [
        ("HOPF / BASELINE PPL ratio", cross["hopf_vs_baseline_ppl_ratio"]["PTB"], cross["hopf_vs_baseline_ppl_ratio"]["WT2"], 3, False, True),
        ("HOPF - PERMUTED PPL", cross["hopf_vs_permuted_delta_ppl"]["PTB"], cross["hopf_vs_permuted_delta_ppl"]["WT2"], 2, True, False),
        ("HOPF effective-path ratio", cross["hopf_eff_ratio_vs_dense"]["PTB"], cross["hopf_eff_ratio_vs_dense"]["WT2"], 2, False, True),
        ("BASELINE eff. paths", cross["baseline_mean_eff_buckets"]["PTB"], cross["baseline_mean_eff_buckets"]["WT2"], 1, False, False),
        ("HOPF eff. paths", cross["hopf_mean_eff_buckets"]["PTB"], cross["hopf_mean_eff_buckets"]["WT2"], 1, False, False),
        ("PERMUTED eff. paths", cross["permuted_mean_eff_buckets"]["PTB"], cross["permuted_mean_eff_buckets"]["WT2"], 1, False, False),
    ]
    lines = [r"\begin{tabular}{lcc}", r"\toprule", r"Metric & PTB & WT2 \\", r"\midrule"]
    for label, p, w, digits, signed, mult in cross_rows:
        suffix = r"$\times$" if mult else ""
        lines.append(f"{label} & {fmt(p, digits, signed)}{suffix} & {fmt(w, digits, signed)}{suffix} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_cross_dataset_summary.tex", "\n".join(lines))

    null_rows = [row for row in controls if "null" in row["control_case"].lower()]
    lines = [r"\begin{tabular}{lcccc}", r"\toprule", r"Dataset & HOPF / BASE & HOPF - PERM & HOPF eff. paths & PERM eff. paths \\", r"\midrule"]
    for row in null_rows:
        lines.append(
            f"{row['dataset_or_setting']} & {fmt(row['hopf_vs_baseline_ratio'], 3)} & "
            f"{fmt(row['hopf_minus_permuted_ppl'], 2, True)} & {fmt(row['hopf_mean_eff_b'], 1)} & {fmt(row['permuted_mean_eff_b'], 1)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_key_null_main.tex", "\n".join(lines))

    lines = [
        r"\begin{tabular}{p{0.19\linewidth}p{0.10\linewidth}p{0.10\linewidth}p{0.10\linewidth}p{0.36\linewidth}}",
        r"\toprule",
        r"Case & HOPF / BASE & HOPF - PERM & Aux eff. paths & Interpretation \\",
        r"\midrule",
    ]
    for row in controls:
        aux_text = "--" if not row["learned_sparse_mean_eff_b"] else fmt(row["learned_sparse_mean_eff_b"], 1)
        lines.append(
            f"{latex_escape(row['dataset_or_setting'])} & {fmt(row['hopf_vs_baseline_ratio'], 3)} & "
            f"{fmt(row['hopf_minus_permuted_ppl'], 2, True)} & {aux_text} & "
            f"{latex_escape(row['interpretation'])} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_key_control_null_result.tex", "\n".join(lines))


def render_proxy_control_tables() -> None:
    inc0143 = route_stats_by_id(read_json(ANALYSIS / "inc0143_ppmi_semantic_finalize.json"))
    inc0144 = route_stats_by_id(read_json(ANALYSIS / "inc0144_hopf_vs_kmeans_stage3_confirm.json"))
    inc0168 = read_json(ANALYSIS / "inc0168_norm_geometry.json")
    inc0172 = read_json(ANALYSIS / "inc0172_moe_substitution.json")

    lines = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Proxy condition & Runs & Sector $p_{\max}$ & Sector entropy & Test MSE \\",
        r"\midrule",
    ]
    for key, label in [("SEM_ORIG", "Structured"), ("SEM_COL_PERM", "Column-permuted")]:
        row = inc0143[key]
        lines.append(
            f"{label} & {row['n_runs']} & {fmt(row['mean_sector_pmax'], 3)} & "
            f"{fmt(row['mean_sector_entropy'], 3)} & {fmt(row['mean_test_mse_after'], 4)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_proxy_structured_control.tex", "\n".join(lines))

    lines = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Routing family & Runs & Sector $p_{\max}$ & Sector entropy & Test MSE \\",
        r"\midrule",
    ]
    for key, label in [("HOPF_ORIG", "Hopf"), ("KMEANS_ORIG", "$K$-means"), ("HOPF_PERM", "Hopf permuted"), ("KMEANS_PERM", "$K$-means permuted")]:
        row = inc0144[key]
        lines.append(
            f"{label} & {row['n_runs']} & {fmt(row['mean_sector_pmax'], 3)} & "
            f"{fmt(row['mean_sector_entropy'], 3)} & {fmt(row['mean_test_mse_after'], 4)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_proxy_hopf_kmeans_control.tex", "\n".join(lines))

    lines = [
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Normalization & Hopf exponent & Permuted exponent & Base exponent \\",
        r"\midrule",
    ]
    labels = {
        "ExpA_L2": "L2",
        "ExpB1_L1_canonicalDeltaR": "L1",
        "ExpC1_L3": "L3",
        "ExpC2_L4": "L4",
    }
    for exp in ["ExpB1_L1_canonicalDeltaR", "ExpA_L2", "ExpC1_L3", "ExpC2_L4"]:
        se = inc0168[exp]["scaling_exponents"]
        lines.append(
            f"{labels[exp]} & {fmt(se['TRANS_ORIG']['alpha'], 3)} & {fmt(se['TRANS_PERM']['alpha'], 3)} & {fmt(se['BASE_ORIG']['alpha'], 3)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_norm_invariance.tex", "\n".join(lines))

    lines = [
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Condition & Val.\ PPL & Eff.\ paths & Params \\",
        r"\midrule",
    ]
    for key in ["BASELINE", "LEARNED_SPARSE", "HOPF", "PERMUTED"]:
        row = inc0172["summary"][key]
        params_m = float(row["n_params"]) / 1_000_000.0
        lines.append(
            f"{latex_escape(key)} & {fmt(row['mean_val_ppl'])} & "
            f"{('--' if math.isnan(row['mean_eff_buckets']) else fmt(row['mean_eff_buckets'], 1))} & {params_m:.2f}M \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_auxiliary_control.tex", "\n".join(lines))


def render_proxy_control_figure() -> None:
    inc0143 = route_stats_by_id(read_json(ANALYSIS / "inc0143_ppmi_semantic_finalize.json"))
    inc0144 = route_stats_by_id(read_json(ANALYSIS / "inc0144_hopf_vs_kmeans_stage3_confirm.json"))

    plt.rcParams.update(
        {
            "font.size": 9,
            "axes.titlesize": 9,
            "axes.labelsize": 9,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
        }
    )

    fig, axes = plt.subplots(1, 2, figsize=(6.8, 2.5))

    labels_a = ["Structured", "Col-perm"]
    pmax_a = [inc0143["SEM_ORIG"]["mean_sector_pmax"], inc0143["SEM_COL_PERM"]["mean_sector_pmax"]]
    entropy_a = [inc0143["SEM_ORIG"]["mean_sector_entropy"], inc0143["SEM_COL_PERM"]["mean_sector_entropy"]]

    ax = axes[0]
    x = range(len(labels_a))
    ax.bar(x, pmax_a, color=["#3559cf", "#b0b7c3"], width=0.52, edgecolor="#30343b", linewidth=0.4)
    ax.set_xticks(list(x), labels_a)
    ax.set_ylabel(r"Sector $p_{\max}$")
    ax.set_title("A. Structure-destroying permutation control")
    ax.set_ylim(0.0, max(pmax_a) * 1.32)
    for i, val in enumerate(pmax_a):
        ax.text(i, val + 0.002, f"{val:.3f}", ha="center", va="bottom", fontsize=8)
    ax2 = ax.twinx()
    ax2.plot(list(x), entropy_a, color="#a84a00", marker="o", markersize=4, linewidth=1.5)
    ax2.set_ylabel("Entropy", color="#b45309")
    ax2.tick_params(axis="y", colors="#b45309", labelsize=7)
    ax.grid(axis="y", color="#d9dde3", linewidth=0.6)
    ax.set_axisbelow(True)

    labels_b = ["Hopf", "$K$-means", "Hopf perm", "$K$-means perm"]
    pmax_b = [
        inc0144["HOPF_ORIG"]["mean_sector_pmax"],
        inc0144["KMEANS_ORIG"]["mean_sector_pmax"],
        inc0144["HOPF_PERM"]["mean_sector_pmax"],
        inc0144["KMEANS_PERM"]["mean_sector_pmax"],
    ]
    entropy_b = [
        inc0144["HOPF_ORIG"]["mean_sector_entropy"],
        inc0144["KMEANS_ORIG"]["mean_sector_entropy"],
        inc0144["HOPF_PERM"]["mean_sector_entropy"],
        inc0144["KMEANS_PERM"]["mean_sector_entropy"],
    ]

    ax = axes[1]
    x = range(len(labels_b))
    ax.bar(
        x,
        pmax_b,
        color=["#3559cf", "#1e7b74", "#8db3e8", "#98d8ce"],
        width=0.58,
        edgecolor="#30343b",
        linewidth=0.4,
    )
    ax.set_xticks(list(x), labels_b, rotation=16, ha="right")
    ax.set_ylabel(r"Sector $p_{\max}$")
    ax.set_title("B. Fixed Hopf routing vs adaptive $K$-means")
    ax.set_ylim(0.0, max(pmax_b) * 1.32)
    for i, val in enumerate(pmax_b):
        ax.text(i, val + 0.0015, f"{val:.3f}", ha="center", va="bottom", fontsize=7.5)
    ax2 = ax.twinx()
    ax2.plot(list(x), entropy_b, color="#a84a00", marker="o", markersize=4, linewidth=1.5)
    ax2.set_ylabel("Entropy", color="#b45309")
    ax2.tick_params(axis="y", colors="#b45309", labelsize=7)
    ax.grid(axis="y", color="#d9dde3", linewidth=0.6)
    ax.set_axisbelow(True)

    for ax in axes:
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

    fig.tight_layout(w_pad=2.0)
    fig.savefig(FIGURES / "paper1_proxy_controls.pdf", bbox_inches="tight")
    fig.savefig(FIGURES / "paper1_proxy_controls.png", bbox_inches="tight", dpi=180)
    plt.close(fig)


def render_scaling_figure() -> None:
    rows = read_csv(DATA / "scaling_points.csv")
    fit = read_json(DATA / "scaling_fit_params.json")

    orig = sorted((int(r["K"]), float(r["effective_bucket_count"])) for r in rows if r["variant"] == "ORIG")
    perm = sorted((int(r["K"]), float(r["effective_bucket_count"])) for r in rows if r["variant"] == "PERM")
    ks = [k for k, _ in orig]

    fig, ax = plt.subplots(figsize=(5.8, 3.6))
    ax.set_xscale("log")
    ax.set_yscale("log")

    dense_y = ks
    ax.plot(ks, dense_y, linestyle="--", color="#888888", linewidth=1.2, label="Dense")

    perm_x = [k for k, _ in perm]
    perm_y = [v for _, v in perm]
    orig_y = [v for _, v in orig]

    ax.scatter(perm_x, perm_y, s=18, color="#d97706", zorder=3)
    ax.scatter(ks, orig_y, s=18, color="#3559cf", zorder=3)

    kline = [25, 50, 75, 100, 150, 200, 400, 600, 1000, 2000, 3000, 5000]
    hopf_fit = [fit["anchor_fit_reference"]["TRANS_ORIG"]["c"] * (k ** fit["anchor_fit_reference"]["TRANS_ORIG"]["alpha"]) for k in kline]
    perm_fit = [fit["large_k_fit_reference"]["TRANS_PERM"]["c"] * (k ** fit["large_k_fit_reference"]["TRANS_PERM"]["alpha"]) for k in kline]
    ax.plot(kline, hopf_fit, color="#3559cf", linewidth=1.6, label=r"Fixed Hopf fit")
    ax.plot(kline, perm_fit, color="#d97706", linewidth=1.6, label=r"Permuted control fit")

    ax.set_xlabel(r"Routing budget $K$")
    ax.set_ylabel("Effective routing footprint")
    ax.grid(which="both", color="#e5e7eb", linewidth=0.6)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(frameon=False, loc="upper left")

    ax.annotate(r"$\hat e \propto K^{0.572}$", xy=(150, 47), xytext=(95, 24),
                fontsize=8, color="#3559cf",
                arrowprops=dict(arrowstyle="-", color="#3559cf", lw=0.9))
    ax.annotate(r"$\hat e \propto K^{0.816}$", xy=(600, 343), xytext=(430, 650),
                fontsize=8, color="#d97706",
                arrowprops=dict(arrowstyle="-", color="#d97706", lw=0.9))

    fig.tight_layout()
    fig.savefig(FIGURES / "paper1_scaling_main.pdf", bbox_inches="tight")
    plt.close(fig)


def render_method_schematic() -> None:
    plt.rcParams.update(
        {
            "font.size": 9,
            "axes.titlesize": 9,
            "axes.labelsize": 9,
        }
    )

    fig, ax = plt.subplots(figsize=(7.2, 2.4))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 3)
    ax.axis("off")

    boxes = [
        (0.3, 1.15, 1.55, 0.78, "#eef3ff", "#5f7fd9", "Normalized\ninput $x \\in \\mathbb{R}^D$"),
        (2.15, 1.15, 1.55, 0.78, "#eef7ee", "#6a9a6c", "Fixed 4D chart\n$(a,b,c,d)$"),
        (4.0, 1.15, 1.8, 0.78, "#fff6ea", "#c28a3f", "Hopf-style\ncoordinates"),
        (6.2, 1.15, 1.65, 0.78, "#f4efff", "#8b72c0", "Transported\nphase $\\alpha_t$"),
        (8.2, 1.15, 1.45, 0.78, "#edf7f4", "#4f9a87", "Sector address\n$k(x)$"),
    ]

    for x, y, w, h, face, edge, label in boxes:
        rect = plt.Rectangle((x, y), w, h, facecolor=face, edgecolor=edge, linewidth=1.1, joinstyle="round")
        ax.add_patch(rect)
        ax.text(x + w / 2, y + h / 2, label, ha="center", va="center")

    arrows = [(1.85, 1.54, 2.15, 1.54), (3.7, 1.54, 4.0, 1.54), (5.8, 1.54, 6.2, 1.54), (7.85, 1.54, 8.2, 1.54)]
    for x1, y1, x2, y2 in arrows:
        ax.annotate("", xy=(x2, y2), xytext=(x1, y1), arrowprops=dict(arrowstyle="->", lw=1.0, color="#444"))

    ax.text(4.9, 2.42, r"$\rho_1,\rho_2,\chi_u,\delta,\alpha$", ha="center", va="center", fontsize=8.5)
    ax.text(7.0, 2.42, r"$\alpha_t = \alpha + \frac{1}{2}\lambda \cos(2\chi)\delta$", ha="center", va="center", fontsize=8.5)
    ax.text(4.9, 0.62, "A fixed geometric map converts a normalized representation into a low-dimensional angular address.", ha="center", va="center", fontsize=8.5)
    ax.text(7.0, 0.28, "Concentrated routing appears only if structured representations occupy those addresses unevenly.", ha="center", va="center", fontsize=8.2)

    fig.tight_layout(pad=0.3)
    fig.savefig(FIGURES / "paper1_method_schematic_v2.pdf", bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    FIGURES.mkdir(parents=True, exist_ok=True)
    render_metrics()
    render_setup_main_table()
    render_setup_appendix_table()
    render_lm_tables()
    render_cross_and_null_tables()
    render_proxy_control_tables()
    render_scaling_figure()
    render_proxy_control_figure()
    render_method_schematic()
    print(f"Rendered manuscript inputs and figures in {DRAFT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
