#!/usr/bin/env python3
"""Render manuscript-facing LaTeX inputs from canonical Paper 1 assets.

This script reads the generated CSV/JSON artifacts under ``paper1_assets/`` and
writes LaTeX snippets for the submission draft. The goal is to keep manuscript
tables and key numeric claims synchronized with the canonical analysis exports
rather than retyping them into LaTeX.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "paper1_assets"
TABLES = ASSETS / "tables"
DATA = ASSETS / "data"
DRAFT = ROOT / "paper1_submission_draft"
GENERATED = DRAFT / "generated"


def read_csv(name: str) -> list[dict[str, str]]:
    with (TABLES / name).open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def read_json(name: str) -> dict:
    with (DATA / name).open("r", encoding="utf-8") as handle:
        return json.load(handle)


def fmt(value: str, digits: int = 2, signed: bool = False) -> str:
    number = float(value)
    if signed:
        return f"{number:+.{digits}f}"
    return f"{number:.{digits}f}"


def tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def render_metrics() -> None:
    ptb = read_csv("ptb_results.csv")
    wt2 = read_csv("wt2_results.csv")
    cross = {row["metric"]: row for row in read_csv("cross_dataset_summary.csv")}
    controls = read_csv("key_control_null_result.csv")
    fit = read_json("scaling_fit_params.json")

    ptb_map = {row["condition"]: row for row in ptb}
    wt2_map = {row["condition"]: row for row in wt2}
    aux_row = next(row for row in controls if row["control_case"] == "Baseline_rationale_aux_loss_control")
    inc0170 = json.loads((ROOT / "router-research" / "results" / "analysis" / "inc0170_large_k.json").read_text())
    ratio_400 = inc0170["compression_by_K"]["400"]["eff_ratio_PERM_over_ORIG"]
    ratio_5000 = inc0170["compression_by_K"]["5000"]["eff_ratio_PERM_over_ORIG"]

    lines = [
        "% Auto-generated by scripts/render_manuscript_inputs.py",
        rf"\newcommand{{\PaperHopfScalingA}}{{{fit['anchor_fit_reference']['TRANS_ORIG']['c']:.3f}}}",
        rf"\newcommand{{\PaperHopfScalingAlpha}}{{{fit['anchor_fit_reference']['TRANS_ORIG']['alpha']:.3f}}}",
        rf"\newcommand{{\PaperPermScalingAlpha}}{{{fit['anchor_fit_reference']['TRANS_PERM']['alpha']:.3f}}}",
        rf"\newcommand{{\PaperHopfLargeKAlpha}}{{{fit['large_k_fit_reference']['TRANS_ORIG']['alpha']:.3f}}}",
        rf"\newcommand{{\PaperRatioAtFourHundred}}{{{ratio_400:.2f}}}",
        rf"\newcommand{{\PaperRatioAtFiveThousand}}{{{ratio_5000:.2f}}}",
        rf"\newcommand{{\PaperPTBHopfBaselineRatio}}{{{fmt(cross['hopf_vs_baseline_ppl_ratio']['PTB'], 3)}}}",
        rf"\newcommand{{\PaperWTTwoHopfBaselineRatio}}{{{fmt(cross['hopf_vs_baseline_ppl_ratio']['WT2'], 3)}}}",
        rf"\newcommand{{\PaperPTBHopfPermDelta}}{{{fmt(cross['hopf_vs_permuted_delta_ppl']['PTB'], 2, signed=True)}}}",
        rf"\newcommand{{\PaperWTTwoHopfPermDelta}}{{{fmt(cross['hopf_vs_permuted_delta_ppl']['WT2'], 2, signed=True)}}}",
        rf"\newcommand{{\PaperPTBHopfEff}}{{{fmt(ptb_map['HOPF']['mean_eff_buckets'], 1)}}}",
        rf"\newcommand{{\PaperWTTwoHopfEff}}{{{fmt(wt2_map['HOPF']['mean_eff_buckets'], 1)}}}",
        rf"\newcommand{{\PaperAuxSparseEff}}{{{fmt(aux_row['learned_sparse_mean_eff_b'], 1)}}}",
    ]
    write(GENERATED / "metrics.tex", "\n".join(lines))


def render_setup_table() -> None:
    content = r"""
\begin{tabular}{p{0.15\linewidth}p{0.20\linewidth}p{0.19\linewidth}p{0.16\linewidth}p{0.18\linewidth}}
\toprule
Setting & Data & Model / routing regime & Budget and training & Primary outputs \\
\midrule
Semantic proxy & WikiText-2-derived PPMI-SVD proxy embeddings & Static normalized embeddings routed by a fixed Hopf-derived map & $K \in [25, 5000]$; confirmed multi-run analysis chain & Effective routing footprint, routing concentration, scaling law \\
Toy LM transfer & Penn Treebank and WikiText-2 & 2-layer transformer-like LM; learned top-1 baseline versus fixed HOPF and fixed PERMUTED routing & $K = 64$, 4000 steps, 2 seeds per dataset & Validation perplexity and effective expert-path count \\
\bottomrule
\end{tabular}
"""
    write(GENERATED / "table_setup_summary.tex", content)


def render_combined_lm_table() -> None:
    ptb = read_csv("ptb_results.csv")
    wt2 = read_csv("wt2_results.csv")

    rows = []
    for dataset, dataset_rows in (("PTB", ptb), ("WT2", wt2)):
        for row in dataset_rows:
            rows.append(
                f"{dataset} & {row['condition']} & {fmt(row['mean_val_ppl'])} & "
                f"{fmt(row['mean_eff_buckets'])} & {fmt(row['eff_ratio_vs_dense'])}$\\times$ \\\\"
            )

    content = "\n".join(
        [
            r"\begin{tabular}{llccc}",
            r"\toprule",
            r"Dataset & Condition & Val.\ PPL & Eff.\ paths & $64/\mathrm{eff}_b$ \\",
            r"\midrule",
            *rows[:3],
            r"\midrule",
            *rows[3:],
            r"\bottomrule",
            r"\end{tabular}",
        ]
    )
    write(GENERATED / "table_lm_combined.tex", content)


def render_ptb_table() -> None:
    ptb = read_csv("ptb_results.csv")
    lines = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Condition & Val.\ PPL & Eff.\ paths & $64/\mathrm{eff}_b$ & Params \\",
        r"\midrule",
    ]
    for row in ptb:
        params_m = float(row["n_params"]) / 1_000_000.0
        lines.append(
            f"{row['condition']} & {fmt(row['mean_val_ppl'])} & {fmt(row['mean_eff_buckets'])} & "
            f"{fmt(row['eff_ratio_vs_dense'])}$\\times$ & {params_m:.2f}M \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_ptb_results.tex", "\n".join(lines))


def render_wt2_table() -> None:
    wt2 = read_csv("wt2_results.csv")
    lines = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Condition & Val.\ PPL & Std.\ PPL & Eff.\ paths & $64/\mathrm{eff}_b$ \\",
        r"\midrule",
    ]
    for row in wt2:
        lines.append(
            f"{row['condition']} & {fmt(row['mean_val_ppl'])} & {fmt(row['std_val_ppl'])} & "
            f"{fmt(row['mean_eff_buckets'])} & {fmt(row['eff_ratio_vs_dense'])}$\\times$ \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_wt2_results.tex", "\n".join(lines))


def render_cross_dataset_table() -> None:
    cross = {row["metric"]: row for row in read_csv("cross_dataset_summary.csv")}
    rows = [
        ("HOPF / BASELINE PPL ratio", cross["hopf_vs_baseline_ppl_ratio"]["PTB"], cross["hopf_vs_baseline_ppl_ratio"]["WT2"], 3, False),
        ("HOPF - PERMUTED PPL", cross["hopf_vs_permuted_delta_ppl"]["PTB"], cross["hopf_vs_permuted_delta_ppl"]["WT2"], 2, True),
        ("HOPF effective-path ratio", cross["hopf_eff_ratio_vs_dense"]["PTB"], cross["hopf_eff_ratio_vs_dense"]["WT2"], 2, False),
        ("BASELINE eff. paths", cross["baseline_mean_eff_buckets"]["PTB"], cross["baseline_mean_eff_buckets"]["WT2"], 1, False),
        ("HOPF eff. paths", cross["hopf_mean_eff_buckets"]["PTB"], cross["hopf_mean_eff_buckets"]["WT2"], 1, False),
        ("PERMUTED eff. paths", cross["permuted_mean_eff_buckets"]["PTB"], cross["permuted_mean_eff_buckets"]["WT2"], 1, False),
    ]

    lines = [
        r"\begin{tabular}{lcc}",
        r"\toprule",
        r"Metric & PTB & WT2 \\",
        r"\midrule",
    ]
    for label, ptb_value, wt2_value, digits, signed in rows:
        suffix = r"$\times$" if "ratio" in label.lower() and "PPL" not in label else ""
        lines.append(
            f"{label} & {fmt(ptb_value, digits, signed)}{suffix} & {fmt(wt2_value, digits, signed)}{suffix} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_cross_dataset_summary.tex", "\n".join(lines))


def render_key_null_table() -> None:
    controls = read_csv("key_control_null_result.csv")
    null_rows = [row for row in controls if "null" in row["control_case"].lower()]

    lines = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Dataset & HOPF / BASE & HOPF - PERM & HOPF eff. paths & PERM eff. paths \\",
        r"\midrule",
    ]
    for row in null_rows:
        lines.append(
            f"{row['dataset_or_setting']} & {fmt(row['hopf_vs_baseline_ratio'], 3)} & "
            f"{fmt(row['hopf_minus_permuted_ppl'], 2, True)} & "
            f"{fmt(row['hopf_mean_eff_b'], 1)} & {fmt(row['permuted_mean_eff_b'], 1)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_key_null_main.tex", "\n".join(lines))


def render_key_control_appendix_table() -> None:
    controls = read_csv("key_control_null_result.csv")
    lines = [
        r"\begin{tabular}{p{0.22\linewidth}p{0.11\linewidth}p{0.11\linewidth}p{0.11\linewidth}p{0.33\linewidth}}",
        r"\toprule",
        r"Case & HOPF / BASE & HOPF - PERM & Aux eff. paths & Interpretation \\",
        r"\midrule",
    ]
    for row in controls:
        case = row["dataset_or_setting"].replace("_", r"\_")
        aux_eff = row["learned_sparse_mean_eff_b"]
        aux_text = fmt(aux_eff, 1) if aux_eff else "--"
        lines.append(
            f"{case} & {fmt(row['hopf_vs_baseline_ratio'], 3)} & "
            f"{fmt(row['hopf_minus_permuted_ppl'], 2, True)} & {aux_text} & "
            f"{tex_escape(row['interpretation'])} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(GENERATED / "table_key_control_null_result.tex", "\n".join(lines))


def main() -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    render_metrics()
    render_setup_table()
    render_combined_lm_table()
    render_ptb_table()
    render_wt2_table()
    render_cross_dataset_table()
    render_key_null_table()
    render_key_control_appendix_table()
    print(f"Rendered manuscript inputs in {GENERATED.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
