-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- v0.2.1 ergonomics surface — sealed wrappers, Certify typeclass, PipelineFailure inductive, and the UOR.Prelude re-exports. Every symbol traces to an ontology entity.

import UOR.Primitives
import UOR.Enums

namespace UOR.Enforcement

open UOR.Primitives

/-- Sealed marker class identifying foundation-produced types. The Lean counterpart of Rust's `OntologyTarget` trait. Implementations are emitted only for foundation certificate / witness shims, mirroring the Rust crate's prelude composition. -/
class OntologyTarget (α : Type) : Prop where
  /-- Sealed witness — only foundation-emitted types may instantiate. -/
  sealed : True

/-- Validated wrapper around a foundation-produced inner value. v0.2.1 pairs Lean's `Validated` with `OntologyTarget` to gate the inner type. Construction is private to UOR.Enforcement, mirroring the Rust `pub(crate) const fn new`. -/
structure Validated (α : Type) [OntologyTarget α] where
  /-- The validated inner value. -/
  inner : α

namespace Validated
/-- Read-only accessor for the validated inner value. -/
def value {α : Type} [OntologyTarget α] (v : Validated α) : α := v.inner
end Validated

/-- Coercion to the inner type so consumers can call certificate methods directly: `cert.targetLevel` rather than `cert.value.targetLevel`. Lean coercions resolve at elaboration time, matching the Rust auto-deref ergonomics. -/
instance {α : Type} [OntologyTarget α] : Coe (Validated α) α where
  coe v := v.inner

/-- Sealed marker class for type:ConstrainedType subclasses that may appear as the parameter of `Grounded`. Counterpart of Rust's `GroundedShape` sealed trait. -/
class GroundedShape (α : Type) : Prop where
  /-- Sealed witness. -/
  sealed : True

/-- BindingsTable carries the static op:GS_5 zero-step access table. -/
structure BindingsTable where
  /-- Sorted-by-address binding entries. -/
  entries : Array (UInt64 × Array UInt8)

/-- The compile-time witness that op:GS_4 holds for the value it carries: σ = 1, freeRank = 0, S = 0, T_ctx = 0. Counterpart of Rust's `Grounded<T: GroundedShape>`. Construction is gated by the back-door minting path. -/
structure Grounded (α : Type) [GroundedShape α] where
  /-- The bindings table laid out for op:GS_5 access. -/
  bindings : BindingsTable
  /-- The Witt level the grounded value was minted at. -/
  wittLevelBits : UInt16
  /-- Content-address of the originating CompileUnit. -/
  unitAddress : UInt64

namespace Grounded
/-- Returns the binding for the given query address, or `none` if absent. -/
def getBinding {α : Type} [GroundedShape α] (g : Grounded α) (q : UInt64) : Option (Array UInt8) :=
  (g.bindings.entries.find? (fun (a, _) => a == q)).map Prod.snd
end Grounded

/-- Sealed shim for cert:GroundingCertificate. Phase 7e.6: carries real `wittBits` from the pipeline. -/
structure GroundingCertificate where
  wittBits : UInt16 := 32
  deriving Inhabited, Repr
instance : OntologyTarget GroundingCertificate where sealed := trivial

/-- Construct a GroundingCertificate carrying the given Witt level. Used by the Lean pipeline driver to mint certificates with the real level. -/
def GroundingCertificate.withWittBits (witt : UInt16) : GroundingCertificate := { wittBits := witt }

/-- Sealed shim for cert:LiftChainCertificate. Exposes the v0.2.1 `targetLevel` accessor. -/
structure LiftChainCertificate where
  wittBits : UInt16 := 32
  deriving Inhabited, Repr
instance : OntologyTarget LiftChainCertificate where sealed := trivial

/-- Construct a LiftChainCertificate carrying the given Witt level. Used by the Lean pipeline driver to mint certificates with the real level. -/
def LiftChainCertificate.withWittBits (witt : UInt16) : LiftChainCertificate := { wittBits := witt }

/-- Sealed shim for cert:InhabitanceCertificate (v0.2.1). -/
structure InhabitanceCertificate where
  wittBits : UInt16 := 32
  deriving Inhabited, Repr
instance : OntologyTarget InhabitanceCertificate where sealed := trivial

/-- Construct a InhabitanceCertificate carrying the given Witt level. Used by the Lean pipeline driver to mint certificates with the real level. -/
def InhabitanceCertificate.withWittBits (witt : UInt16) : InhabitanceCertificate := { wittBits := witt }

/-- Sealed shim for cert:CompletenessCertificate. -/
structure CompletenessCertificate where
  wittBits : UInt16 := 32
  deriving Inhabited, Repr
instance : OntologyTarget CompletenessCertificate where sealed := trivial

/-- Construct a CompletenessCertificate carrying the given Witt level. Used by the Lean pipeline driver to mint certificates with the real level. -/
def CompletenessCertificate.withWittBits (witt : UInt16) : CompletenessCertificate := { wittBits := witt }

/-- Sealed shim for cert:MultiplicationCertificate (v0.2.2 Phase C.4). -/
structure MultiplicationCertificate where
  wittBits : UInt16 := 32
  deriving Inhabited, Repr
instance : OntologyTarget MultiplicationCertificate where sealed := trivial

/-- Construct a MultiplicationCertificate carrying the given Witt level. Used by the Lean pipeline driver to mint certificates with the real level. -/
def MultiplicationCertificate.withWittBits (witt : UInt16) : MultiplicationCertificate := { wittBits := witt }

/-- Returns the Witt level the certificate was issued for, sourced from the `wittBits` field populated by the pipeline. -/
def LiftChainCertificate.targetLevel (cert : LiftChainCertificate) : Nat :=
  cert.wittBits.toNat

/-- Returns the witness value tuple bytes when `verified` is true. v0.2.1 always returns `none`; witness emission lands in v0.2.2. -/
def InhabitanceCertificate.witness (_ : InhabitanceCertificate) : Option (Array UInt8) := none

/-- Sealed shim for proof:ImpossibilityWitness. -/
structure GenericImpossibilityWitness where
  private dummy : Unit := ()
instance : OntologyTarget GenericImpossibilityWitness where sealed := trivial

/-- Sealed shim for proof:InhabitanceImpossibilityWitness (v0.2.1). -/
structure InhabitanceImpossibilityWitness where
  private dummy : Unit := ()
instance : OntologyTarget InhabitanceImpossibilityWitness where sealed := trivial

/-- Input shim for type:ConstrainedType. -/
structure ConstrainedTypeInput where
  private dummy : Unit := ()
instance : OntologyTarget ConstrainedTypeInput where sealed := trivial

/-- Input shim for reduction:CompileUnit. -/
structure CompileUnit where
  private dummy : Unit := ()
instance : OntologyTarget CompileUnit where sealed := trivial

/-- Sealed marker class for impossibility witnesses. -/
class ImpossibilityWitnessKind (α : Type) : Prop where
  /-- Sealed witness. -/
  sealed : True
instance : ImpossibilityWitnessKind GenericImpossibilityWitness where sealed := trivial
instance : ImpossibilityWitnessKind InhabitanceImpossibilityWitness where sealed := trivial

/-- PipelineFailure inductive — variants discovered parametrically from reduction:PipelineFailureReason individuals plus failure: namespace and conformance:ShapeViolationReport. -/
inductive PipelineFailure where
  | DispatchMiss
  | GroundingFailure
  | ConvergenceStall
  | ContradictionDetected
  | CoherenceViolation
  | ShapeMismatch
  | LiftObstructionFailure
  | ShapeViolation
  deriving Repr, BEq, Inhabited

/-- Verdict-producing typeclass. Mirrors the Rust `Certify<I>` trait. The `certify` method accepts an optional `level : Nat` defaulting to 32 (per `Certify::DEFAULT_LEVEL` in the Rust side). -/
class Certify (ρ : Type) (I : Type) where
  Certificate : Type
  Witness : Type
  [certificateTarget : OntologyTarget Certificate]
  [witnessKind : ImpossibilityWitnessKind Witness]
  certify : ρ → I → Except Witness (Validated Certificate)
  certifyAt : ρ → I → Nat → Except Witness (Validated Certificate)

/-- v0.2.1 façade structure for the TowerCompletenessResolver resolver class. The `Certify` instance lives in `UOR.Pipeline`. -/
structure TowerCompletenessResolver where
  private dummy : Unit := ()
def TowerCompletenessResolver.new : TowerCompletenessResolver := {}

/-- v0.2.1 façade structure for the IncrementalCompletenessResolver resolver class. The `Certify` instance lives in `UOR.Pipeline`. -/
structure IncrementalCompletenessResolver where
  private dummy : Unit := ()
def IncrementalCompletenessResolver.new : IncrementalCompletenessResolver := {}

/-- v0.2.1 façade structure for the GroundingAwareResolver resolver class. The `Certify` instance lives in `UOR.Pipeline`. -/
structure GroundingAwareResolver where
  private dummy : Unit := ()
def GroundingAwareResolver.new : GroundingAwareResolver := {}

/-- v0.2.1 façade structure for the InhabitanceResolver resolver class. The `Certify` instance lives in `UOR.Pipeline`. -/
structure InhabitanceResolver where
  private dummy : Unit := ()
def InhabitanceResolver.new : InhabitanceResolver := {}

/-- v0.2.1 façade structure for the MultiplicationResolver resolver class. The `Certify` instance lives in `UOR.Pipeline`. -/
structure MultiplicationResolver where
  private dummy : Unit := ()
def MultiplicationResolver.new : MultiplicationResolver := {}

/-- Witt level marker structures. Reified at the type level so consumers can bind `Mul.{W8}.apply a b` with compile-time level checking. -/
structure W8 where
structure W16 where
structure W24 where
structure W32 where

/-- Ring-op typeclasses. One class per ring op (mul/add/sub/xor/and/or binary; neg/bnot/succ/pred unary), indexed over the Witt level `L`. -/
class AddOp (L : Type) (α : Type) where apply : α → α → α
class AndOp (L : Type) (α : Type) where apply : α → α → α
class BnotOp (L : Type) (α : Type) where apply : α → α
class DivOp (L : Type) (α : Type) where apply : α → α → α
class ModOp (L : Type) (α : Type) where apply : α → α → α
class MulOp (L : Type) (α : Type) where apply : α → α → α
class NegOp (L : Type) (α : Type) where apply : α → α
class OrOp (L : Type) (α : Type) where apply : α → α → α
class PowOp (L : Type) (α : Type) where apply : α → α → α
class PredOp (L : Type) (α : Type) where apply : α → α
class SubOp (L : Type) (α : Type) where apply : α → α → α
class SuccOp (L : Type) (α : Type) where apply : α → α
class XorOp (L : Type) (α : Type) where apply : α → α → α

/-- Ring-op instances at each Witt level. Delegates to the Lean core `UInt8` / `UInt16` / `UInt32` operators for actual arithmetic. -/
instance : AddOp W8 UInt8 where apply a b := a + b
instance : AndOp W8 UInt8 where apply a b := a &&& b
instance : BnotOp W8 UInt8 where apply a := ~~~ a
instance : DivOp W8 UInt8 where apply a b := a
instance : ModOp W8 UInt8 where apply a b := a
instance : MulOp W8 UInt8 where apply a b := a * b
instance : NegOp W8 UInt8 where apply a := 0 - a
instance : OrOp W8 UInt8 where apply a b := a ||| b
instance : PowOp W8 UInt8 where apply a b := a
instance : PredOp W8 UInt8 where apply a := a - 1
instance : SubOp W8 UInt8 where apply a b := a - b
instance : SuccOp W8 UInt8 where apply a := a + 1
instance : XorOp W8 UInt8 where apply a b := a ^^^ b
instance : AddOp W16 UInt16 where apply a b := a + b
instance : AndOp W16 UInt16 where apply a b := a &&& b
instance : BnotOp W16 UInt16 where apply a := ~~~ a
instance : DivOp W16 UInt16 where apply a b := a
instance : ModOp W16 UInt16 where apply a b := a
instance : MulOp W16 UInt16 where apply a b := a * b
instance : NegOp W16 UInt16 where apply a := 0 - a
instance : OrOp W16 UInt16 where apply a b := a ||| b
instance : PowOp W16 UInt16 where apply a b := a
instance : PredOp W16 UInt16 where apply a := a - 1
instance : SubOp W16 UInt16 where apply a b := a - b
instance : SuccOp W16 UInt16 where apply a := a + 1
instance : XorOp W16 UInt16 where apply a b := a ^^^ b
instance : AddOp W24 UInt32 where apply a b := a + b
instance : AndOp W24 UInt32 where apply a b := a &&& b
instance : BnotOp W24 UInt32 where apply a := ~~~ a
instance : DivOp W24 UInt32 where apply a b := a
instance : ModOp W24 UInt32 where apply a b := a
instance : MulOp W24 UInt32 where apply a b := a * b
instance : NegOp W24 UInt32 where apply a := 0 - a
instance : OrOp W24 UInt32 where apply a b := a ||| b
instance : PowOp W24 UInt32 where apply a b := a
instance : PredOp W24 UInt32 where apply a := a - 1
instance : SubOp W24 UInt32 where apply a b := a - b
instance : SuccOp W24 UInt32 where apply a := a + 1
instance : XorOp W24 UInt32 where apply a b := a ^^^ b
instance : AddOp W32 UInt32 where apply a b := a + b
instance : AndOp W32 UInt32 where apply a b := a &&& b
instance : BnotOp W32 UInt32 where apply a := ~~~ a
instance : DivOp W32 UInt32 where apply a b := a
instance : ModOp W32 UInt32 where apply a b := a
instance : MulOp W32 UInt32 where apply a b := a * b
instance : NegOp W32 UInt32 where apply a := 0 - a
instance : OrOp W32 UInt32 where apply a b := a ||| b
instance : PowOp W32 UInt32 where apply a b := a
instance : PredOp W32 UInt32 where apply a := a - 1
instance : SubOp W32 UInt32 where apply a b := a - b
instance : SuccOp W32 UInt32 where apply a := a + 1
instance : XorOp W32 UInt32 where apply a b := a ^^^ b

/-- Fragment classifier markers — emitted parametrically from predicate:DispatchRule individuals whose dispatchPredicate evaluates over type:ConstrainedType. -/
class FragmentMarker (α : Type) : Prop where
  /-- Sealed witness. -/
  sealed : True

structure Is2SatShape where
instance : FragmentMarker Is2SatShape where sealed := trivial
structure IsHornShape where
instance : FragmentMarker IsHornShape where sealed := trivial
structure IsResidualFragment where
instance : FragmentMarker IsResidualFragment where sealed := trivial

/-- DispatchRule entries with predicate IRI, target resolver IRI, and priority. v0.2.1 emits one constant per predicate:DispatchTable individual in the ontology. -/
structure DispatchRule where
  predicateIri : String
  targetResolverIri : String
  priority : Nat

/-- v0.2.1 dispatch table generated from `predicate:InhabitanceDispatchTable`. -/
def InhabitanceDispatchTable : Array DispatchRule := #[
  { predicateIri := "https://uor.foundation/predicate/Is2SatShape", targetResolverIri := "https://uor.foundation/resolver/TwoSatDecider", priority := 0 },
  { predicateIri := "https://uor.foundation/predicate/IsHornShape", targetResolverIri := "https://uor.foundation/resolver/HornSatDecider", priority := 1 },
  { predicateIri := "https://uor.foundation/predicate/IsResidualFragment", targetResolverIri := "https://uor.foundation/resolver/ResidualVerdictResolver", priority := 2 }
]

end UOR.Enforcement
