-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — individual constant namespaces (aggregator).

import UOR.Individuals.Schema
import UOR.Individuals.Op
import UOR.Individuals.Resolver
import UOR.Individuals.Type_
import UOR.Individuals.Foundation
import UOR.Individuals.Observable
import UOR.Individuals.Homology
import UOR.Individuals.Cohomology
import UOR.Individuals.Proof
import UOR.Individuals.Trace
import UOR.Individuals.Morphism
import UOR.Individuals.State
import UOR.Individuals.Reduction
import UOR.Individuals.Convergence
import UOR.Individuals.Division
import UOR.Individuals.Predicate
import UOR.Individuals.Conformance_
