//! Contextual selection of unchanged reverse starts. Authored labels stay offline.
use super::*;

fn examples(tag: &str, worlds: &[(&str, &str, &str, &str)], long: bool) -> Vec<ValueExample> {
    let mut out = Vec::new();
    for (i, &(intro, name, full, single)) in worlds.iter().enumerate() {
        for (j, (prefix, value)) in [(intro, full), ("", full), (intro, single), ("", single)]
            .into_iter()
            .enumerate()
        {
            let padding = if long {
                "quiet sky. ".repeat(96)
            } else {
                String::new()
            };
            out.push(ValueExample {
                id: format!("{tag}/{i}/{j}"),
                prompt: format!("{prefix}{value} holds {name}. {padding}Where is {name}? Answer:"),
                response: format!(" {value}.\n"),
            });
        }
    }
    out
}

fn save(out: &Path, name: &str, model: &Model, docs: &[ValueExample]) -> ProbeResult<Value> {
    let mut cases = Vec::new();
    let started = Instant::now();
    for doc in docs {
        let generation_started = Instant::now();
        let generation = model.generate(&doc.prompt, 32, Control::Full)?;
        let elapsed_ns = generation_started.elapsed().as_nanos();
        cases.push(json!({
            "id":doc.id,"prompt":doc.prompt,"expected":doc.response,
            "exact":generation.bytes == doc.response.as_bytes() && generation.stop == "end_of_document",
            "generation":{"text":generation.text,"bytes":generation.bytes,"stop":generation.stop,
                "token_ids":generation.token_ids,"utf8_valid":generation.utf8_valid},
            "generation_elapsed_ns":elapsed_ns,"work":generation.work
        }));
    }
    let report = json!({"artifact":model.artifact_cid(),
        "exact":cases.iter().filter(|case|case["exact"] == true).count(),"total":cases.len(),
        "elapsed_ns":started.elapsed().as_nanos(),"cases":cases,
        "scope":"Complete prompt/expected/generated bytes, EOS, per-case whole generation elapsed time and aggregate Generation.work retained. Captured state and per-token traces omitted; training candidate/feature traces remain in fit.json."
    });
    write_json(&out.join(format!("{name}.json")), &report)?;
    Ok(report)
}

fn exact(report: &Value) -> bool {
    report["total"].as_u64().is_some_and(|total| total > 0) && report["exact"] == report["total"]
}

fn subset(out: &Path, name: &str, report: &Value, docs: &[ValueExample]) -> ProbeResult<Value> {
    let ids: BTreeSet<_> = docs.iter().map(|doc| doc.id.as_str()).collect();
    let mut selected = report.clone();
    let cases = selected["cases"]
        .as_array_mut()
        .ok_or("response cases absent")?;
    cases.retain(|case| case["id"].as_str().is_some_and(|id| ids.contains(id)));
    if cases.len() != docs.len() {
        return Err("response subset identity mismatch".into());
    }
    let total = cases.len();
    let exact = cases.iter().filter(|case| case["exact"] == true).count();
    selected["total"] = json!(total);
    selected["exact"] = json!(exact);
    selected["elapsed_scope"] = json!("Top-level elapsed time covers all 52 supplied cases; per-case elapsed and work are exact for this subset. No generation repeated to produce this view.");
    write_json(&out.join(format!("{name}.json")), &selected)?;
    Ok(selected)
}

fn diagnostics() -> Vec<ValueExample> {
    [
        ("changed-order", "calvi is in fine sand. Where is calvi? Answer:", " fine sand.\n"),
        ("distractor-first", "notes say soft clay holds nerri. log tells Silver Valley holds jovri. Where is jovri? Answer:", " Silver Valley.\n"),
        ("distractor-last", "log tells Silver Valley holds jovri. notes say soft clay holds nerri. Where is jovri? Answer:", " Silver Valley.\n"),
        ("role-value", "report notes notes cove holds kalri. notes say soft clay holds nerri. Where is kalri? Answer:", " notes cove.\n"),
        // Different ordinary assertions conflict; only an explicit revision
        // permits replacement. Preserve the earlier v2 diagnostic oracle error.
        ("conflicting-assertions", "notes say fine sand holds calvi. log tells clear water bay holds calvi. Where is calvi? Answer:", " Unknown.\n"),
    ]
    .into_iter()
    .map(|(id, prompt, response)| ValueExample {
        id: format!("context-start-diagnostic/{id}"),
        prompt: prompt.into(),
        response: response.into(),
    })
    .collect()
}

pub(super) fn run(args: &[String]) -> ProbeResult<()> {
    if args.len() != 3 {
        return Err("contextual-start PARENT ROOT NEW_DIRECTORY".into());
    }
    let started = Instant::now();
    // Shared writer accounting includes the model as well as evidence files.
    // The recorded projection allows 32 MiB for the artifact and 16 MiB for reports.
    OUTPUT_BYTES_REMAINING.store(48 * 1024 * 1024, Ordering::Relaxed);
    let root = Path::new(&args[1]);
    let out = Path::new(&args[2]);
    fs::create_dir(out)?;
    let mut fit = examples(
        "start-fit",
        &[
            ("Notes say ", "telra", "Amber Meadow", "Amber"),
            ("Log tells ", "mevin", "Dawn River Bend", "Dawn"),
        ],
        false,
    );
    fit.extend(examples(
        "context-start-fit",
        &[
            ("notes say ", "calvi", "fine sand", "fine"),
            ("log tells ", "davri", "clear water bay", "clear"),
            ("the report says ", "selra", "quiet river", "quiet"),
            ("report notes ", "zerni", "says meadow", "says"),
            ("file says ", "larvi", "notes river", "notes"),
            ("Records show ", "merli", "Golden Harbor", "Golden"),
        ],
        false,
    ));
    let original_fit = fit.clone();
    let transfer_fit = examples(
        "context-start-transfer-fit",
        &[
            ("log tells ", "pervi", "Ivory Marsh", "Ivory"),
            ("report notes ", "vilra", "notes haven", "notes"),
            ("A ledger says ", "murvi", "Emerald Ridge", "Emerald"),
        ],
        false,
    );
    fit.extend(transfer_fit.iter().cloned());
    let title_context_fit = examples(
        "context-start-title-fit",
        &[
            ("Record notes ", "helvi", "Copper Shore", "Copper"),
            ("Memo notes ", "darvi", "Quartz Hill", "Quartz"),
        ],
        false,
    );
    fit.extend(title_context_fit.iter().cloned());
    let supplied_fit = fit;
    let upstream_ids = ["context-start-fit/2/0", "context-start-fit/2/1"];
    let (upstream, fit): (Vec<_>, Vec<_>) = supplied_fit
        .iter()
        .cloned()
        .partition(|doc| upstream_ids.contains(&doc.id.as_str()));
    if original_fit.len() != 32
        || transfer_fit.len() != 12
        || title_context_fit.len() != 8
        || supplied_fit.len() != 52
        || fit.len() != 50
        || upstream.len() != 2
    {
        return Err("explicit construction eligibility counts changed".into());
    }
    let eligibility = json!({
        "original_supplied":32,"first_open_feedback_construction":12,"title_open_feedback_construction":8,
        "added_open_feedback_construction":20,"supplied":52,"supported_fit":50,"upstream_diagnostics":2,
        "excluded_ids":upstream_ids,
        "reason":"The preceding contextual-start-angular attempt stopped with no completed reverse write in context-start-fit/2/0. Inspection of that attempt's parent-construction evidence established no parent record for both multiword quiet river cases /2/0 and /2/1, while the singleton cases /2/2 and /2/3 had records. This is explicit observed upstream writer eligibility, not filtering by learned correctness. The same two unsupported cases remain visible in complete 52-case comparisons, original32 subsets and upstream diagnostics. No additional case is excluded.",
        "construction_extension":"Twelve explicit OPEN-feedback construction contrasts follow the cross-owner artifact's residual singleton log tells/report notes and prior A ledger says errors. New owners and payloads use the unchanged runtime feature law; these are construction, not fresh evaluation.",
        "title_construction_extension":"Eight explicit OPEN-feedback construction contrasts follow artifact af997b17's remaining prior Report notes Cobalt Field/Cobalt errors. Record notes/helvi/Copper Shore/Copper and Memo notes/darvi/Quartz Hill/Quartz vary title-case introductory words under distinct single owners. Report is not added to fitting. These exercise shared unknown-title-before-notes behavior under the unchanged cross-owner registry rule; they are construction, not fresh evaluation.",
        "prior_error":"no completed reverse write in context-start-fit/2/0",
        "prior_attempt":"contextual-start-angular",
        "scope":"Selection covers supported construction 50/50, unchanged OPEN 12/12 and prior preservation including the prior-start challenge8; it does not establish success on all 52 supplied cases or all original32 cases. Admission and runtime are unchanged."
    });
    let open = examples(
        "context-start-open",
        &[
            ("notes say ", "nerri", "soft clay", "soft"),
            ("report notes ", "kalri", "notes cove", "notes"),
            ("log tells ", "jovri", "Silver Valley", "Silver"),
        ],
        false,
    );
    let prior_open = examples(
        "start-open",
        &[
            ("A ledger says ", "tesvi", "Pearl Cove", "Pearl"),
            ("Report notes ", "vorin", "Cobalt Field", "Cobalt"),
        ],
        false,
    );
    let diagnostics = diagnostics();
    write_json(
        &out.join("source.json"),
        &json!({
            "supplied_fit":supplied_fit,"fit":fit,"upstream_writer_diagnostics":upstream,"eligibility":eligibility,
            "original_supplied_fit":original_fit,"open_feedback_construction":transfer_fit,
            "title_open_feedback_construction":title_context_fit,
            "development":open,"prior_development":prior_open,"diagnostics":diagnostics,
            "scope":"52 supplied construction: original32 and the previous12 OPEN-feedback construction contrasts remain unchanged; eight title-context OPEN-feedback construction contrasts are appended. Exactly the same two previously measured parent no-write cases are explicit upstream diagnostics, leaving50 supported fit cases. Complete52 and original32 output remain reported; selection uses50. Twelve unchanged OPEN development cases and prior-start challenge8 remain selection gates. Single completed reverse write per fit document is enforced by training. Records show is an already opened cue with a new payload; old exact diagnostic is excluded. The earlier relation-start fresh eight and new fresh12 remain unopened before selection. Diagnostics are inference-only and do not enter selection. All exact counts require complete output bytes and EOS."
        }),
    )?;
    let parent = Model::from_bytes(&fs::read(&args[0])?)?;
    write_json(&out.join("eligibility.json"), &eligibility)?;
    let before = save(out, "parent-construction", &parent, &supplied_fit)?;
    let before_original = subset(out, "parent-original-construction", &before, &original_fit)?;
    let before_supported = subset(out, "parent-supported-construction", &before, &fit)?;
    subset(out, "upstream-writer-parent", &before, &upstream)?;
    let before_open = save(out, "parent-development", &parent, &open)?;
    let (model, report) = match parent.fit_contextual_relation_start(&fit) {
        Ok(value) => value,
        Err(error) => {
            write_json(
                &out.join("fit-error.json"),
                &json!({"parent":parent.artifact_cid(),"error":error.to_string(),"status":"FIT_FAILED","elapsed_ms":started.elapsed().as_millis(),"fresh":"NOT_RUN"}),
            )?;
            return Err(error.into());
        }
    };
    write_json(&out.join("fit.json"), &report)?;
    write_new(&out.join("model.json"), &model.to_bytes()?)?;
    let mut wire: Value = serde_json::from_slice(&model.to_bytes()?)?;
    let mut old: Value = serde_json::from_slice(&parent.to_bytes()?)?;
    let object = wire.as_object_mut().ok_or("model shape")?;
    let block = object
        .remove("relation_start")
        .ok_or("start block absent")?;
    object
        .remove("relation_start_context")
        .ok_or("context registry absent")?;
    if block["parent_artifact"] != parent.artifact_cid() {
        return Err("wrong contextual start parent".into());
    }
    for value in [&mut wire, &mut old] {
        let object = value.as_object_mut().ok_or("model shape")?;
        object.remove("artifact_cid");
        object.remove("uor_model_address");
    }
    if wire != old {
        return Err("parent parameters changed".into());
    }
    let reloaded = Model::from_bytes(&fs::read(out.join("model.json"))?)?;
    if reloaded.to_bytes()? != model.to_bytes()? {
        return Err("contextual artifact roundtrip changed".into());
    }
    let disabled = model.without_relation_start_context()?;
    let supplied_construction = save(out, "construction", &model, &supplied_fit)?;
    let original_construction = subset(
        out,
        "original-construction",
        &supplied_construction,
        &original_fit,
    )?;
    let construction = subset(out, "supported-construction", &supplied_construction, &fit)?;
    subset(
        out,
        "upstream-writer-full",
        &supplied_construction,
        &upstream,
    )?;
    let development = save(out, "development", &model, &open)?;
    let disabled_supplied = save(
        out,
        "context-disabled-construction",
        &disabled,
        &supplied_fit,
    )?;
    let disabled_construction = subset(
        out,
        "context-disabled-supported-construction",
        &disabled_supplied,
        &fit,
    )?;
    let disabled_original = subset(
        out,
        "context-disabled-original-construction",
        &disabled_supplied,
        &original_fit,
    )?;
    subset(
        out,
        "upstream-writer-context-disabled",
        &disabled_supplied,
        &upstream,
    )?;
    let disabled_development = save(out, "context-disabled-development", &disabled, &open)?;
    let mut preserved = reverse_span::preserve(&model, root, out)?;
    let prior = save(
        &out.join("preservation"),
        "prior-start-open",
        &model,
        &prior_open,
    )?;
    preserved &= exact(&prior);
    for (name, names, values, prefix) in [
        (
            "reverse-construction",
            ["nelra", "vesk"],
            ["Orin Grove", "Amber Grove", "Silver Cape"],
            "",
        ),
        (
            "reverse-open",
            ["serin", "mavra"],
            ["Copper Vale", "Cobalt Vale", "Ivory Pier"],
            "Record: ",
        ),
        (
            "reverse-prior-fresh",
            ["belvi", "norvi"],
            ["Quiet River Bend", "Silver River Bend", "Violet Quay"],
            "",
        ),
    ] {
        let report = reverse_span::panel(&model, names, values, prefix)?;
        preserved &=
            exact(&report) && report["version_counts_exact"] == true && report["isolation"] == true;
        write_json(
            &out.join("preservation").join(format!("{name}.json")),
            &report,
        )?;
    }
    let short = reverse_span::short(&model)?;
    preserved &= exact(&short);
    write_json(&out.join("preservation/reverse-short.json"), &short)?;
    let selected = exact(&construction) && exact(&development) && preserved;
    write_json(
        &out.join("selection.json"),
        &json!({
            "artifact":model.artifact_cid(),"parent":parent.artifact_cid(),"parent_parameters_equal":true,
            "artifact_roundtrip_equal":true,"selected_before_fresh":selected,
            "eligibility":eligibility,"supplied_construction":supplied_construction["exact"],"supplied_construction_total":52,
            "original_construction":original_construction["exact"],"original_construction_total":32,
            "construction":construction["exact"],"construction_total":construction["total"],
            "development":development["exact"],"development_total":development["total"],
            "context_disabled_construction":disabled_construction["exact"],
            "context_disabled_development":disabled_development["exact"],
            "control_scope":"Context-disabled retains the registry, candidate features and work; contextual H4 feature roots are set to identity while learned shape roots remain.",
            "preservation":preserved,"fresh":"NOT_RUN_AT_SELECTION","elapsed_ms":started.elapsed().as_millis()
        }),
    )?;
    for (label, arm) in [
        ("parent", &parent),
        ("full", &model),
        ("context-disabled", &disabled),
    ] {
        save(out, &format!("diagnostics-{label}"), arm, &diagnostics)?;
    }
    let fresh = if selected {
        let fresh = examples(
            "context-start-fresh",
            &[
                ("notes say ", "revni", "pale dune", "pale"),
                ("report notes ", "sorli", "says inlet", "says"),
                ("log tells ", "talvi", "Violet Harbor", "Violet"),
            ],
            true,
        );
        write_json(
            &out.join("fresh-source.json"),
            &json!({"fresh":fresh,"scope":"Twelve first-use cases, new owners/payloads, familiar structural cues and role-value words. Ninety-six padding sentences evict source before query. First executed after selection; earlier relation-start fresh eight remain unopened."}),
        )?;
        save(out, "fresh", &model, &fresh)?
    } else {
        json!({"status":"NOT_RUN_SELECTION_FAILED"})
    };
    let summary = json!({
        "artifact":model.artifact_cid(),"parent":parent.artifact_cid(),
        "parent_construction":before["exact"],"parent_construction_total":52,
        "parent_supported_construction":before_supported["exact"],"parent_supported_construction_total":50,
        "parent_original_construction":before_original["exact"],"original_construction_total":32,
        "original_construction":original_construction["exact"],"context_disabled_original_construction":disabled_original["exact"],
        "parent_development":before_open["exact"],"eligibility":eligibility,
        "supplied_construction":supplied_construction["exact"],"supplied_construction_total":52,
        "context_disabled_supplied_construction":disabled_supplied["exact"],
        "construction":construction["exact"],"construction_total":construction["total"],
        "development":development["exact"],"development_total":development["total"],
        "context_disabled_construction":disabled_construction["exact"],
        "context_disabled_development":disabled_development["exact"],
        "preservation":preserved,"selected":selected,"fresh":fresh["exact"],
        "fresh_total":fresh["total"],"fresh_status":fresh["status"],"elapsed_ms":started.elapsed().as_millis()
    });
    write_json(&out.join("report.json"), &summary)?;
    println!("{summary}");
    Ok(())
}
