//! One separator-conditioned source-span intervention, with compact evidence.
use super::*;
/// Keep complete input/output, verdict and work; omit bulky per-step traces.
pub(super) fn compact(mut value: Value) -> Value {
    fn visit(v: &mut Value) {
        match v {
            Value::Object(map) => {
                if map.contains_key("text") && map.contains_key("stop") {
                    map.remove("steps");
                    map.remove("trace");
                    map.remove("value_trace");
                    map.remove("completion_trace");
                }
                for v in map.values_mut() {
                    visit(v);
                }
            }
            Value::Array(xs) => {
                for x in xs {
                    visit(x);
                }
            }
            _ => {}
        }
    }
    visit(&mut value);
    value["report_scope"] = json!("Complete prompts, expected/generated bytes, EOS verdicts and aggregate work retained; per-token traces omitted to bound storage.");
    value
}

/// Decision-bearing preservation receipts without captured state or work traces.
/// Input and expected labels are retained as offline evidence, never serving data.
pub(super) fn lean(value: Value) -> Value {
    let Some(report) = value.as_object() else {
        return value;
    };
    let mut out = serde_json::Map::new();
    // Keep existing scalar aggregate counts, identities and scope annotations.
    for (key, value) in report {
        if !value.is_array() && !value.is_object() {
            out.insert(key.clone(), value.clone());
        }
    }
    if let Some(cases) = report.get("cases").and_then(Value::as_array) {
        let rows = cases.iter().map(|case| {
            let mut row = serde_json::Map::new();
            for key in [
                "id", "input", "prompt", "query", "expected", "expected_action",
                "expected_operands", "expected_writes", "text", "stop", "terminated",
                "exact", "used_intermediate", "writes_exact", "initial_generation_failed",
                "actual_action", "actual_operands", "actual_writes",
            ] {
                if let Some(value) = case.get(key) {
                    row.insert(key.into(), value.clone());
                }
            }
            if let Some(generation) = case.get("generation").and_then(Value::as_object) {
                let mut actual = serde_json::Map::new();
                for key in ["text", "stop"] {
                    if let Some(value) = generation.get(key) {
                        actual.insert(key.into(), value.clone());
                    }
                }
                row.insert("generation".into(), Value::Object(actual));
            }
            if let Some(decision) = case.get("decision") {
                row.insert("actual_action".into(), decision.get("action").cloned().unwrap_or(Value::Null));
                if let Some(operands) = decision.get("operands").and_then(Value::as_array) {
                    row.insert("actual_operands".into(), Value::Array(operands.iter().map(|r| r["value"].clone()).collect()));
                }
            }
            if let Some(records) = case.get("relations").and_then(|r| r.get("records")).and_then(Value::as_array) {
                let writes = records.iter().filter(|r| r["id"].as_u64().unwrap_or(0) != 0).map(|r| {
                    json!({"owner_end_byte":r["owner"]["byte_end"],"value_end_byte":r["value"]["byte_end"],"action":r["action"]})
                }).collect();
                row.insert("actual_writes".into(), Value::Array(writes));
            }
            Value::Object(row)
        }).collect();
        out.insert("cases".into(), Value::Array(rows));
    }
    out.insert("report_scope".into(), json!("Lean preservation receipt: case identities, available complete inputs and expected labels, actual text/termination/actions/writes, verdicts and aggregate counts retained. Captured state, decisions, work and token traces omitted. Session verification remains unchanged."));
    Value::Object(out)
}
fn save(
    out: &Path,
    label: &str,
    model: &Model,
    docs: &[ValueExample],
    control: Control,
) -> ProbeResult<()> {
    let report = compact(source_noread::responses(model, docs, false, control)?);
    write_json(&out.join(format!("{label}.json")), &report)?;
    println!(
        "{}",
        json!({"split":label,"exact":report["exact"],"total":report["total"]})
    );
    Ok(())
}
fn examples(prefix: &str, owner: &str, places: &[&str]) -> Vec<ValueExample> {
    places
        .iter()
        .enumerate()
        .map(|(i, place)| ValueExample {
            id: format!("{prefix}/{i}"),
            prompt: format!("User: {owner} lives in {place}.\nUser: Where is {owner}?\nAssistant:"),
            response: format!(" {place}.\n"),
        })
        .collect()
}
pub(super) fn run(args: &[String]) -> ProbeResult<()> {
    match args.first().map(String::as_str) {
        Some("fit") if args.len() == 4 => {
            let root = Path::new(&args[2]);
            let out = Path::new(&args[3]);
            fs::create_dir(out)?;
            let parent = Model::from_bytes(&fs::read(&args[1])?)?;
            let mut fit = examples(
                "span-fit",
                "adara",
                &["Old Haven", "San Pedro del Mar", "Aster-Bay", "Dover"],
            );
            fit.push(ValueExample {
                id: "span-fit/line".into(),
                prompt: "User: adara lives in Merrow\nUser: Where is adara?\nAssistant:".into(),
                response: " Merrow.\n".into(),
            });
            let source: Value = serde_json::from_slice(&fs::read(
                root.join("contextual-emission-baseline-source.json"),
            )?)?;
            let open: Vec<ValueExample> = serde_json::from_value(source["development"].clone())?;
            write_json(
                &out.join("source.json"),
                &json!({"fit":fit,"development":open,"scope":"Separator-conditioned source span; development exposed by the recorded parent baseline."}),
            )?;
            save(out, "parent-construction", &parent, &fit, Control::Full)?;
            let (candidate, report) = parent.fit_source_span(&fit)?;
            write_new(&out.join("model.json"), &candidate.to_bytes()?)?;
            write_json(&out.join("fit.json"), &report)?;
            println!("{}", report);
            save(out, "construction", &candidate, &fit, Control::Full)?;
            save(out, "development", &candidate, &open, Control::Full)?;
            save(
                out,
                "disabled-development",
                &candidate,
                &open,
                Control::SourceSpanDisabled,
            )?;
            for (file, split, label) in [
                (
                    "source-order-angular256/source.json",
                    "fit",
                    "retained-construction",
                ),
                (
                    "source-order-angular256/fresh-source.json",
                    "",
                    "source-context-prior-fresh",
                ),
                (
                    "literal-binding-source.json",
                    "first_use",
                    "literal-prior-fresh",
                ),
                (
                    "joint-admission-source.json",
                    "first_use",
                    "admission-prior-fresh",
                ),
                (
                    "source-noread-source-v2.json",
                    "first_use",
                    "source-prior-fresh",
                ),
            ] {
                let s: Value = serde_json::from_slice(&fs::read(root.join(file))?)?;
                let docs: Vec<ValueExample> = serde_json::from_value(if split.is_empty() {
                    s
                } else {
                    s[split].clone()
                })?;
                save(out, label, &candidate, &docs, Control::Full)?;
            }
            let preserve = out.join("preservation");
            fs::create_dir(&preserve)?;
            source_noread::preserve_model_compact(candidate, root, &preserve)?;
        }
        Some("fresh") if args.len() == 3 => {
            let out = Path::new(&args[2]);
            let model = Model::from_bytes(&fs::read(&args[1])?)?;
            let mut docs = examples(
                "span-fresh",
                "velmi",
                &[
                    "Blue Harbour",
                    "Santa Luz de Oro",
                    "North-East",
                    "Fern",
                    "Vale  Crest",
                ],
            );
            docs.extend(examples(
                "span-fresh-other",
                "torva",
                &["Blue Ridge", "Silver Vale Bay", "West-End", "Briar"],
            ));
            docs.push(ValueExample {
                id: "span-fresh/unsupported".into(),
                prompt: "User: velmi lives in Blue Harbour.\nUser: Where is torva?\nAssistant:"
                    .into(),
                response: " Unknown.\n".into(),
            });
            // Explicit out-of-scope boundary: same separator cannot encode phrase end.
            let boundary=vec![ValueExample {id:"span-boundary/same-space".into(),prompt:"User: velmi lives in Blue Harbour near Briar.\nUser: Where is velmi?\nAssistant:".into(),response:" Blue Harbour.\n".into()}];
            write_json(
                &out.join("fresh-source.json"),
                &json!({"fresh":docs,"semantic_boundary":boundary,"scope":"Separately authored fixed cases, first executed after design selection; not used for fitting. Double-space is an intentional unsupported-gap check, not a expected complete-span capability."}),
            )?;
            save(out, "fresh", &model, &docs, Control::Full)?;
            save(
                out,
                "fresh-disabled",
                &model,
                &docs,
                Control::SourceSpanDisabled,
            )?;
            save(out, "semantic-boundary", &model, &boundary, Control::Full)?;
        }
        _ => return Err("source-span fit PARENT ROOT NEW_DIR | fresh MODEL EXISTING_DIR".into()),
    }
    Ok(())
}
