//! Adversarial Challenger Test Suite — Milestone M3:
//! Streaming UTF-8 Decoding, Stop-Token Suppression & Stream Lifecycle Invariants.
//! File: crates/uor-r4-integer/tests/adversarial_m3_streaming_utf8_stop_tokens.rs
//!
//! Empirical adversarial verification covering:
//! 1. IncrementalUtf8Decoder pathological byte splits:
//!    - 4-byte emojis (🦀, 🚀, 🧪, 🧠, 🤖, 🧬) split byte-by-byte (1 byte per call) across 4 calls:
//!      * 0 replacement characters (`\u{FFFD}`)
//!      * Exact character reconstruction
//!    - Arbitrary integer partitions of 4-byte, 3-byte, and 2-byte sequences:
//!      * 3-byte CJK characters (語, 漢, 字, 中, 文) across [1,1,1], [1,2], [2,1] splits
//!      * 2-byte accented letters (é, ü, ñ, ç, ö, α, β) across [1,1] splits
//!    - Invalid byte sequences followed by valid sequences:
//!      * Recovery without buffer corruption, hanging pending bytes, or crash
//!    - Trailing incomplete bytes flushed with `\u{FFFD}` cleanly upon termination
//!
//! 2. Stop-token suppression and lifecycle in ChatTokenStream:
//!    - `<|turn_end|>` (id 6) generated by model is NEVER yielded to consumer string stream
//!    - `<|eos|>` (id 1) generated by model is NEVER yielded to consumer string stream
//!    - Session state appends stop token internally to dialogue memory
//!    - Session enters ready state for next user turn with incremented turn counter
//!    - Immediate stop on token 0 (turn end / eos / custom stop as first generated token)
//!    - Delayed stop token after multiple text tokens: text tokens yielded, stop token suppressed

use uor_r4_integer::{
    Bundle, ChatSession, IncrementalUtf8Decoder, RoleToken, SamplePolicy, StreamStopReason,
};

// ============================================================================
// PART 1: IncrementalUtf8Decoder Adversarial Stress Tests
// ============================================================================

#[test]
fn test_adversarial_utf8_emoji_byte_by_byte_split_4calls() {
    let emojis = [
        ("🦀", "Crab", "0xF0, 0x9F, 0xA6, 0x80"),
        ("🚀", "Rocket", "0xF0, 0x9F, 0x9A, 0x80"),
        ("🧪", "TestTube", "0xF0, 0x9F, 0xA7, 0xAA"),
        ("🧠", "Brain", "0xF0, 0x9F, 0xA7, 0xA0"),
        ("🤖", "Robot", "0xF0, 0x9F, 0xA4, 0x96"),
        ("🧬", "DNA", "0xF0, 0x9F, 0xA7, 0xAC"),
    ];

    for &(emoji, name, byte_desc) in &emojis {
        let bytes = emoji.as_bytes();
        assert_eq!(bytes.len(), 4, "Emoji {name} must be 4 bytes");

        let mut decoder = IncrementalUtf8Decoder::new();

        // Call 1: push byte 0
        let chunk0 = decoder.push_bytes(&bytes[0..1]);
        assert_eq!(
            chunk0, None,
            "Call 1 for {name} ({byte_desc}) must return None"
        );
        assert_eq!(decoder.pending_len(), 1);
        assert!(!decoder.is_empty());

        // Call 2: push byte 1
        let chunk1 = decoder.push_bytes(&bytes[1..2]);
        assert_eq!(
            chunk1, None,
            "Call 2 for {name} ({byte_desc}) must return None"
        );
        assert_eq!(decoder.pending_len(), 2);

        // Call 3: push byte 2
        let chunk2 = decoder.push_bytes(&bytes[2..3]);
        assert_eq!(
            chunk2, None,
            "Call 3 for {name} ({byte_desc}) must return None"
        );
        assert_eq!(decoder.pending_len(), 3);

        // Call 4: push byte 3 (completion)
        let chunk3 = decoder.push_bytes(&bytes[3..4]);
        assert_eq!(
            chunk3.as_deref(),
            Some(emoji),
            "Call 4 for {name} must return exactly {emoji}"
        );
        assert_eq!(
            decoder.pending_len(),
            0,
            "Pending buffer must be 0 after full 4-byte completion"
        );
        assert!(decoder.is_empty());

        // Verify zero replacement characters emitted throughout
        assert_ne!(
            chunk3.as_deref(),
            Some("\u{FFFD}"),
            "Emoji {name} must never produce replacement character \u{FFFD}"
        );
    }
}

#[test]
fn test_adversarial_utf8_emoji_arbitrary_partitions() {
    let emojis = ["🦀", "🚀", "🧪", "🧠"];
    // All 8 possible non-empty ordered integer compositions of 4:
    let compositions: &[&[usize]] = &[
        &[1, 1, 1, 1],
        &[1, 1, 2],
        &[1, 2, 1],
        &[2, 1, 1],
        &[2, 2],
        &[1, 3],
        &[3, 1],
        &[4],
    ];

    for &emoji in &emojis {
        let bytes = emoji.as_bytes();
        for &comp in compositions {
            let mut decoder = IncrementalUtf8Decoder::new();
            let mut assembled = String::new();
            let mut offset = 0;

            for (i, &size) in comp.iter().enumerate() {
                let slice = &bytes[offset..offset + size];
                offset += size;

                if let Some(chunk) = decoder.push_bytes(slice) {
                    assert!(
                        !chunk.contains('\u{FFFD}'),
                        "Emitted chunk must not contain replacement char \u{FFFD} for partition {comp:?}"
                    );
                    assembled.push_str(&chunk);
                }

                if i < comp.len() - 1 {
                    assert!(
                        assembled.is_empty(),
                        "Intermediate chunk in partition {comp:?} must not emit completed char early"
                    );
                }
            }

            assert_eq!(
                assembled, emoji,
                "Assembled output for partition {comp:?} must match {emoji}"
            );
            assert!(
                decoder.is_empty(),
                "Decoder buffer must be empty after full composition"
            );
        }
    }
}

#[test]
fn test_adversarial_utf8_cjk_3byte_splits() {
    let cjk_chars = [
        ("語", "Japanese/Chinese word", [0xE8u8, 0xAA, 0x9E]),
        ("漢", "Han character", [0xE6, 0xBC, 0xA2]),
        ("字", "Glyph character", [0xE5, 0xAD, 0x97]),
        ("中", "Middle/Center", [0xE4, 0xB8, 0xAD]),
        ("文", "Script/Culture", [0xE6, 0x96, 0x87]),
    ];

    for &(cjk_str, desc, expected_bytes) in &cjk_chars {
        assert_eq!(cjk_str.as_bytes(), &expected_bytes);

        // Composition 1: [1, 1, 1] byte-by-byte
        {
            let mut decoder = IncrementalUtf8Decoder::new();
            assert_eq!(
                decoder.push_bytes(&expected_bytes[0..1]),
                None,
                "{desc} byte 1 must return None"
            );
            assert_eq!(decoder.pending_len(), 1);

            assert_eq!(
                decoder.push_bytes(&expected_bytes[1..2]),
                None,
                "{desc} byte 2 must return None"
            );
            assert_eq!(decoder.pending_len(), 2);

            let res = decoder.push_bytes(&expected_bytes[2..3]);
            assert_eq!(
                res.as_deref(),
                Some(cjk_str),
                "{desc} byte 3 must complete {cjk_str}"
            );
            assert!(decoder.is_empty());
        }

        // Composition 2: [1, 2]
        {
            let mut decoder = IncrementalUtf8Decoder::new();
            assert_eq!(decoder.push_bytes(&expected_bytes[0..1]), None);
            assert_eq!(
                decoder.push_bytes(&expected_bytes[1..3]).as_deref(),
                Some(cjk_str)
            );
            assert!(decoder.is_empty());
        }

        // Composition 3: [2, 1]
        {
            let mut decoder = IncrementalUtf8Decoder::new();
            assert_eq!(decoder.push_bytes(&expected_bytes[0..2]), None);
            assert_eq!(
                decoder.push_bytes(&expected_bytes[2..3]).as_deref(),
                Some(cjk_str)
            );
            assert!(decoder.is_empty());
        }
    }
}

#[test]
fn test_adversarial_utf8_accented_2byte_splits() {
    let accented = [
        ("é", [0xC3u8, 0xA9]),
        ("ü", [0xC3, 0xBC]),
        ("ñ", [0xC3, 0xB1]),
        ("ç", [0xC3, 0xA7]),
        ("ö", [0xC3, 0xB6]),
        ("α", [0xCE, 0xB1]),
        ("β", [0xCE, 0xB2]),
        ("λ", [0xCE, 0xBB]),
    ];

    for &(ch, expected_bytes) in &accented {
        assert_eq!(ch.as_bytes(), &expected_bytes);
        let mut decoder = IncrementalUtf8Decoder::new();

        // Push byte 0
        let chunk0 = decoder.push_bytes(&expected_bytes[0..1]);
        assert_eq!(chunk0, None, "Accented byte 0 must return None");
        assert_eq!(decoder.pending_len(), 1);

        // Push byte 1
        let chunk1 = decoder.push_bytes(&expected_bytes[1..2]);
        assert_eq!(
            chunk1.as_deref(),
            Some(ch),
            "Accented byte 1 must complete character {ch}"
        );
        assert!(decoder.is_empty());
    }
}

#[test]
fn test_adversarial_utf8_mixed_stream_stress() {
    let text = "Hello, 世界! 🦀 Rust 🚀 is fun — 100% café & 🧪.";
    let bytes = text.as_bytes();

    // Adversarially split into pseudo-random chunks of varying sizes [1, 2, 3, 1, 4, 1, ...]
    let chunk_sizes = [1, 2, 3, 1, 4, 1, 2, 1, 3, 5, 2, 1, 1, 2, 4, 1, 3, 2];
    let mut decoder = IncrementalUtf8Decoder::new();
    let mut reconstructed = String::new();
    let mut offset = 0;
    let mut step = 0;

    while offset < bytes.len() {
        let size = chunk_sizes[step % chunk_sizes.len()].min(bytes.len() - offset);
        let slice = &bytes[offset..offset + size];
        offset += size;
        step += 1;

        if let Some(chunk) = decoder.push_bytes(slice) {
            assert!(
                !chunk.contains('\u{FFFD}'),
                "Emitted chunk '{chunk}' must not contain replacement characters during valid stream"
            );
            reconstructed.push_str(&chunk);
        }
    }

    if let Some(flushed) = decoder.flush() {
        reconstructed.push_str(&flushed);
    }

    assert_eq!(
        reconstructed, text,
        "Reconstructed text must match original source text 100% verbatim"
    );
    assert!(
        decoder.is_empty(),
        "Decoder buffer must be empty after stream completion"
    );
}

#[test]
fn test_adversarial_utf8_invalid_sequence_recovery() {
    let mut decoder = IncrementalUtf8Decoder::new();

    // 1. Standalone invalid byte 0xFF
    let out = decoder.push_bytes(&[0xFF]);
    assert_eq!(
        out.as_deref(),
        Some("\u{FFFD}"),
        "Invalid byte 0xFF must emit replacement character"
    );
    assert!(
        decoder.is_empty(),
        "Pending buffer must be cleared after consuming invalid byte"
    );

    // Feed valid sequence immediately following 0xFF
    let out = decoder.push_bytes(b"hello ");
    assert_eq!(
        out.as_deref(),
        Some("hello "),
        "Decoder must cleanly recover and emit valid ASCII"
    );
    assert!(decoder.is_empty());

    // 2. Orphaned continuation byte 0x80
    let out = decoder.push_bytes(&[0x80]);
    assert_eq!(
        out.as_deref(),
        Some("\u{FFFD}"),
        "Lone continuation byte 0x80 must emit replacement character"
    );
    assert!(decoder.is_empty());

    // Feed valid 4-byte emoji byte-by-byte
    let crab = "🦀".as_bytes();
    assert_eq!(decoder.push_bytes(&crab[0..1]), None);
    assert_eq!(decoder.push_bytes(&crab[1..2]), None);
    assert_eq!(decoder.push_bytes(&crab[2..3]), None);
    assert_eq!(decoder.push_bytes(&crab[3..4]), Some("🦀".to_string()));
    assert!(decoder.is_empty());

    // 3. Incomplete sequence truncated by non-continuation byte
    // 0xF0 0x9F (start of 4-byte emoji) followed by ASCII '!' (0x21)
    assert_eq!(decoder.push_bytes(&[0xF0, 0x9F]), None);
    assert_eq!(decoder.pending_len(), 2);

    let out = decoder.push_bytes(b"!");
    // The invalid 2-byte prefix is drained as replacement char
    assert_eq!(
        out.as_deref(),
        Some("\u{FFFD}"),
        "Truncated 4-byte prefix followed by ASCII must emit replacement char"
    );

    // Flush or next push drains the remaining valid byte
    let flushed = decoder.flush();
    assert_eq!(
        flushed.as_deref(),
        Some("!"),
        "Remaining valid ASCII byte must be cleanly flushed"
    );
    assert!(decoder.is_empty());
}

#[test]
fn test_adversarial_utf8_trailing_bytes_flush() {
    // Test 1: Incomplete 2-byte accent
    let mut decoder = IncrementalUtf8Decoder::new();
    assert_eq!(decoder.push_bytes(&[0xC3]), None);
    assert_eq!(decoder.pending_len(), 1);
    assert_eq!(decoder.flush(), Some("\u{FFFD}".to_string()));
    assert!(decoder.is_empty());
    assert_eq!(decoder.flush(), None);

    // Test 2: Incomplete 3-byte CJK
    assert_eq!(decoder.push_bytes(&[0xE8, 0xAA]), None);
    assert_eq!(decoder.pending_len(), 2);
    assert_eq!(decoder.flush(), Some("\u{FFFD}".to_string()));
    assert!(decoder.is_empty());

    // Test 3: Incomplete 4-byte emoji
    assert_eq!(decoder.push_bytes(&[0xF0, 0x9F, 0xA6]), None);
    assert_eq!(decoder.pending_len(), 3);
    assert_eq!(decoder.flush(), Some("\u{FFFD}".to_string()));
    assert!(decoder.is_empty());

    // Clean resumption after flush
    assert_eq!(decoder.push_bytes(b"Clean"), Some("Clean".to_string()));
    assert!(decoder.is_empty());
}

// ============================================================================
// PART 2: Stop-Token Suppression & Stream Lifecycle Invariants
// ============================================================================

fn find_immediate_stop_seed(bundle: &Bundle, prompt: &str, target: u32) -> Option<(u64, usize)> {
    let formatted = format!(
        "{}{}{}{}",
        RoleToken::USER_STR,
        prompt,
        RoleToken::TURN_END_STR,
        RoleToken::ASSISTANT_STR
    );
    let tokens = bundle.tokenizer().encode(&formatted);
    let prompt_len = tokens.len();
    let mut state = bundle.model().new_conversational_session();
    state.seal_persistent();
    let mut last_step = None;
    for &t in &tokens {
        last_step = Some(
            bundle
                .model()
                .step_conversational(
                    &mut state,
                    t,
                    uor_r4_integer::SlotTarget::Dialogue,
                    uor_r4_integer::ReadMode::Enabled,
                )
                .ok()?,
        );
    }
    let probs = &last_step?.probabilities;
    let policy = SamplePolicy::Categorical { top_k: 4096 };
    for seed in 1..200_000u64 {
        let mut sampler = uor_r4_integer::Sampler::new(seed);
        if let Ok(idx) = sampler.select(probs, policy) {
            if idx as u32 == target {
                return Some((seed, prompt_len));
            }
        }
    }
    None
}

#[test]
fn test_adversarial_stop_token_turn_end_suppression_and_state() {
    let bundle = Bundle::synthetic_for_test();
    let prompt = "User turn 1";
    let (seed, prompt_len) = find_immediate_stop_seed(&bundle, prompt, RoleToken::TurnEnd.id())
        .expect("must find a seed that produces TurnEnd on step 0");

    let mut session = ChatSession::new(&bundle, None, seed).expect("new session");
    session.set_policy(SamplePolicy::Categorical { top_k: 4096 });

    let initial_telemetry = session.telemetry();
    assert_eq!(initial_telemetry.current_turn_id, 0);

    let stop_tokens = [RoleToken::TurnEnd.id(), RoleToken::EOS_ID];

    // Ingest prompt and generate stream
    let mut stream = session
        .generate_stream(prompt, 50, &stop_tokens)
        .expect("generate stream");

    // Pull all items from stream
    let mut emitted_chunks = Vec::new();
    for chunk in stream.by_ref() {
        emitted_chunks.push(chunk);
    }

    // 1. VERIFY: Token 6 (<|turn_end|>) is NEVER yielded to consumer string stream
    let full_emitted_text = emitted_chunks.join("");
    assert!(
        !full_emitted_text.contains("<|turn_end|>"),
        "Consumer string stream must NEVER yield stop token <|turn_end|>"
    );
    assert!(
        !full_emitted_text.contains("<|eos|>"),
        "Consumer string stream must NEVER yield stop token <|eos|>"
    );

    // 2. VERIFY: Stream stop metadata
    assert!(
        stream.is_stopped(),
        "Stream must be marked stopped upon encountering <|turn_end|>"
    );
    assert_eq!(
        stream.stop_reason(),
        Some(StreamStopReason::TurnEnd { token_id: 6 }),
        "Stop reason must identify TurnEnd with token_id 6"
    );
    assert_eq!(
        stream.tokens_generated(),
        0,
        "Stop token on token 0 must not count as generated user token"
    );
    assert!(
        stream.generated_tokens().is_empty(),
        "Generated tokens slice must be empty when stopped on token 0"
    );

    // 3. VERIFY: Session state internally appended stop token 6 into dialogue memory
    let post_telemetry = session.telemetry();
    assert_eq!(
        post_telemetry.dialogue_tokens_seen,
        initial_telemetry.dialogue_tokens_seen + (prompt_len as u64) + 1,
        "Dialogue tokens seen must include the prompt tokens plus the stop token"
    );

    // Verify last slot token in dialogue ring buffer is token 6
    let cursor = session.state().dialogue_cursor;
    let last_slot_idx = if cursor == 0 {
        session.state().dialogue_capacity - 1
    } else {
        cursor - 1
    };
    assert_eq!(
        session.state().dialogue_tokens[last_slot_idx],
        RoleToken::TURN_END_ID,
        "Session dialogue memory ring buffer must record stop token 6 at current cursor"
    );

    // 4. VERIFY: Session is ready for the next user turn
    let turn2_result = session.ingest_user_turn("User turn 2");
    assert!(
        turn2_result.is_ok(),
        "Session must cleanly accept the next user turn"
    );
    assert_eq!(
        session.telemetry().current_turn_id,
        2,
        "Current turn ID must advance to turn 2"
    );
}

#[test]
fn test_adversarial_stop_token_eos_suppression_and_state() {
    let bundle = Bundle::synthetic_for_test();
    let prompt = "User turn 1";
    let (seed, prompt_len) = find_immediate_stop_seed(&bundle, prompt, RoleToken::EOS_ID)
        .expect("must find a seed that produces EOS on step 0");

    let mut session = ChatSession::new(&bundle, None, seed).expect("new session");
    session.set_policy(SamplePolicy::Categorical { top_k: 4096 });

    let initial_telemetry = session.telemetry();
    let stop_tokens = [RoleToken::TurnEnd.id(), RoleToken::EOS_ID];

    let mut stream = session
        .generate_stream(prompt, 50, &stop_tokens)
        .expect("generate stream");

    let mut emitted_chunks = Vec::new();
    for chunk in stream.by_ref() {
        emitted_chunks.push(chunk);
    }

    let full_emitted_text = emitted_chunks.join("");
    assert!(
        !full_emitted_text.contains("<|eos|>"),
        "Consumer stream must NEVER yield <|eos|>"
    );
    assert!(
        !full_emitted_text.contains("<|turn_end|>"),
        "Consumer stream must NEVER yield <|turn_end|>"
    );

    assert!(stream.is_stopped());
    assert_eq!(
        stream.stop_reason(),
        Some(StreamStopReason::Eos { token_id: 1 }),
        "Stop reason must identify Eos with token_id 1"
    );
    assert_eq!(stream.tokens_generated(), 0);

    // Verify session state internally recorded EOS token 1
    let post_telemetry = session.telemetry();
    assert_eq!(
        post_telemetry.dialogue_tokens_seen,
        initial_telemetry.dialogue_tokens_seen + (prompt_len as u64) + 1,
        "Session must have stepped the EOS token into dialogue memory"
    );

    let cursor = session.state().dialogue_cursor;
    let last_slot_idx = if cursor == 0 {
        session.state().dialogue_capacity - 1
    } else {
        cursor - 1
    };
    assert_eq!(
        session.state().dialogue_tokens[last_slot_idx],
        RoleToken::EOS_ID,
        "Dialogue memory must record token 1 (<|eos|>)"
    );

    // Verify ready state for subsequent turn
    let next_turn = session.ingest_user_turn("Post-EOS message");
    assert!(next_turn.is_ok());
    assert_eq!(session.telemetry().current_turn_id, 2);
}

#[test]
fn test_adversarial_delayed_stop_token_suppression() {
    let bundle = Bundle::synthetic_for_test();
    // Seed 1300 generates token 4 ("<|user|>") on step 0, and then token 6 (<|turn_end|>) on step 1
    let seed = 1300;
    let mut session = ChatSession::new(&bundle, None, seed).expect("new session");
    session.set_policy(SamplePolicy::Categorical { top_k: 4096 });

    let initial_telemetry = session.telemetry();
    let stop_tokens = [RoleToken::TurnEnd.id(), RoleToken::EOS_ID];

    let mut stream = session
        .generate_stream("User turn 1", 50, &stop_tokens)
        .expect("generate stream");

    let mut emitted_chunks = Vec::new();
    for chunk in stream.by_ref() {
        emitted_chunks.push(chunk);
    }

    // 1. Text token was emitted
    assert_eq!(emitted_chunks, vec!["<|user|>".to_string()]);
    // 2. Stop token <|turn_end|> was suppressed
    let full_text = emitted_chunks.join("");
    assert!(!full_text.contains("<|turn_end|>"));

    assert!(stream.is_stopped());
    assert_eq!(
        stream.stop_reason(),
        Some(StreamStopReason::TurnEnd { token_id: 6 })
    );
    assert_eq!(stream.tokens_generated(), 1);
    assert_eq!(stream.generated_tokens(), &[4]);

    // 3. Dialogue memory contains prompt tokens, text token AND stop token
    let prompt_len = bundle
        .tokenizer()
        .encode("<|user|>User turn 1<|turn_end|><|assistant|>")
        .len() as u64;
    let post_telemetry = session.telemetry();
    assert_eq!(
        post_telemetry.dialogue_tokens_seen,
        initial_telemetry.dialogue_tokens_seen + prompt_len + 1 + 1 // prompt + 1 text + 1 stop
    );

    // 4. Ready for next turn
    assert!(session.ingest_user_turn("Next turn").is_ok());
    assert_eq!(session.telemetry().current_turn_id, 2);
}

#[test]
fn test_adversarial_immediate_stop_on_token_0() {
    let bundle = Bundle::synthetic_for_test();
    let mut session = ChatSession::new(&bundle, None, 42).expect("new session");
    session.set_policy(SamplePolicy::Greedy);

    // In greedy mode on synthetic model, token 4 (<|user|>) is predicted on token 0
    // We register token 4 as a custom stop token to test immediate stop on token 0
    let stop_tokens = [4u32, RoleToken::TurnEnd.id(), RoleToken::EOS_ID];

    let mut stream = session
        .generate_stream("Stop immediately", 100, &stop_tokens)
        .expect("generate stream");

    // The very first call to next() must immediately return None
    let first_chunk = stream.next();
    assert_eq!(
        first_chunk, None,
        "Stream must immediately terminate and return None on token 0 stop"
    );
    assert!(
        stream.is_stopped(),
        "Stream must be marked stopped on token 0"
    );
    assert_eq!(
        stream.tokens_generated(),
        0,
        "Tokens generated count must be strictly 0"
    );
    assert_eq!(
        stream.stop_reason(),
        Some(StreamStopReason::CustomStop { token_id: 4 }),
        "Stop reason must identify CustomStop with token 4"
    );

    // Subsequent calls to next() must also return None
    assert_eq!(stream.next(), None);
    assert_eq!(stream.next(), None);

    // Verify dialogue memory has token 4 appended
    let cursor = session.state().dialogue_cursor;
    let last_slot_idx = if cursor == 0 {
        session.state().dialogue_capacity - 1
    } else {
        cursor - 1
    };
    assert_eq!(
        session.state().dialogue_tokens[last_slot_idx],
        4,
        "Stop token 4 must be stepped into dialogue ring buffer"
    );

    // Verify session is ready for next turn
    let next_turn = session.ingest_user_turn("Followup prompt");
    assert!(next_turn.is_ok());
}

#[test]
fn test_adversarial_stream_cycle_detection_suppression() {
    let bundle = Bundle::synthetic_for_test();
    let mut session = ChatSession::new(&bundle, None, 42).expect("new session");
    session.set_policy(SamplePolicy::Greedy);

    // In greedy mode without token 4 in stop_tokens, synthetic model repeats token 4
    let stop_tokens = [RoleToken::TurnEnd.id(), RoleToken::EOS_ID];

    let mut stream = session
        .generate_stream("Trigger cycle", 20, &stop_tokens)
        .expect("generate stream");

    let _chunks: Vec<_> = stream.by_ref().collect();

    assert!(stream.is_stopped());
    assert_eq!(
        stream.stop_reason(),
        Some(StreamStopReason::CycleDetected { period: 1 }),
        "Repetitive token sequence must trigger short-cycle detection"
    );

    // Cycle detection automatically steps TurnEnd into dialogue memory
    let cursor = session.state().dialogue_cursor;
    let last_slot_idx = if cursor == 0 {
        session.state().dialogue_capacity - 1
    } else {
        cursor - 1
    };
    assert_eq!(
        session.state().dialogue_tokens[last_slot_idx],
        RoleToken::TURN_END_ID,
        "Cycle detection must step TurnEnd into dialogue memory"
    );

    // Verify turn ready
    assert!(session.ingest_user_turn("Next turn").is_ok());
}
