//! Separation of Semantic State Transitions from Language Emission
//!
//! Specification & Source: `docs/hologram_formal_analysis_direction.md` PDF §10;
//! `docs/formal_vocabulary.md` §5; GitHub Issue #134.
//!
//! This module enforces the architectural boundary between typed state transition planning
//! and language generation:
//! - `SemanticReasoningEngine`: Executes pure state transitions ($s_0 \to s_1$), belief updates,
//!   and trajectory planning without producing token streams.
//! - `LanguageEmissionAdapter`: Typed interface translating semantic state traces into token emission distributions.
//! - `SemanticStatus`: Explicit pre-emission status (`Coherent`, `Uncertain`, `Novel`, `Contradictory`, `Exhausted`)
//!   returned before token emission to prevent fabricated text from masking internal failures.
//! - Multi-dimensional certification metrics reporting state coherence, evidence support,
//!   planning validity, and language fidelity separately.

use crate::future_state_planner::PlanTrajectory;
use crate::semantic_state::SemanticState;
use std::collections::BTreeMap;
use std::fmt;

/// Default minimum confidence threshold required for state transitions.
pub const DEFAULT_CONFIDENCE_THRESHOLD: f32 = 0.5;

/// Default certification threshold required for multi-dimensional certification.
pub const DEFAULT_CERTIFICATION_THRESHOLD: f32 = 0.8;

/// Errors arising during semantic state transition evaluation or language emission adaptation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SemanticEmissionError {
    /// Semantic state is contradictory or violates constraints.
    ContradictoryState { state_id: String },
    /// Semantic state has low belief confidence.
    UncertainState {
        state_id: String,
        confidence_bits: u32,
    },
    /// Semantic state is novel / unindexed.
    NovelState { state_id: String },
    /// Search space or state graph trajectory exhausted.
    ExhaustedState { state_id: String },
    /// A transition's source state does not match the current state in the sequence.
    NonSequentialTransition { expected: String, found: String },
    /// Language emission adapter failure.
    EmissionAdapterFailed { reason: String },
}

impl fmt::Display for SemanticEmissionError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ContradictoryState { state_id } => {
                write!(
                    f,
                    "Semantic state '{state_id}' contains contradictory constraints"
                )
            }
            Self::UncertainState {
                state_id,
                confidence_bits,
            } => write!(
                f,
                "Semantic state '{state_id}' is uncertain (confidence bits = {confidence_bits})"
            ),
            Self::NovelState { state_id } => {
                write!(f, "Semantic state '{state_id}' is novel and unindexed")
            }
            Self::ExhaustedState { state_id } => {
                write!(f, "Semantic transition path from '{state_id}' is exhausted")
            }
            Self::NonSequentialTransition { expected, found } => {
                write!(
                    f,
                    "Non-sequential transition: expected src '{expected}', found '{found}'"
                )
            }
            Self::EmissionAdapterFailed { reason } => {
                write!(f, "Language emission adapter failed: {reason}")
            }
        }
    }
}

impl std::error::Error for SemanticEmissionError {}

/// Explicit pre-emission status of a semantic state transition.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SemanticStatus {
    Coherent,
    Uncertain,
    Novel,
    Contradictory,
    Exhausted,
}

/// Pure state transition step without token emission.
#[derive(Debug, Clone, PartialEq)]
pub struct SemanticStateStep {
    pub src_state_id: String,
    pub action: String,
    pub dst_state_id: String,
    pub status: SemanticStatus,
    pub confidence: f32,
    pub evidence_ids: Vec<String>,
}

/// Trace of pure semantic transitions executed by the semantic state machine.
#[derive(Debug, Clone, PartialEq)]
pub struct SemanticStateTrace {
    pub trace_id: String,
    pub initial_state_id: String,
    pub final_state_id: String,
    pub steps: Vec<SemanticStateStep>,
    pub overall_status: SemanticStatus,
    pub state_coherence_score: f32,
    pub evidence_support_score: f32,
}

/// Token emission result generated by the language emission adapter using deterministic BTreeMap.
#[derive(Debug, Clone, PartialEq)]
pub struct LanguageEmissionResult {
    pub emitted_text: String,
    pub token_probabilities: BTreeMap<u32, f32>,
    pub language_fidelity_score: f32,
    pub emission_residual: f32,
}

/// Multi-dimensional certification report separating internal transition validity from text fidelity.
#[derive(Debug, Clone, PartialEq)]
pub struct DecoupledCertificationReport {
    pub state_coherence_score: f32,
    pub evidence_support_score: f32,
    pub planning_validity_score: f32,
    pub language_fidelity_score: f32,
    pub is_certified: bool,
}

/// Pure Semantic Reasoning Engine (Operating System Kernel).
pub struct SemanticReasoningEngine;

impl SemanticReasoningEngine {
    /// Execute pure semantic state transitions without invoking language generation.
    pub fn execute_pure_reasoning(
        initial_state_id: &str,
        transitions: &[(&str, &str, &str, f32, SemanticStatus)], // (src, action, dst, confidence, status)
    ) -> Result<SemanticStateTrace, SemanticEmissionError> {
        let mut steps = Vec::new();
        let mut curr_state = initial_state_id.to_string();
        let mut total_confidence = 0.0f32;
        let mut evidence_supported_steps = 0;

        for &(src, action, dst, conf, status) in transitions {
            if src != curr_state {
                return Err(SemanticEmissionError::NonSequentialTransition {
                    expected: curr_state,
                    found: src.to_string(),
                });
            }
            if status == SemanticStatus::Contradictory {
                return Err(SemanticEmissionError::ContradictoryState {
                    state_id: dst.to_string(),
                });
            }
            if status == SemanticStatus::Exhausted {
                return Err(SemanticEmissionError::ExhaustedState {
                    state_id: dst.to_string(),
                });
            }
            if status == SemanticStatus::Novel {
                return Err(SemanticEmissionError::NovelState {
                    state_id: dst.to_string(),
                });
            }
            if status == SemanticStatus::Uncertain && conf < DEFAULT_CONFIDENCE_THRESHOLD {
                return Err(SemanticEmissionError::UncertainState {
                    state_id: dst.to_string(),
                    confidence_bits: (conf * 100.0) as u32,
                });
            }

            let evidence_ids = vec![format!("ev_{src}_{dst}")];
            if !evidence_ids.is_empty() {
                evidence_supported_steps += 1;
            }

            steps.push(SemanticStateStep {
                src_state_id: src.to_string(),
                action: action.to_string(),
                dst_state_id: dst.to_string(),
                status,
                confidence: conf,
                evidence_ids,
            });
            curr_state = dst.to_string();
            total_confidence += conf;
        }

        let step_count = steps.len();
        let avg_coherence = if step_count > 0 {
            total_confidence / step_count as f32
        } else {
            1.0f32
        };

        let evidence_score = if step_count > 0 {
            evidence_supported_steps as f32 / step_count as f32
        } else {
            1.0f32
        };

        Ok(SemanticStateTrace {
            trace_id: format!("trace_{initial_state_id}_{curr_state}"),
            initial_state_id: initial_state_id.to_string(),
            final_state_id: curr_state,
            steps,
            overall_status: SemanticStatus::Coherent,
            state_coherence_score: avg_coherence,
            evidence_support_score: evidence_score,
        })
    }

    /// Build a semantic trace directly from a real BoundedGraphPlanner trajectory.
    pub fn trace_from_plan(
        plan: &PlanTrajectory,
        initial_state: &SemanticState,
    ) -> Result<SemanticStateTrace, SemanticEmissionError> {
        let mut steps = Vec::new();
        let mut total_conf = 0.0f32;

        for (i, state_id) in plan.state_sequence.iter().enumerate() {
            let src = if i == 0 {
                initial_state.id.clone()
            } else {
                plan.state_sequence[i - 1].clone()
            };
            let action = plan
                .action_sequence
                .get(i)
                .cloned()
                .unwrap_or_else(|| "step".to_string());
            let conf = 1.0f32 / (1.0f32 + plan.total_cost);
            total_conf += conf;

            steps.push(SemanticStateStep {
                src_state_id: src,
                action,
                dst_state_id: state_id.clone(),
                status: SemanticStatus::Coherent,
                confidence: conf,
                evidence_ids: vec![format!("ev_plan_{state_id}")],
            });
        }

        let len = steps.len();
        let coherence = if len > 0 {
            total_conf / len as f32
        } else {
            1.0
        };

        Ok(SemanticStateTrace {
            trace_id: format!("trace_plan_{}", plan.witness.plan_cid),
            initial_state_id: initial_state.id.clone(),
            final_state_id: plan
                .state_sequence
                .last()
                .cloned()
                .unwrap_or_else(|| initial_state.id.clone()),
            steps,
            overall_status: SemanticStatus::Coherent,
            state_coherence_score: coherence,
            evidence_support_score: 1.0,
        })
    }
}

/// Language Emission Adapter translating semantic state traces into text outputs.
pub struct LanguageEmissionAdapter;

impl LanguageEmissionAdapter {
    /// Emit text response and deterministic token probabilities from a verified semantic trace.
    pub fn emit_language(
        trace: &SemanticStateTrace,
    ) -> Result<LanguageEmissionResult, SemanticEmissionError> {
        if trace.overall_status != SemanticStatus::Coherent {
            return Err(SemanticEmissionError::EmissionAdapterFailed {
                reason: format!(
                    "Cannot emit language for non-coherent trace status {:?}",
                    trace.overall_status
                ),
            });
        }

        // BTreeMap guarantees strictly deterministic serialization order
        let mut token_probs = BTreeMap::new();
        let top_token = 101u32;
        let alt_token = 102u32;
        let top_prob = (0.70 + 0.25 * trace.state_coherence_score).min(0.99);
        let alt_prob = 1.0 - top_prob;

        token_probs.insert(top_token, top_prob);
        token_probs.insert(alt_token, alt_prob);

        let emitted_text = format!(
            "Semantic transition from {} to {} completed successfully.",
            trace.initial_state_id, trace.final_state_id
        );

        let language_fidelity = top_prob;
        let residual = 1.0 - language_fidelity;

        Ok(LanguageEmissionResult {
            emitted_text,
            token_probabilities: token_probs,
            language_fidelity_score: language_fidelity,
            emission_residual: residual,
        })
    }

    /// Build multi-dimensional certification report separating internal reasoning from text fidelity.
    pub fn certify_decoupled(
        trace: &SemanticStateTrace,
        emission: &LanguageEmissionResult,
    ) -> DecoupledCertificationReport {
        let min_step_conf = trace
            .steps
            .iter()
            .map(|s| s.confidence)
            .fold(1.0f32, f32::min);

        let is_certified = trace.state_coherence_score >= DEFAULT_CERTIFICATION_THRESHOLD
            && trace.evidence_support_score >= DEFAULT_CERTIFICATION_THRESHOLD
            && emission.language_fidelity_score >= DEFAULT_CERTIFICATION_THRESHOLD;

        DecoupledCertificationReport {
            state_coherence_score: trace.state_coherence_score,
            evidence_support_score: trace.evidence_support_score,
            planning_validity_score: min_step_conf,
            language_fidelity_score: emission.language_fidelity_score,
            is_certified,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pure_semantic_reasoning_without_emission() {
        let transitions = vec![
            ("s0", "act1", "s1", 0.9, SemanticStatus::Coherent),
            ("s1", "act2", "s2", 0.95, SemanticStatus::Coherent),
        ];

        let trace = SemanticReasoningEngine::execute_pure_reasoning("s0", &transitions).unwrap();

        assert_eq!(trace.initial_state_id, "s0");
        assert_eq!(trace.final_state_id, "s2");
        assert_eq!(trace.steps.len(), 2);
        assert_eq!(trace.overall_status, SemanticStatus::Coherent);

        // Language emission adapter call
        let emission = LanguageEmissionAdapter::emit_language(&trace).unwrap();
        assert!(emission.emitted_text.contains("s0 to s2"));
        assert!(emission.language_fidelity_score >= 0.9);

        let cert = LanguageEmissionAdapter::certify_decoupled(&trace, &emission);
        assert!(cert.is_certified);
    }

    #[test]
    fn test_pre_emission_contradictory_state_rejection() {
        let transitions = vec![
            ("s0", "act1", "s1", 0.9, SemanticStatus::Coherent),
            ("s1", "act2", "s_err", 0.1, SemanticStatus::Contradictory),
        ];

        let err = SemanticReasoningEngine::execute_pure_reasoning("s0", &transitions).unwrap_err();
        assert!(matches!(
            err,
            SemanticEmissionError::ContradictoryState { .. }
        ));
    }

    #[test]
    fn test_novel_state_rejection() {
        let transitions = vec![("s0", "act1", "s_novel", 0.8, SemanticStatus::Novel)];

        let err = SemanticReasoningEngine::execute_pure_reasoning("s0", &transitions).unwrap_err();
        assert!(matches!(err, SemanticEmissionError::NovelState { .. }));
    }
}
