// Build script: turn the uor-addr-wasm core module at
// ../../target/wasm32-unknown-unknown/release/uor_addr_wasm.wasm into a
// single self-contained, environment-agnostic ES module under ./dist/.
//
// Why wasm32-unknown-unknown and not wasm32-wasip2: the wasip2 target
// links std's WASI runtime (cli/io/exit/environment) into the
// component even though this pure-compute library never calls it. jco
// can only satisfy those imports with `@bytecodealliance/preview2-shim`,
// which is Node-only — so a wasip2-derived package is unusable in the
// browser, Deno, Bun, Cloudflare Workers, and any bundler that resolves
// `node:` specifiers statically. Building for wasm32-unknown-unknown
// produces a core module with no WASI dependency; `jco new`
// componentizes it into a zero-import component, and base64-inlining the
// core wasm (`--base64-cutoff`) plus `--no-nodejs-compat` yields a lone
// uor-addr.js with no `node:` imports, no fetch, and no separate .wasm
// asset — runnable anywhere a WebAssembly engine exists.
//
// In CI / publish flow, the core module is produced by the `publish-npm`
// job in .github/workflows/release.yml. Locally, run:
//   cargo build -p uor-addr-wasm --target wasm32-unknown-unknown --release

import { execSync } from "node:child_process";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..", "..", "..");
const coreModulePath = join(
  root, "target", "wasm32-unknown-unknown", "release", "uor_addr_wasm.wasm",
);
const distDir = resolve(__dirname, "..", "dist");
const componentPath = join(distDir, "uor-addr.component.wasm");

// Inline core wasm of any plausible size as base64 so the published
// package is a single self-contained module (no fetch, no fs, no
// sidecar .wasm). 256 MiB is well above the ~1.5 MiB artifact.
const BASE64_CUTOFF = 256 * 1024 * 1024;

if (!existsSync(coreModulePath)) {
  console.error(`error: expected core wasm module at ${coreModulePath}`);
  console.error("       run: cargo build -p uor-addr-wasm --target wasm32-unknown-unknown --release");
  process.exit(1);
}

// Start from a clean dist/ so stale sidecar artifacts (e.g. a previous
// build's uor-addr.core.wasm) never ship.
rmSync(distDir, { recursive: true, force: true });
mkdirSync(distDir, { recursive: true });

const jco = resolve(__dirname, "..");

// 1. Componentize: wrap the bare core module into a Component Model
//    component using the WIT embedded by wit-bindgen. No WASI adapter is
//    needed because the module imports nothing from the host.
console.log("componentizing uor_addr_wasm.wasm via jco new…");
execSync(
  `npx jco new "${coreModulePath}" -o "${componentPath}"`,
  { stdio: "inherit", cwd: jco },
);

// 2. Transpile to a single universal ES module. --base64-cutoff inlines
//    the core wasm; --no-nodejs-compat strips the Node-only fs fallback.
console.log("transpiling component via jco…");
execSync(
  `npx jco transpile "${componentPath}" --out-dir "${distDir}" --name uor-addr ` +
    `--no-typescript --no-nodejs-compat --minify --base64-cutoff ${BASE64_CUTOFF}`,
  { stdio: "inherit", cwd: jco },
);

// The intermediate component is not part of the published package.
rmSync(componentPath, { force: true });

// Generate a TypeScript ambient declaration matching the WIT exports
// (one *-address function per realization). jco's --no-typescript flag
// suppresses its own .d.ts emit so we ship a hand-written one that
// matches the public surface 1:1.
const dts = `// Generated by bindings/npm/scripts/build.mjs — do not edit by hand.
// Mirrors crates/uor-addr-wasm/wit/uor-addr.wit.

/** ASCII \`sha256:<64hex>\` κ-label — exactly 71 bytes. */
export type KappaLabel = string;

/** Failure modes from any realization's address function. */
export type AddressError =
  | "invalid-input"
  | "too-large"
  | "pipeline-failure";

/** Failure modes from \`Grounded.verify()\` — 1:1 with the WIT
 * \`verify-error\` variant. All five are defensive against substrate
 * corruption; unreachable for a \`Grounded\` minted through this
 * binding. */
export type VerifyError =
  | "empty-trace"
  | "out-of-order-event"
  | "zero-target"
  | "non-contiguous-steps"
  | "capacity-exceeded";

/** σ-axis selector for the composition entry points. Mirrors the WIT
 * \`hash-algorithm\` enum; \`sha3256\` is the SHA3-256 axis (the κ-label
 * prefix it produces is still \`sha3-256\`). */
export type HashAlgorithm =
  | "sha256"
  | "blake3"
  | "sha3256"
  | "keccak256"
  | "sha512";

/** Opaque foreign-managed witness handle to a Rust-side
 * \`Grounded<AddressLabel>\` value carrying the ψ-pipeline's emitted
 * derivation.
 *
 * TC-05 conformance: every Grounded produced by a
 * \`*AddressWithWitness\` call replays through \`verify()\` to a
 * κ-label byte-identical to the one \`kappaLabel()\` reports
 * (QS-05 replay equivalence — bit-identical round-trip).
 *
 * Lifetime: in-process state held by the Component Model runtime.
 * Cross-process attestation is not supported — for that, persist the
 * κ-label itself and re-mint at the verifier side. */
export interface Grounded {
  /** Return the 71-byte ASCII κ-label this Grounded carries. */
  kappaLabel(): KappaLabel;
  /** Return the 32-byte SHA-256 content fingerprint. */
  contentFingerprint(): Uint8Array;
  /** Replay the derivation through \`prism_verify::certify_from_trace\`
   * and return the recovered κ-label. SHA-256 is **not** re-invoked. */
  verify(): KappaLabel;
}

export interface Kappa {
  /** RFC 8259 JSON under RFC 8785 JCS + Unicode NFC. */
  jsonAddress(input: Uint8Array): KappaLabel;
  /** Rivest 1997 canonical S-expressions. */
  sexpAddress(input: Uint8Array): KappaLabel;
  /** W3C XML-C14N 1.1 (subset). */
  xmlAddress(input: Uint8Array): KappaLabel;
  /** ITU-T X.690 DER. */
  asn1Address(input: Uint8Array): KappaLabel;
  /** UOR-Framework Amendment 43 §2 ring elements. */
  ringAddress(input: Uint8Array): KappaLabel;
  /** CCMAS canonical AST. */
  codemoduleAddress(input: Uint8Array): KappaLabel;
  /** schema.org/Photograph admission + JSON canonicalization. */
  schemaPhotoAddress(input: Uint8Array): KappaLabel;
  /** schema.org/Article admission + JSON canonicalization. */
  schemaDocumentAddress(input: Uint8Array): KappaLabel;
  /** in-toto Statement v1 admission + JSON canonicalization. */
  schemaCodemoduleSignedAddress(input: Uint8Array): KappaLabel;
  /** GGUF v3 spec-canonical structural commitment (binds metadata + tensor weights). */
  ggufAddress(input: Uint8Array): KappaLabel;
  /** ONNX IR v13 protobuf-canonical commitment (topological node ordering + weight digests). */
  onnxAddress(input: Uint8Array): KappaLabel;

  // ── Witness-bearing variants (TC-05 cross-language replay) ──

  /** JSON realization; returns a verifiable [\`Grounded\`] witness. */
  jsonAddressWithWitness(input: Uint8Array): Grounded;
  /** S-expression realization; returns a verifiable witness. */
  sexpAddressWithWitness(input: Uint8Array): Grounded;
  /** XML realization; returns a verifiable witness. */
  xmlAddressWithWitness(input: Uint8Array): Grounded;
  /** ASN.1 realization; returns a verifiable witness. */
  asn1AddressWithWitness(input: Uint8Array): Grounded;
  /** Ring realization; returns a verifiable witness. */
  ringAddressWithWitness(input: Uint8Array): Grounded;
  /** Code-module realization; returns a verifiable witness. */
  codemoduleAddressWithWitness(input: Uint8Array): Grounded;
  /** schema.org/Photograph; returns a verifiable witness. */
  schemaPhotoAddressWithWitness(input: Uint8Array): Grounded;
  /** schema.org/Article; returns a verifiable witness. */
  schemaDocumentAddressWithWitness(input: Uint8Array): Grounded;
  /** in-toto Statement v1; returns a verifiable witness. */
  schemaCodemoduleSignedAddressWithWitness(input: Uint8Array): Grounded;
  /** GGUF v3 realization; returns a verifiable [\`Grounded\`] witness. */
  ggufAddressWithWitness(input: Uint8Array): Grounded;
  /** ONNX IR v13 realization; returns a verifiable [\`Grounded\`] witness. */
  onnxAddressWithWitness(input: Uint8Array): Grounded;

  // ── κ-label composition (ADR-061) ──
  // Operands are κ-labels under the σ-axis \`algo\`; the composed label
  // shares that axis. CS-G2 is a commutative binary product; the other
  // four are unary endomorphisms on the Atlas image inside E₈.

  /** CS-G2 commutative binary product of two κ-labels. */
  composeG2(left: KappaLabel, right: KappaLabel, algo: HashAlgorithm): KappaLabel;
  /** CS-G2 product; returns a verifiable [\`Grounded\`] witness. */
  composeG2WithWitness(left: KappaLabel, right: KappaLabel, algo: HashAlgorithm): Grounded;
  /** CS-F4 ± involution quotient of a κ-label. */
  composeF4(operand: KappaLabel, algo: HashAlgorithm): KappaLabel;
  /** CS-F4 quotient; returns a verifiable witness. */
  composeF4WithWitness(operand: KappaLabel, algo: HashAlgorithm): Grounded;
  /** CS-E6 degree-partition filtration of a κ-label. */
  composeE6(operand: KappaLabel, algo: HashAlgorithm): KappaLabel;
  /** CS-E6 filtration; returns a verifiable witness. */
  composeE6WithWitness(operand: KappaLabel, algo: HashAlgorithm): Grounded;
  /** CS-E7 S₄-orbit augmentation of a κ-label. */
  composeE7(operand: KappaLabel, algo: HashAlgorithm): KappaLabel;
  /** CS-E7 augmentation; returns a verifiable witness. */
  composeE7WithWitness(operand: KappaLabel, algo: HashAlgorithm): Grounded;
  /** CS-E8 direct embedding of a κ-label. */
  composeE8(operand: KappaLabel, algo: HashAlgorithm): KappaLabel;
  /** CS-E8 embedding; returns a verifiable witness. */
  composeE8WithWitness(operand: KappaLabel, algo: HashAlgorithm): Grounded;
}

export const kappa: Kappa;
`;
writeFileSync(join(distDir, "uor-addr.d.ts"), dts);

console.log(`wrote ${distDir}/uor-addr.d.ts`);
console.log("done.");
