#!/usr/bin/env python3
"""Generate the independent T5 raw-SentencePiece differential fixture.

The reference implementation is deliberately outside the Rust workspace:
`sentencepiece==0.2.2` loads the pinned `google-t5/t5-base` `spiece.model`
and supplies the expected token ids and decoded text.  The generated fixture
contains selected readable cases plus a compact digest over all 32,000
singleton decodes; it does not copy the source model or an enormous table into
the repository.

Reproduction (from the repository root):

    python3 -m venv /tmp/uor-r4-sp-reference
    /tmp/uor-r4-sp-reference/bin/pip install \
        sentencepiece==0.2.2 blake3==1.0.9 protobuf==6.33.6
    /tmp/uor-r4-sp-reference/bin/python \
        scripts/gen_t5_sentencepiece_fixture.py

The generator is intentionally scoped to raw `spiece.model` semantics.  It
does not load the sibling Hugging Face `tokenizer.json`, add its 100 sentinel
tokens, or apply its EOS-appending post-processor.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

import blake3
import google.protobuf
import sentencepiece as sentencepiece
from sentencepiece import sentencepiece_model_pb2


REPOSITORY = "google-t5/t5-base"
REVISION = "a9723ea7f1b39c1eae772870f3b547bf6ef7e6c1"
MODEL_BYTES = 791_656
MODEL_SHA256 = "d60acb128cf7b7f2536e8f38a5b18a05535c9e14c7a355904270e15b0945ea86"
MODEL_BLAKE3 = "blake3:18af7072534a34d626ca166c92f5e37c7ccfcd6ce6877c3c25d325bc8201090d"
REFERENCE_VERSION = "0.2.2"
BLAKE3_VERSION = "1.0.9"
PROTOBUF_VERSION = "6.33.6"
VOCAB_SIZE = 32_000
ADAPTER_FAMILY = "sentencepiece-unigram"
ADAPTER_VERSION = 2
ADAPTER_DIGEST = (
    "blake3:e56dc74051fdaf4a90a626328ad01c81b7cd26044b2b071b8d50302c07bbacd1"
)

SCHEMA = "uor-r4/t5-raw-sentencepiece-reference/1"
SINGLETON_DOMAIN = b"uor-r4/t5-raw-sentencepiece-singleton-decode/1\x00"

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MODEL = REPO_ROOT / ".uor-models/sources/t5-base-tokenizer/spiece.model"
DEFAULT_OUTPUT = (
    REPO_ROOT
    / "crates/uor-r4-core/tests/fixtures/t5_raw_sentencepiece_reference.json"
)


# These raw-text cases cover normalization, whitespace, ordinary Unicode,
# unknown spans, and multiple separated unknown spans.  No wrapper-level EOS
# or <extra_id_*> token is inserted by the reference processor.
ENCODE_INPUTS = [
    "",
    "Hello world",
    "Hello  world",
    "The quick brown fox.",
    "café",
    "naïve résumé",
    "ﬁ ligature and ½ fraction",
    "ｆｕｌｌｗｉｄｔｈ",
    "Ａ１２３",
    "①②③",
    "emoji 😀 test",
    "日本語のテキスト",
    " leading and  double   spaces ",
    "A🎉B🎉C",
    "\tTab\nNL",
    "Ⅻ roman",
    "㍿ square",
]

# Decode-only cases make special/control/unknown behavior explicit rather than
# leaving the full-vocabulary digest as an opaque mismatch signal.
DECODE_IDS = [
    [],
    [0],
    [1],
    [2],
    [3],
    [3, 2],
    [2, 2],
    [8774, 296],
    [71, 2, 279, 2, 254],
    [37, 1704, 4216, 3, 20400, 5],
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--model",
        type=Path,
        default=DEFAULT_MODEL,
        help="pinned T5 spiece.model (default: %(default)s)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="fixture path (default: %(default)s)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated bytes differ from --output; do not write",
    )
    return parser.parse_args()


def verify_reference_environment() -> None:
    version = getattr(sentencepiece, "__version__", None)
    if version != REFERENCE_VERSION:
        raise SystemExit(
            f"sentencepiece=={REFERENCE_VERSION} is required; found {version!r}"
        )
    blake3_version = getattr(blake3, "__version__", None)
    if blake3_version != BLAKE3_VERSION:
        raise SystemExit(
            f"blake3=={BLAKE3_VERSION} is required; found {blake3_version!r}"
        )
    protobuf_version = getattr(google.protobuf, "__version__", None)
    if protobuf_version != PROTOBUF_VERSION:
        raise SystemExit(
            f"protobuf=={PROTOBUF_VERSION} is required; found {protobuf_version!r}"
        )


def verify_adapter_pin() -> None:
    """Refuse to emit a fixture with a nullable or malformed adapter identity."""

    if ADAPTER_VERSION != 2:
        raise SystemExit(
            "the independent fixture must pin current sentencepiece-unigram/2"
        )
    prefix = "blake3:"
    if not isinstance(ADAPTER_DIGEST, str) or not ADAPTER_DIGEST.startswith(prefix):
        raise SystemExit("ADAPTER_DIGEST must be a pinned lowercase blake3 address")
    hex_digest = ADAPTER_DIGEST[len(prefix) :]
    if len(hex_digest) != 64 or any(
        byte not in "0123456789abcdef" for byte in hex_digest
    ):
        raise SystemExit("ADAPTER_DIGEST must be a pinned lowercase blake3 address")


def verify_model(path: Path) -> bytes:
    try:
        model = path.read_bytes()
    except OSError as error:
        raise SystemExit(f"cannot read pinned model {path}: {error}") from error

    measured_sha256 = hashlib.sha256(model).hexdigest()
    measured_blake3 = f"blake3:{blake3.blake3(model).hexdigest()}"
    errors = []
    if len(model) != MODEL_BYTES:
        errors.append(f"bytes {len(model)} != {MODEL_BYTES}")
    if measured_sha256 != MODEL_SHA256:
        errors.append(f"sha256 {measured_sha256} != {MODEL_SHA256}")
    if measured_blake3 != MODEL_BLAKE3:
        errors.append(f"blake3 {measured_blake3} != {MODEL_BLAKE3}")
    if errors:
        raise SystemExit(f"{path} is not the pinned T5 source: " + "; ".join(errors))
    return model


def singleton_decode_digest(processor: sentencepiece.SentencePieceProcessor) -> str:
    """Hash the ordered singleton-decode table in a language-neutral format."""

    digest = hashlib.sha256()
    digest.update(SINGLETON_DOMAIN)
    digest.update(VOCAB_SIZE.to_bytes(4, "little"))
    for token_id in range(VOCAB_SIZE):
        decoded = processor.decode([token_id]).encode("utf-8")
        digest.update(token_id.to_bytes(4, "little"))
        digest.update(len(decoded).to_bytes(4, "little"))
        digest.update(decoded)
    return f"sha256:{digest.hexdigest()}"


def build_fixture(model: bytes) -> dict[str, object]:
    processor = sentencepiece.SentencePieceProcessor(model_proto=model)
    if processor.get_piece_size() != VOCAB_SIZE:
        raise SystemExit(
            f"pinned model has {processor.get_piece_size()} pieces, expected {VOCAB_SIZE}"
        )

    encode_cases = []
    for text in ENCODE_INPUTS:
        ids = processor.encode(text, out_type=int)
        encode_cases.append(
            {
                "text": text,
                "ids": ids,
                "decoded": processor.decode(ids),
            }
        )

    decode_cases = [
        {"ids": ids, "decoded": processor.decode(ids)} for ids in DECODE_IDS
    ]

    out_of_range_ids = [VOCAB_SIZE]
    try:
        processor.decode(out_of_range_ids)
    except Exception as error:  # The exception type is part of the reference record.
        out_of_range_decode = {
            "ids": out_of_range_ids,
            "outcome": "error",
            "exception": type(error).__name__,
            "message": str(error),
        }
    else:
        raise SystemExit("reference accepted an out-of-range SentencePiece id")

    proto = sentencepiece_model_pb2.ModelProto()
    proto.ParseFromString(model)
    type_names = {
        sentencepiece_model_pb2.ModelProto.SentencePiece.NORMAL: "normal",
        sentencepiece_model_pb2.ModelProto.SentencePiece.UNKNOWN: "unknown",
        sentencepiece_model_pb2.ModelProto.SentencePiece.CONTROL: "control",
        sentencepiece_model_pb2.ModelProto.SentencePiece.USER_DEFINED: "user_defined",
        sentencepiece_model_pb2.ModelProto.SentencePiece.UNUSED: "unused",
        sentencepiece_model_pb2.ModelProto.SentencePiece.BYTE: "byte",
    }
    piece_type_ids = {name: [] for name in type_names.values()}
    for token_id, piece in enumerate(proto.pieces):
        piece_type_ids[type_names[piece.type]].append(token_id)
    piece_types = {}
    for name, ids in piece_type_ids.items():
        record = {"count": len(ids)}
        # The interesting non-normal inventories are tiny.  Recording all
        # 31,997 normal ids would defeat the compact-fixture design.
        if name != "normal":
            record["ids"] = ids
        piece_types[name] = record

    return {
        "schema": SCHEMA,
        "scope": (
            "raw spiece.model semantics only; excludes Hugging Face added "
            "tokens and post-processing"
        ),
        "source": {
            "repository": REPOSITORY,
            "revision": REVISION,
            "path": "spiece.model",
            "bytes": len(model),
            "sha256": hashlib.sha256(model).hexdigest(),
            "blake3": f"blake3:{blake3.blake3(model).hexdigest()}",
        },
        "reference": {
            "package": "sentencepiece",
            "version": REFERENCE_VERSION,
        },
        "adapter": {
            "family": ADAPTER_FAMILY,
            "version": ADAPTER_VERSION,
            "tokenizer_cid": f"blake3:{blake3.blake3(model).hexdigest()}",
            "adapter_digest": ADAPTER_DIGEST,
            "decision_status": "pinned",
        },
        "vocab_size": VOCAB_SIZE,
        "special_ids": {
            "pad": processor.pad_id(),
            "eos": processor.eos_id(),
            "unknown": processor.unk_id(),
            "bos": processor.bos_id(),
        },
        "singleton_decode": {
            "algorithm": "sha256",
            "domain_hex": SINGLETON_DOMAIN.hex(),
            "canonical_records": (
                "u32le(vocab_size), then for id=0..vocab_size-1: "
                "u32le(id) || u32le(decoded_utf8_bytes) || decoded_utf8"
            ),
            "digest": singleton_decode_digest(processor),
        },
        "encode_cases": encode_cases,
        "decode_cases": decode_cases,
        "out_of_range_decode": out_of_range_decode,
        "piece_types": piece_types,
        "generator": "scripts/gen_t5_sentencepiece_fixture.py",
    }


def canonical_json_bytes(fixture: dict[str, object]) -> bytes:
    text = json.dumps(
        fixture,
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )
    return (text + "\n").encode("utf-8")


def main() -> None:
    args = parse_args()
    verify_reference_environment()
    verify_adapter_pin()
    model = verify_model(args.model)
    fixture = build_fixture(model)
    generated = canonical_json_bytes(fixture)

    if args.check:
        try:
            existing = args.output.read_bytes()
        except OSError as error:
            raise SystemExit(f"cannot read fixture {args.output}: {error}") from error
        if existing != generated:
            raise SystemExit(
                f"{args.output} differs; regenerate with sentencepiece=={REFERENCE_VERSION}"
            )
        print(f"PASS: {args.output} matches the pinned independent reference")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(generated)
    print(f"wrote {args.output}")
    print(f"source: {REPOSITORY}@{REVISION} ({MODEL_BYTES} bytes)")
    print(f"singleton decode: {fixture['singleton_decode']['digest']}")


if __name__ == "__main__":
    try:
        main()
    except BrokenPipeError:
        sys.exit(1)
