-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — Cohomology individual constants.

import UOR.Structures
import UOR.Individuals.Op
import UOR.Individuals.Schema

open UOR.Primitives

namespace UOR.Bridge.Cohomology

-- δ² = 0: the coboundary of a coboundary is zero.
def coboundarySquaredZero : UOR.Kernel.Op.Identity UOR.Prims.Standard := {
  lhs := some (UOR.Kernel.Schema.term_coboundarySquaredZero_lhs.toTermExpression)
  rhs := some (UOR.Kernel.Schema.term_coboundarySquaredZero_rhs.toTermExpression)
  forAll := some (UOR.Kernel.Schema.term_coboundarySquaredZero_forAll)
  verificationDomain := #[.topological]
  verifiedAtLevel := #[]
  universallyValid := none
  validityKind := none
  validKMin := none
  validKMax := none
}

-- Discrete de Rham duality: H^k ≅ Hom(H_k, R).
def deRhamDuality : UOR.Kernel.Op.Identity UOR.Prims.Standard := {
  lhs := some (UOR.Kernel.Schema.term_deRhamDuality_lhs.toTermExpression)
  rhs := some (UOR.Kernel.Schema.term_deRhamDuality_rhs.toTermExpression)
  forAll := some (UOR.Kernel.Schema.term_deRhamDuality_forAll)
  verificationDomain := #[.topological]
  verifiedAtLevel := #[]
  universallyValid := none
  validityKind := none
  validKMin := none
  validKMax := none
}

-- Local-global principle: H^1(K; F) = 0 implies all local sections glue to global sections.
def localGlobalPrinciple : UOR.Kernel.Op.Identity UOR.Prims.Standard := {
  lhs := some (UOR.Kernel.Schema.term_localGlobalPrinciple_lhs.toTermExpression)
  rhs := some (UOR.Kernel.Schema.term_localGlobalPrinciple_rhs.toTermExpression)
  forAll := some (UOR.Kernel.Schema.term_localGlobalPrinciple_forAll)
  verificationDomain := #[.topological]
  verifiedAtLevel := #[]
  universallyValid := none
  validityKind := none
  validKMin := none
  validKMax := none
}

-- Sheaf cohomology equals simplicial cohomology for constant sheaves.
def sheafCohomologyBridge : UOR.Kernel.Op.Identity UOR.Prims.Standard := {
  lhs := some (UOR.Kernel.Schema.term_sheafCohomologyBridge_lhs.toTermExpression)
  rhs := some (UOR.Kernel.Schema.term_sheafCohomologyBridge_rhs.toTermExpression)
  forAll := some (UOR.Kernel.Schema.term_sheafCohomologyBridge_forAll)
  verificationDomain := #[.topological]
  verifiedAtLevel := #[]
  universallyValid := none
  validityKind := none
  validKMin := none
  validKMax := none
}

end UOR.Bridge.Cohomology
