-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — Predicate individual constants.

import UOR.Structures
import UOR.Individuals.State

open UOR.Primitives

namespace UOR.Kernel.Predicate

-- The predicate:DispatchTable governing resolver:InhabitanceResolver. Three rules form a partition of type:ConstrainedType: Is2SatShape → TwoSatDecider (priority 0), IsHornShape → HornSatDecider (priority 1), IsResidualFragment → ResidualVerdictResolver (priority 2, catch-all). Total coverage is enforced by reduction:DispatchCoverageCheck; DispatchMiss is unreachable for this table.
def InhabitanceDispatchTable : UOR.Kernel.Predicate.DispatchTable UOR.Prims.Standard := {
  dispatchRules := #[]
  isExhaustive := some (true)
  isMutuallyExclusive := some (true)
}

-- True on ConstrainedType instances whose constraint nerve contains only disjunctions of width ≤ 2.
def Is2SatShape : UOR.Kernel.Predicate.TypePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/type/ConstrainedType" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True on ConstrainedType instances whose disjunctions each contain at most one positive literal.
def IsHornShape : UOR.Kernel.Predicate.TypePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/type/ConstrainedType" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- Default (catch-all) predicate. True on ConstrainedType instances not classified by Is2SatShape or IsHornShape.
def IsResidualFragment : UOR.Kernel.Predicate.TypePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/type/ConstrainedType" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True on every Datum. Match-arm default catch-all.
def always : UOR.Kernel.Predicate.Predicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/schema/Datum" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True iff the FreeRank deficit is zero.
def budgetExhausted : UOR.Kernel.Predicate.StatePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/partition/FreeRank" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True iff the resolver has entered a ContradictionBoundary.
def contradictionReached : UOR.Kernel.Predicate.StatePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/state/ContradictionBoundary" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- Dispatch rule 1 of InhabitanceDispatchTable: Is2SatShape → TwoSatDecider at priority 0.
def inhabitance_rule_2sat : UOR.Kernel.Predicate.DispatchRule UOR.Prims.Standard := {
  dispatchPredicate := some (UOR.Kernel.Predicate.Is2SatShape.toPredicate)
  dispatchTarget := some (("https://uor.foundation/resolver/TwoSatDecider" : String))
  dispatchPriority := some ((0 : Nat))
  dispatchIndex := none
}

-- Dispatch rule 2 of InhabitanceDispatchTable: IsHornShape → HornSatDecider at priority 1.
def inhabitance_rule_horn : UOR.Kernel.Predicate.DispatchRule UOR.Prims.Standard := {
  dispatchPredicate := some (UOR.Kernel.Predicate.IsHornShape.toPredicate)
  dispatchTarget := some (("https://uor.foundation/resolver/HornSatDecider" : String))
  dispatchPriority := some ((1 : Nat))
  dispatchIndex := none
}

-- Dispatch rule 3 (catch-all) of InhabitanceDispatchTable: IsResidualFragment → ResidualVerdictResolver at priority 2. Ensures total coverage.
def inhabitance_rule_residual : UOR.Kernel.Predicate.DispatchRule UOR.Prims.Standard := {
  dispatchPredicate := some (UOR.Kernel.Predicate.IsResidualFragment.toPredicate)
  dispatchTarget := some (("https://uor.foundation/resolver/ResidualVerdictResolver" : String))
  dispatchPriority := some ((2 : Nat))
  dispatchIndex := none
}

-- True iff the Datum parity bit is 0.
def isEven : UOR.Kernel.Predicate.TypePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/schema/Datum" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True iff op(op(x)) = x for the bound op.
def isInvolution : UOR.Kernel.Predicate.TypePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/schema/Datum" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True iff the Datum parity bit is 1.
def isOdd : UOR.Kernel.Predicate.TypePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/schema/Datum" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True iff the Datum is the multiplicative identity.
def isUnit : UOR.Kernel.Predicate.TypePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/schema/Datum" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True iff the Datum is the additive identity of its ring.
def isZero : UOR.Kernel.Predicate.TypePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/schema/Datum" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- False on every Datum. Disabled-arm marker.
def never : UOR.Kernel.Predicate.Predicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/schema/Datum" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True iff the reduction fixpoint has been reached.
def reductionConverged : UOR.Kernel.Predicate.StatePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/reduction/ReductionState" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True iff the named site coordinate is currently free.
def siteFree : UOR.Kernel.Predicate.SitePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/partition/SiteIndex" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

-- True iff the named site coordinate is currently pinned.
def sitePinned : UOR.Kernel.Predicate.SitePredicate UOR.Prims.Standard := {
  evaluatesOver := some (("https://uor.foundation/partition/SiteIndex" : String))
  evaluatorTerm := none
  terminationWitness := none
  boundedEvaluator := #[]
}

end UOR.Kernel.Predicate
