-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — State individual constants.

import UOR.Structures

open UOR.Primitives

namespace UOR.User.State

-- The canonical ground-state witness: a GroundedContext at σ = 1, freeRank = 0, T_ctx = 0, S = 0 (SC_4). Demonstrates that full saturation is achievable and O(1) resolution (SC_5) is realized.
def ground_state : UOR.User.State.GroundedContext UOR.Prims.Standard := {
  groundedTriad := none
  binding := #[]
  capacity := none
  contentAddress := none
  wittLength := none
  groundingDegree := some ((1 : Float))
  contextTemperature := some ((0 : Float))
  isGrounded := some (true)
  groundingPhase := some (.fullGrounding)
  residualFreeCount := some ((0 : Nat))
}

end UOR.User.State
