//! GNAF root-import module check (SPEC 5), ported from the vendored
//! `proofs/wasm-gemm-gnaf/Tools/root.py` (#653 phase-2 follow-up, second
//! `Tools/*.py` port after `gnaf_firewall.rs`).
//!
//! "SPEC 5 fixes the layer structure. A file that belongs to no layer is
//! scratch, and scratch in the proof path is how a broken or unreviewed
//! module reaches the build." (`Tools/root.py`'s own docstring.)
//!
//! Every `.lean` file under `WasmGemmGnaf/` must live at least two path
//! segments deep, with its first segment naming one of the ten SPEC-5
//! layers; a file that doesn't is reported as unowned. From the owned
//! modules, this regenerates the root import file
//! `proofs/wasm-gemm-gnaf/WasmGemmGnaf.lean`, grouped by layer in SPEC-5
//! order and sorted within each layer -- byte-for-byte the same shape
//! `Tools/root.py` produces. `--check` mode (the mode this repository's own
//! gate ladder uses) reports staleness without writing; write mode
//! regenerates the file.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::Fail;

/// SPEC 5's fixed layer order. A module's first path segment under
/// `WasmGemmGnaf/` must name one of these, and the generated root file
/// groups imports by layer in this exact order.
const LAYERS: [&str; 10] = [
    "Foundation",
    "Wasm",
    "Cost",
    "Gemm",
    "GNAF",
    "Universal",
    "Atlas",
    "Artifact",
    "Theorems",
    "Conformance",
];

/// SPEC 5: every `.lean` file under `WasmGemmGnaf/` belongs to a named
/// layer, and the generated root import file is current.
pub fn gnaf_root(root: &Path, check: bool) -> Result<(), Fail> {
    let gnaf_dir = root.join("proofs/wasm-gemm-gnaf");
    let base = gnaf_dir.join("WasmGemmGnaf");
    if !base.exists() {
        return Err(format!(
            "{} not found; the vendored GNAF proof tree (#742) is expected \
             at this path",
            base.display()
        )
        .into());
    }

    let mut files = Vec::new();
    collect_lean(&base, &mut files)?;
    files.sort();

    let mut by_layer: BTreeMap<&str, Vec<String>> = BTreeMap::new();
    let mut unowned = Vec::new();
    for path in &files {
        let rel = path.strip_prefix(&base).unwrap_or(path);
        let rel = rel.with_extension("");
        let parts: Vec<&str> = rel
            .components()
            .map(|c| c.as_os_str().to_str().unwrap_or(""))
            .collect();
        // Look up the `&'static str` from LAYERS itself rather than keeping
        // `parts[0]` (which borrows this iteration's local `rel`), so the
        // map key's lifetime doesn't depend on a value dropped at the end
        // of the loop body.
        let layer: Option<&'static str> = parts
            .first()
            .and_then(|p0| LAYERS.iter().find(|&&l| l == *p0))
            .copied();
        match layer {
            Some(l) if parts.len() >= 2 => {
                by_layer
                    .entry(l)
                    .or_default()
                    .push(format!("WasmGemmGnaf.{}", parts.join(".")));
            }
            _ => unowned.push(format!("WasmGemmGnaf/{}.lean", parts.join("/"))),
        }
    }

    if !unowned.is_empty() {
        unowned.sort();
        return Err(format!(
            "UNOWNED MODULES (belong to no SPEC 5 layer -- scratch?):\n{}",
            unowned
                .iter()
                .map(|u| format!("  {u}"))
                .collect::<Vec<_>>()
                .join("\n")
        )
        .into());
    }

    let text = render(&by_layer);
    let total: usize = by_layer.values().map(Vec::len).sum();
    let root_lean = gnaf_dir.join("WasmGemmGnaf.lean");

    if check {
        let current = std::fs::read_to_string(&root_lean).unwrap_or_default();
        if current != text {
            return Err(format!(
                "{} is STALE -- run `cargo xtask gnaf-root`",
                root_lean.display()
            )
            .into());
        }
        println!("gnaf-root: root imports current: {total} modules, no unowned files (SPEC 5)");
    } else {
        std::fs::write(&root_lean, &text)?;
        println!("gnaf-root: root regenerated: {total} modules (SPEC 5)");
    }
    Ok(())
}

/// Render the root import file text: the fixed header comment, then one
/// block per non-empty layer (in `LAYERS` order) of `-- Layer` followed by
/// its modules' `import` lines sorted lexicographically, blank-line
/// separated, with exactly one trailing newline. Byte-for-byte the same
/// shape `Tools/root.py` writes.
fn render(by_layer: &BTreeMap<&str, Vec<String>>) -> String {
    let mut out: Vec<String> = vec![
        "/-".to_string(),
        "  Root module: imports every layer of the WASM-GEMM-GNAF development.".to_string(),
        "  Generated by `just root`; do not edit by hand.".to_string(),
        "-/".to_string(),
        String::new(),
    ];
    for layer in LAYERS {
        let Some(modules) = by_layer.get(layer) else {
            continue;
        };
        out.push(format!("-- {layer}"));
        let mut sorted = modules.clone();
        sorted.sort();
        out.extend(sorted.into_iter().map(|m| format!("import {m}")));
        out.push(String::new());
    }
    let mut text = out.join("\n").trim_end().to_string();
    text.push('\n');
    text
}

fn collect_lean(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), Fail> {
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_lean(&path, out)?;
        } else if path.extension().is_some_and(|e| e == "lean") {
            out.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_dir(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "xtask-gnaf-root-test-{name}-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ))
    }

    /// Regression guard mirroring `Tools/root.py --check` against a
    /// synthetic layout: an owned module produces the expected grouped,
    /// sorted, layer-ordered root file, and re-checking against exactly
    /// that generated content reports current (not stale). Built entirely
    /// under `std::env::temp_dir()` -- never against the real vendored tree.
    #[test]
    fn gnaf_root_generates_a_layer_ordered_file_and_check_agrees_with_it() {
        let root = scratch_dir("owned");
        let gnaf = root.join("proofs/wasm-gemm-gnaf");
        std::fs::create_dir_all(gnaf.join("WasmGemmGnaf/Foundation")).unwrap();
        std::fs::create_dir_all(gnaf.join("WasmGemmGnaf/Wasm")).unwrap();
        std::fs::write(
            gnaf.join("WasmGemmGnaf/Foundation/Types.lean"),
            "-- irrelevant to root.py, only the path matters\n",
        )
        .unwrap();
        std::fs::write(gnaf.join("WasmGemmGnaf/Foundation/Bytes.lean"), "").unwrap();
        std::fs::write(gnaf.join("WasmGemmGnaf/Wasm/Semantics.lean"), "").unwrap();

        // Write mode regenerates the file...
        gnaf_root(&root, false).unwrap();
        let written = std::fs::read_to_string(gnaf.join("WasmGemmGnaf.lean")).unwrap();
        assert!(written.starts_with("/-\n  Root module:"));
        // Foundation before Wasm (LAYERS order), Bytes before Types (sorted
        // within a layer, not file-discovery order).
        let foundation_pos = written.find("-- Foundation").unwrap();
        let wasm_pos = written.find("-- Wasm").unwrap();
        let bytes_pos = written
            .find("import WasmGemmGnaf.Foundation.Bytes")
            .unwrap();
        let types_pos = written
            .find("import WasmGemmGnaf.Foundation.Types")
            .unwrap();
        assert!(foundation_pos < wasm_pos);
        assert!(bytes_pos < types_pos);
        assert!(written.ends_with('\n') && !written.ends_with("\n\n"));

        // ...and --check against exactly that output reports current, not stale.
        assert!(gnaf_root(&root, true).is_ok());

        std::fs::remove_dir_all(&root).unwrap();
    }

    /// A `.lean` file with no layer-named parent directory (or living
    /// directly under `WasmGemmGnaf/` with no subdirectory at all) is
    /// unowned scratch and must be rejected in both modes.
    #[test]
    fn gnaf_root_rejects_an_unowned_module() {
        let root = scratch_dir("unowned");
        let gnaf = root.join("proofs/wasm-gemm-gnaf");
        std::fs::create_dir_all(gnaf.join("WasmGemmGnaf/Scratch")).unwrap();
        std::fs::write(gnaf.join("WasmGemmGnaf/Scratch/Loose.lean"), "").unwrap();

        assert!(gnaf_root(&root, false).is_err());
        assert!(gnaf_root(&root, true).is_err());
        // No partial write on rejection.
        assert!(!gnaf.join("WasmGemmGnaf.lean").exists());

        std::fs::remove_dir_all(&root).unwrap();
    }

    /// A stale checked-in root file (content that doesn't match what the
    /// current tree would generate) must be rejected by `--check` without
    /// being silently rewritten.
    #[test]
    fn gnaf_root_check_mode_rejects_a_stale_file_without_writing() {
        let root = scratch_dir("stale");
        let gnaf = root.join("proofs/wasm-gemm-gnaf");
        std::fs::create_dir_all(gnaf.join("WasmGemmGnaf/Foundation")).unwrap();
        std::fs::write(gnaf.join("WasmGemmGnaf/Foundation/Types.lean"), "").unwrap();
        std::fs::write(gnaf.join("WasmGemmGnaf.lean"), "stale placeholder\n").unwrap();

        assert!(gnaf_root(&root, true).is_err());
        assert_eq!(
            std::fs::read_to_string(gnaf.join("WasmGemmGnaf.lean")).unwrap(),
            "stale placeholder\n",
            "check mode must not rewrite the file it just rejected"
        );

        std::fs::remove_dir_all(&root).unwrap();
    }
}
