/* uor-addr-c — C ABI bindings for the uor-addr crate.
* Auto-generated by cbindgen. Do not edit by hand.
*
* Apache-2.0 — https://github.com/UOR-Foundation/uor-addr
*/

#ifndef UOR_ADDR_H
#define UOR_ADDR_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// σ-axis selector for the `*_with_hash` entry points: SHA-256 (default).
#define UOR_ADDR_HASH_SHA256 0

// σ-axis selector: BLAKE3.
#define UOR_ADDR_HASH_BLAKE3 1

// σ-axis selector: SHA3-256 (FIPS 202).
#define UOR_ADDR_HASH_SHA3_256 2

// σ-axis selector: Keccak-256 (pre-FIPS padding).
#define UOR_ADDR_HASH_KECCAK256 3

// σ-axis selector: SHA-512 (FIPS 180-4; 64-byte digest → 135-byte label).
#define UOR_ADDR_HASH_SHA512 4

// Success.
#define UOR_ADDR_OK 0

// `input == NULL && input_len > 0`, or `out_label == NULL`.
#define UOR_ADDR_ERR_NULL_POINTER -1

// `out_label_len < UOR_ADDR_LABEL_BYTES`.
#define UOR_ADDR_ERR_BUFFER_TOO_SMALL -2

// Input failed the realization's host-boundary parser.
#define UOR_ADDR_ERR_INVALID_INPUT -3

// **Reserved** — never returned under ADR-060 (inputs are unbounded;
// the per-realization size/count caps were removed). Retained so
// existing `-4` handlers in downstream C consumers keep compiling.
#define UOR_ADDR_ERR_TOO_LARGE -4

// Defensive — substrate-level pipeline failure.
#define UOR_ADDR_ERR_PIPELINE -5

// Unknown σ-axis selector passed to a `*_with_hash` entry point (not one
// of the `UOR_ADDR_HASH_*` constants).
#define UOR_ADDR_ERR_UNKNOWN_HASH -6

// A composition operand's σ-axis does not match the operation's axis
// (CA-3 σ-axis homogeneity), or — for the binary product — the two
// operands carry different axes.
#define UOR_ADDR_ERR_SIGMA_AXIS_MISMATCH -7

// `verify()` failed: empty trace. **Reserved** — the live verify path maps
// every failure to `UOR_ADDR_ERR_PIPELINE`; retained for ABI stability.
#define UOR_ADDR_ERR_VERIFY_EMPTY_TRACE -10

// **Reserved** (see above).
#define UOR_ADDR_ERR_VERIFY_OUT_OF_ORDER_EVENT -11

// **Reserved** (see above).
#define UOR_ADDR_ERR_VERIFY_ZERO_TARGET -12

// **Reserved** (see above).
#define UOR_ADDR_ERR_VERIFY_NON_CONTIGUOUS_STEPS -13

// **Reserved** (see above).
#define UOR_ADDR_ERR_VERIFY_CAPACITY_EXCEEDED -14

// Width-erased owned outcome — one opaque `UorAddrGrounded` handle carries
// a κ-label of any admissible σ-axis width (71 / 73 / 74 for the 32-byte
// fingerprint axes, 135 for sha512's 64-byte fingerprint).
typedef struct AnyOutcome AnyOutcome;

// Opaque, foreign-managed witness handle. Construct via any
// `uor_addr_*_with_witness[_hash]` function; release with
// `uor_addr_grounded_free`.
typedef struct UorAddrGrounded {
  struct AnyOutcome outcome;
} UorAddrGrounded;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Wire-format κ-label byte width under the default σ-axis (sha256) —
// `len("sha256:") + 64 = 71`.
extern const uintptr_t UOR_ADDR_LABEL_BYTES;

// Widest κ-label byte width across the admissible σ-axes (keccak256 →
// `len("keccak256:") + 64 = 74`). A `*_with_hash` output buffer sized to
// this fits every algorithm.
extern const uintptr_t UOR_ADDR_MAX_LABEL_BYTES;

// `json` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_json(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// `json` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_json`].
int32_t uor_addr_json_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// `sexp` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_sexp(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// `sexp` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_sexp`].
int32_t uor_addr_sexp_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// `xml` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_xml(const uint8_t *input,
                     uintptr_t input_len,
                     uint8_t *out_label,
                     uintptr_t out_label_len,
                     uintptr_t *out_written);

// `xml` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_xml`].
int32_t uor_addr_xml_with_hash(uint8_t algo,
                               const uint8_t *input,
                               uintptr_t input_len,
                               uint8_t *out_label,
                               uintptr_t out_label_len,
                               uintptr_t *out_written);

// `asn1` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_asn1(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// `asn1` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_asn1`].
int32_t uor_addr_asn1_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// `ring` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_ring(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// `ring` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_ring`].
int32_t uor_addr_ring_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// `codemodule` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_codemodule(const uint8_t *input,
                            uintptr_t input_len,
                            uint8_t *out_label,
                            uintptr_t out_label_len,
                            uintptr_t *out_written);

// `codemodule` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_codemodule`].
int32_t uor_addr_codemodule_with_hash(uint8_t algo,
                                      const uint8_t *input,
                                      uintptr_t input_len,
                                      uint8_t *out_label,
                                      uintptr_t out_label_len,
                                      uintptr_t *out_written);

// `cbor` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_cbor(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// `cbor` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_cbor`].
int32_t uor_addr_cbor_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// `schema_photo` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_schema_photo(const uint8_t *input,
                              uintptr_t input_len,
                              uint8_t *out_label,
                              uintptr_t out_label_len,
                              uintptr_t *out_written);

// `schema_photo` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_schema_photo`].
int32_t uor_addr_schema_photo_with_hash(uint8_t algo,
                                        const uint8_t *input,
                                        uintptr_t input_len,
                                        uint8_t *out_label,
                                        uintptr_t out_label_len,
                                        uintptr_t *out_written);

// `schema_document` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_schema_document(const uint8_t *input,
                                 uintptr_t input_len,
                                 uint8_t *out_label,
                                 uintptr_t out_label_len,
                                 uintptr_t *out_written);

// `schema_document` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_schema_document`].
int32_t uor_addr_schema_document_with_hash(uint8_t algo,
                                           const uint8_t *input,
                                           uintptr_t input_len,
                                           uint8_t *out_label,
                                           uintptr_t out_label_len,
                                           uintptr_t *out_written);

// `schema_codemodule_signed` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_schema_codemodule_signed(const uint8_t *input,
                                          uintptr_t input_len,
                                          uint8_t *out_label,
                                          uintptr_t out_label_len,
                                          uintptr_t *out_written);

// `schema_codemodule_signed` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_schema_codemodule_signed`].
int32_t uor_addr_schema_codemodule_signed_with_hash(uint8_t algo,
                                                    const uint8_t *input,
                                                    uintptr_t input_len,
                                                    uint8_t *out_label,
                                                    uintptr_t out_label_len,
                                                    uintptr_t *out_written);

// `gguf` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_gguf(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// `gguf` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_gguf`].
int32_t uor_addr_gguf_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// `onnx` realization — default σ-axis (SHA-256).
//
// # Safety
//
// - `input` is null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_label` is writable for at least `out_label_len` bytes.
// - `out_written` if non-null points to a writable `size_t`.
int32_t uor_addr_onnx(const uint8_t *input,
                      uintptr_t input_len,
                      uint8_t *out_label,
                      uintptr_t out_label_len,
                      uintptr_t *out_written);

// `onnx` realization under a caller-selected σ-axis (`UOR_ADDR_HASH_*`).
// `out_label` must be writable for at least `UOR_ADDR_MAX_LABEL_BYTES`.
//
// # Safety
//
// As [`uor_addr_onnx`].
int32_t uor_addr_onnx_with_hash(uint8_t algo,
                                const uint8_t *input,
                                uintptr_t input_len,
                                uint8_t *out_label,
                                uintptr_t out_label_len,
                                uintptr_t *out_written);

// Free a Grounded handle. Null is a no-op; each handle is freed once.
//
// # Safety
//
// `handle` is null or a pointer from a `*_with_witness[_hash]` call.
void uor_addr_grounded_free(struct UorAddrGrounded *handle);

// Read the κ-label this Grounded carries into `out_label` (its width
// depends on the σ-axis; size `out_label` to `UOR_ADDR_MAX_LABEL_BYTES`).
//
// # Safety
//
// - `handle` is a live handle from a `*_with_witness[_hash]` call.
// - `out_label` writable for `out_label_len` bytes; `out_written` if
//   non-null writable.
int32_t uor_addr_grounded_kappa_label(const struct UorAddrGrounded *handle,
                                      uint8_t *out_label,
                                      uintptr_t out_label_len,
                                      uintptr_t *out_written);

// Read the σ-projection content fingerprint into `out_digest` (32 bytes
// for the `Hasher<32>` axes, 64 for sha512). Size `out_digest` to 64.
//
// # Safety
//
// As [`uor_addr_grounded_kappa_label`].
int32_t uor_addr_grounded_content_fingerprint(const struct UorAddrGrounded *handle,
                                              uint8_t *out_digest,
                                              uintptr_t out_digest_len,
                                              uintptr_t *out_written);

// Verify the witness by re-certifying its replay trace (no σ-axis
// re-invocation) and write the recovered κ-label into `out_label`.
//
// # Safety
//
// As [`uor_addr_grounded_kappa_label`].
int32_t uor_addr_grounded_verify(const struct UorAddrGrounded *handle,
                                 uint8_t *out_label,
                                 uintptr_t out_label_len,
                                 uintptr_t *out_written);

// `json` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_json_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// `json` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_json_with_witness`].
int32_t uor_addr_json_with_witness_hash(uint8_t algo,
                                        const uint8_t *input,
                                        uintptr_t input_len,
                                        struct UorAddrGrounded **out_handle);

// `sexp` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_sexp_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// `sexp` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_sexp_with_witness`].
int32_t uor_addr_sexp_with_witness_hash(uint8_t algo,
                                        const uint8_t *input,
                                        uintptr_t input_len,
                                        struct UorAddrGrounded **out_handle);

// `xml` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_xml_with_witness(const uint8_t *input,
                                  uintptr_t input_len,
                                  struct UorAddrGrounded **out_handle);

// `xml` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_xml_with_witness`].
int32_t uor_addr_xml_with_witness_hash(uint8_t algo,
                                       const uint8_t *input,
                                       uintptr_t input_len,
                                       struct UorAddrGrounded **out_handle);

// `asn1` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_asn1_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// `asn1` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_asn1_with_witness`].
int32_t uor_addr_asn1_with_witness_hash(uint8_t algo,
                                        const uint8_t *input,
                                        uintptr_t input_len,
                                        struct UorAddrGrounded **out_handle);

// `ring` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_ring_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// `ring` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_ring_with_witness`].
int32_t uor_addr_ring_with_witness_hash(uint8_t algo,
                                        const uint8_t *input,
                                        uintptr_t input_len,
                                        struct UorAddrGrounded **out_handle);

// `codemodule` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_codemodule_with_witness(const uint8_t *input,
                                         uintptr_t input_len,
                                         struct UorAddrGrounded **out_handle);

// `codemodule` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_codemodule_with_witness`].
int32_t uor_addr_codemodule_with_witness_hash(uint8_t algo,
                                              const uint8_t *input,
                                              uintptr_t input_len,
                                              struct UorAddrGrounded **out_handle);

// `cbor` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_cbor_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// `cbor` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_cbor_with_witness`].
int32_t uor_addr_cbor_with_witness_hash(uint8_t algo,
                                        const uint8_t *input,
                                        uintptr_t input_len,
                                        struct UorAddrGrounded **out_handle);

// `schema_photo` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_schema_photo_with_witness(const uint8_t *input,
                                           uintptr_t input_len,
                                           struct UorAddrGrounded **out_handle);

// `schema_photo` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_schema_photo_with_witness`].
int32_t uor_addr_schema_photo_with_witness_hash(uint8_t algo,
                                                const uint8_t *input,
                                                uintptr_t input_len,
                                                struct UorAddrGrounded **out_handle);

// `schema_document` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_schema_document_with_witness(const uint8_t *input,
                                              uintptr_t input_len,
                                              struct UorAddrGrounded **out_handle);

// `schema_document` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_schema_document_with_witness`].
int32_t uor_addr_schema_document_with_witness_hash(uint8_t algo,
                                                   const uint8_t *input,
                                                   uintptr_t input_len,
                                                   struct UorAddrGrounded **out_handle);

// `schema_codemodule_signed` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_schema_codemodule_signed_with_witness(const uint8_t *input,
                                                       uintptr_t input_len,
                                                       struct UorAddrGrounded **out_handle);

// `schema_codemodule_signed` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_schema_codemodule_signed_with_witness`].
int32_t uor_addr_schema_codemodule_signed_with_witness_hash(uint8_t algo,
                                                            const uint8_t *input,
                                                            uintptr_t input_len,
                                                            struct UorAddrGrounded **out_handle);

// `gguf` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_gguf_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// `gguf` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_gguf_with_witness`].
int32_t uor_addr_gguf_with_witness_hash(uint8_t algo,
                                        const uint8_t *input,
                                        uintptr_t input_len,
                                        struct UorAddrGrounded **out_handle);

// `onnx` realization — SHA-256 verifiable witness handle.
//
// # Safety
//
// - `input` null (with `input_len == 0`) or readable for `input_len` bytes.
// - `out_handle` is a valid writable `*mut UorAddrGrounded`.
int32_t uor_addr_onnx_with_witness(const uint8_t *input,
                                   uintptr_t input_len,
                                   struct UorAddrGrounded **out_handle);

// `onnx` realization — verifiable witness handle under a caller-selected
// σ-axis (`UOR_ADDR_HASH_*`).
//
// # Safety
//
// As [`uor_addr_onnx_with_witness`].
int32_t uor_addr_onnx_with_witness_hash(uint8_t algo,
                                        const uint8_t *input,
                                        uintptr_t input_len,
                                        struct UorAddrGrounded **out_handle);

// CS-G2 composition (label). `algo` selects the σ-axis (operand
// width + composed axis); `out_label` must be writable for at least
// `UOR_ADDR_MAX_LABEL_BYTES` bytes.
//
// # Safety
//
// Operand pointers are null (with len 0) or readable for their lengths;
// `out_label` writable for `out_label_len`; `out_written` if non-null
// writable.
int32_t uor_addr_compose_g2(uint8_t algo,
                            const uint8_t *left,
                            uintptr_t left_len,
                            const uint8_t *right,
                            uintptr_t right_len,
                            uint8_t *out_label,
                            uintptr_t out_label_len,
                            uintptr_t *out_written);

// CS-G2 composition (verifiable witness handle). See
// [`uor_addr_compose_g2`].
//
// # Safety
//
// As [`uor_addr_compose_g2`]; `out_handle` is a valid writable
// `*mut UorAddrGrounded`.
int32_t uor_addr_compose_g2_with_witness(uint8_t algo,
                                         const uint8_t *left,
                                         uintptr_t left_len,
                                         const uint8_t *right,
                                         uintptr_t right_len,
                                         struct UorAddrGrounded **out_handle);

// CS-F4 composition (label). `algo` selects the σ-axis (operand
// width + composed axis); `out_label` must be writable for at least
// `UOR_ADDR_MAX_LABEL_BYTES` bytes.
//
// # Safety
//
// Operand pointers are null (with len 0) or readable for their lengths;
// `out_label` writable for `out_label_len`; `out_written` if non-null
// writable.
int32_t uor_addr_compose_f4(uint8_t algo,
                            const uint8_t *operand,
                            uintptr_t operand_len,
                            uint8_t *out_label,
                            uintptr_t out_label_len,
                            uintptr_t *out_written);

// CS-F4 composition (verifiable witness handle). See
// [`uor_addr_compose_f4`].
//
// # Safety
//
// As [`uor_addr_compose_f4`]; `out_handle` is a valid writable
// `*mut UorAddrGrounded`.
int32_t uor_addr_compose_f4_with_witness(uint8_t algo,
                                         const uint8_t *operand,
                                         uintptr_t operand_len,
                                         struct UorAddrGrounded **out_handle);

// CS-E6 composition (label). `algo` selects the σ-axis (operand
// width + composed axis); `out_label` must be writable for at least
// `UOR_ADDR_MAX_LABEL_BYTES` bytes.
//
// # Safety
//
// Operand pointers are null (with len 0) or readable for their lengths;
// `out_label` writable for `out_label_len`; `out_written` if non-null
// writable.
int32_t uor_addr_compose_e6(uint8_t algo,
                            const uint8_t *operand,
                            uintptr_t operand_len,
                            uint8_t *out_label,
                            uintptr_t out_label_len,
                            uintptr_t *out_written);

// CS-E6 composition (verifiable witness handle). See
// [`uor_addr_compose_e6`].
//
// # Safety
//
// As [`uor_addr_compose_e6`]; `out_handle` is a valid writable
// `*mut UorAddrGrounded`.
int32_t uor_addr_compose_e6_with_witness(uint8_t algo,
                                         const uint8_t *operand,
                                         uintptr_t operand_len,
                                         struct UorAddrGrounded **out_handle);

// CS-E7 composition (label). `algo` selects the σ-axis (operand
// width + composed axis); `out_label` must be writable for at least
// `UOR_ADDR_MAX_LABEL_BYTES` bytes.
//
// # Safety
//
// Operand pointers are null (with len 0) or readable for their lengths;
// `out_label` writable for `out_label_len`; `out_written` if non-null
// writable.
int32_t uor_addr_compose_e7(uint8_t algo,
                            const uint8_t *operand,
                            uintptr_t operand_len,
                            uint8_t *out_label,
                            uintptr_t out_label_len,
                            uintptr_t *out_written);

// CS-E7 composition (verifiable witness handle). See
// [`uor_addr_compose_e7`].
//
// # Safety
//
// As [`uor_addr_compose_e7`]; `out_handle` is a valid writable
// `*mut UorAddrGrounded`.
int32_t uor_addr_compose_e7_with_witness(uint8_t algo,
                                         const uint8_t *operand,
                                         uintptr_t operand_len,
                                         struct UorAddrGrounded **out_handle);

// CS-E8 composition (label). `algo` selects the σ-axis (operand
// width + composed axis); `out_label` must be writable for at least
// `UOR_ADDR_MAX_LABEL_BYTES` bytes.
//
// # Safety
//
// Operand pointers are null (with len 0) or readable for their lengths;
// `out_label` writable for `out_label_len`; `out_written` if non-null
// writable.
int32_t uor_addr_compose_e8(uint8_t algo,
                            const uint8_t *operand,
                            uintptr_t operand_len,
                            uint8_t *out_label,
                            uintptr_t out_label_len,
                            uintptr_t *out_written);

// CS-E8 composition (verifiable witness handle). See
// [`uor_addr_compose_e8`].
//
// # Safety
//
// As [`uor_addr_compose_e8`]; `out_handle` is a valid writable
// `*mut UorAddrGrounded`.
int32_t uor_addr_compose_e8_with_witness(uint8_t algo,
                                         const uint8_t *operand,
                                         uintptr_t operand_len,
                                         struct UorAddrGrounded **out_handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UOR_ADDR_H */
