/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_uorr4router_free: (a: number, b: number) => void;
export const init_wasm: () => void;
export const uorr4router_calculate_resonance: (a: number, b: number, c: number) => any;
export const uorr4router_compile_thought: (a: number, b: number, c: number) => any;
export const uorr4router_connection_drift: (a: number) => number;
export const uorr4router_evolve_state: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const uorr4router_execute_zkp_phase_reset: (a: number) => [number, number];
export const uorr4router_export_state: (a: number) => [number, number];
export const uorr4router_generate_geometric_response: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => any;
export const uorr4router_get_active_streams: (a: number) => any;
export const uorr4router_get_angle_x: (a: number) => number;
export const uorr4router_get_angle_y: (a: number) => number;
export const uorr4router_get_expert_counts: (a: number) => [number, number];
export const uorr4router_get_semantic_map_points: (a: number) => any;
export const uorr4router_get_top_resonances: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const uorr4router_get_vocab_size: (a: number) => number;
export const uorr4router_import_state: (a: number, b: number, c: number) => [number, number];
export const uorr4router_index_corpus: (a: number, b: number, c: number, d: number, e: number) => number;
export const uorr4router_index_sentence: (a: number, b: number, c: number, d: number, e: number) => void;
export const uorr4router_inject_thought_stream: (a: number, b: number, c: number) => any;
export const uorr4router_is_aligned: (a: number) => number;
export const uorr4router_kill_switch_threshold: (a: number) => number;
export const uorr4router_new: (a: number) => number;
export const uorr4router_reset_brain: (a: number, b: number, c: number) => void;
export const uorr4router_route_query_to_manifold: (a: number, b: number, c: number, d: number, e: number) => any;
export const uorr4router_set_angle_x: (a: number, b: number) => void;
export const uorr4router_set_angle_y: (a: number, b: number) => void;
export const uorr4router_update_drift_physics: (a: number, b: number, c: number) => [number, number];
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
