#!/usr/bin/env python3
"""Independent PR1340 audit: saved bytes/events and elementary recorded-state algebra; no model runs."""
import collections,hashlib,json,pathlib,struct,subprocess
import blake3
P=pathlib.Path;BASE=P('/Users/casey.allard/uor-r4/.uor-models/realtext-prior-2026-09-20');ROOT=BASE/'grounded-session-4';REPO=P('/Users/casey.allard/uor-r4/.worktrees/grounded-dependent-session');HEAD='17d5072c651a0574ff441309b05611fd399cbbec'
sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(p.read_text());out={'schema':'uor-r4.pr1340-independent-evidence-audit/1','scope':'Read-only saved event and artifact audit with exact integer Q8 equality checks on recorded pre/post states. No fitting, model inference, executable invocation, build or sealed-root mutation.','submitted_head':HEAD,'roots':{},'counts':{},'report_checks':{}}
for root in sorted(BASE.glob('grounded-session-*')):
 r=load(root/'result.json');m=load(root/'manifest.json');actual={str(p.relative_to(root)) for p in root.rglob('*') if p.is_file()}-{'manifest.json'};listed={x['path'] for x in m['files']};out['roots'][root.name]={'listed_files':len(listed),'missing':sorted(listed-actual),'unlisted':sorted(actual-listed),'seal_errors':[x['path'] for x in m['files'] if len((root/x['path']).read_bytes())!=x['bytes'] or blake3.blake3((root/x['path']).read_bytes()).hexdigest()!=x['blake3']],'source_receipt':r['running_source'],'source_hash_matches_submitted':{x['path']:sha(subprocess.check_output(['git','show',HEAD+':'+x['path']],cwd=REPO))==x['sha256'] for x in r['running_source']['source_files']},'result_sha256':sha((root/'result.json').read_bytes()),'elapsed_s':r['elapsed_s'],'artifact_bytes':{p.name:p.stat().st_size for p in (root/'artifacts').iterdir()},'reported_panel1':r['panel1_program_completion'],'reported_chain_counts':{k:r.get('panel2_dependent_chain',{}).get(k) for k in ['chains','first_correct','second_selection_correct','answer_correct','resumed_identical']},'retained_bytes':sum(p.stat().st_size for p in root.rglob('*') if p.is_file())}
r=load(ROOT/'result.json');rows=r['panel1_events'];a=load(ROOT/'attempt.json');exe=P(a['argv'][0]);out['primary_provenance']={'executable':str(exe),'sha256':sha(exe.read_bytes()) if exe.exists() else None,'matches_recorded':sha(exe.read_bytes())==r['running_source']['executable_sha256'] if exe.exists() else False,'all_source_hashes_match':all(out['roots'][ROOT.name]['source_hash_matches_submitted'].values()),'note':'Recorded clean85df1739 Git stamp is the parent, not the new source. Individual source-file hashes are the usable submitted-source identity.'}
# Parse and measure the actual serialized factorization.
b=(ROOT/'artifacts/grounded_factorization.rlgf').read_bytes();c=0
def take(n):
 global c
 z=b[c:c+n];assert len(z)==n;c+=n;return z
def u32():return struct.unpack('<I',take(4))[0]
assert take(4)==b'RLGF';version=u32();cyclic=bool(take(1)[0]);ref=u32();domains=[];codes=[]
for _ in range(3):n=u32();domains.append([u32() for _ in range(n)])
for _ in range(3):n=u32();codes.append(list(take(n)))
assert c==len(b)
gf={'version':version,'cyclic':cyclic,'reference_outcome':ref,'action_domain':domains[0],'outcome_domain':domains[1],'payload_domain':domains[2],'action_codes':codes[0],'outcome_states':codes[1],'payload_states':codes[2],'serialized_bytes':len(b),'sha256':sha(b),'reported_parameter_bytes':102,'actual_plain_parameter_token_and_code_bytes':sum(map(len,codes))+4*sum(map(len,domains))}
A=dict(zip(domains[0],codes[0]));Z=dict(zip(domains[1],codes[1]));E=dict(zip(domains[2],codes[2]));invZ={v:k for k,v in Z.items()};finite=load(ROOT/'artifacts/finite_transition.json');fi={(x,y):z for x,y,z in finite['initial']};fr={(x,y):z for x,y,z in finite['recurrent']};out['artifacts']={'grounded_factorization':gf,'finite_transition':{'bytes':(ROOT/'artifacts/finite_transition.json').stat().st_size,'sha256':sha((ROOT/'artifacts/finite_transition.json').read_bytes()),'initial_entries':len(fi),'recurrent_entries':len(fr)},'fitted_shared_recurrence':{'retained':False,'reported_bytes':370},'session_snapshot':{'retained':False}}
by=collections.defaultdict(list)
for x in rows:by[x['arm'],x['split']].append(x)
complete=lambda x:x['stopped'] and x['tokens']==x['expected'];correct=lambda x:x['read'] and x['payload_seq_abs'] is not None and x['payload_seq_abs'][1]==x['intended_payload_abs'] and x['selected_payload']==x['intended_payload']
for (arm,split),xs in by.items():
 seqs=collections.defaultdict(list)
 for x in xs:seqs[tuple(x['observed_primitives'])].append(x)
 out['counts'][arm+'/'+split]={'items':len(xs),'complete':sum(map(complete,xs)),'token_hits':sum(sum(j<len(x['tokens']) and x['tokens'][j]==y for j,y in enumerate(x['expected'])) for x in xs),'token_total':sum(len(x['expected']) for x in xs),'stopped_correctly':sum(x['stopped'] and len(x['tokens'])==len(x['expected']) for x in xs),'correct_sources':sum(map(correct,xs)),'correct_source_complete':sum(correct(x) and complete(x) for x in xs),'wrong_source_complete':sum(not correct(x) and complete(x) for x in xs),'terminal_counts':dict(collections.Counter(x['steps'][-1]['kind'] for x in xs)),'sequence_count':len(seqs),'sequences_all_values_complete':sum(all(map(complete,z)) for z in seqs.values()),'complete_flags_match':all(x['complete']==complete(x) for x in xs),'actual_token_events_match':all(x['tokens']==[s['emitted'] for s in x['steps'] if s['kind']=='Emit'] for x in xs),'observed_instruction_span_matches':all(x['observed_primitives']==x['prefix'][x['instruction_start']:-2] for x in xs),'source_ref_matches_prefix':all(x['payload_seq_abs'] is not None and x['source_seq_abs'] is not None and x['source_seq_abs'][0]==x['payload_seq_abs'][0] and x['source_seq_abs'][1]+1==x['payload_seq_abs'][1] and x['prefix'][x['payload_seq_abs'][1]]==x['selected_payload'] for x in xs if x['read'])}
for x in r['panel1_program_completion']:
 k=x['arm']+'/'+x['split'];out['report_checks'][k]={f:out['counts'][k][f]==x[f] for f in ['items','complete','token_hits','token_total','stopped_correctly']}
out['all_reported_counts_match']=all(all(v.values()) for v in out['report_checks'].values())
# Integer Hamilton arithmetic verifies recorded state equalities in the 8 signed-axis roots.
# Canonical order from embedding.rs is axis0..3, sign[-1,+1], so identity is index1.
q=[tuple(sign if j==axis else 0 for j in range(4)) for axis in range(4) for sign in (-1,1)]
def mul(x,y):
 a,b,c,d=q[x];e,f,g,h=q[y];return q.index((a*e-b*f-c*g-d*h,a*f+b*e+c*h-d*g,a*g-b*h+c*e+d*f,a*h+b*g-c*f+d*e))
state_checks=[]
for x in rows:
 if x['arm']!='grounded_factorization':continue
 for s in x['steps']:
  if s['kind']=='Emit':state_checks.append({'split':x['split'],'product_matches':mul(A[s['primitive']],s['pre_state'])==s['post_state'],'label_matches':invZ[s['post_state']]==s['emitted'],'target_matches':s['emitted']==s['expected']})
dev=by['grounded_factorization','dev'];init=collections.defaultdict(set);recur=collections.defaultdict(set)
for x in dev:
 for j,(p,y) in enumerate(zip(x['observed_primitives'],x['expected'])):
  if j==0:init[x['intended_payload'],p].add(y)
  else:recur[x['expected'][j-1],p].add(y)
out['factorization_audit']={'all_codes_in_canonical_q8':all(0<=x<8 for cs in codes for x in cs),'action_codes_injective':len(set(codes[0]))==len(codes[0]),'outcome_states_injective':len(set(codes[1]))==len(codes[1]),'gauge_reference_is_identity':Z[ref]==1,'recorded_emit_steps':len(state_checks),'all_recorded_products_match':all(x['product_matches'] for x in state_checks),'all_recorded_labels_match_artifact':all(x['label_matches'] for x in state_checks),'dev_steps':sum(x['split']=='dev' for x in state_checks),'dev_steps_correct':sum(x['split']=='dev' and x['target_matches'] for x in state_checks),'unique_initial_pairs':len(init),'unique_recurrent_pairs':len(recur),'initial_observation_conflicts':sum(len(v)>1 for v in init.values()),'recurrent_observation_conflicts':sum(len(v)>1 for v in recur.values()),'all_unique_initial_products_match':all(all(mul(A[p],E[v])==Z[y] for y in ys) for (v,p),ys in init.items()),'all_unique_recurrent_products_match':all(all(mul(A[p],Z[prev])==Z[y] for y in ys) for (prev,p),ys in recur.items()),'finite_initial_exactly_dev':len(fi)==len(init) and all(fi.get(k) in v for k,v in init.items()),'finite_recurrent_exactly_dev':len(fr)==len(recur) and all(fr.get(k) in v for k,v in recur.items()),'initial_agreement_note':'32 checks consist of4 first assignments and28 agreement checks; reported28 agreements are not4 failures.','method_scope':'Observed complete regular order8 action explicitly factored into a supplied witnessed Q8 subgroup; no hidden fixture codes read by fitter. This is exact structured compression of supplied transition supervision, not general statistical language learning.'}
out['loaded_object_audit']={'gf_exported_reloaded_equal':True,'gf_loaded_used_for_panel1':False,'gf_loaded_used_for_chain':False,'finite_exported_reloaded':True,'finite_loaded_used_for_panel1':False,'fitted_exported_reloaded':False,'source_detail':'Scoring closures use gf and finite; gf_loaded/finite_loaded are unused; fitted serves in memory and is not retained. GF equality check gives parameter-parity support but not actual loaded-candidate serving.'}
out['comparison_settings']={'current_fitted_recurrence':{'fit_items':288,'outer_probe_items':0,'passes':3,'restarts':2,'seed':0xC0F40001,'dev_complete':248},'previous_pr1339_recurrence':{'fit_items':144,'outer_probe_items':144,'passes':3,'restarts':6,'seed':0xC0F30001,'dev_complete':186},'interpretation':'248/288 is a newly refitted comparator with different calibration/probe/restart/seed settings, not a replay of the previous artifact. Both use the same total supervised development population.'}
# Recount chain outputs and actual selected payload positions using the source-declared record order.
chain=r['panel2_dependent_chain'];outcomes=domains[1];values=domains[2];keys=[x['key1'] for x in chain['rows']];p1=domains[0][0];p2=domains[0][1];chain_audit=[]
for j,x in enumerate(chain['rows']):
 ob=x['observed'];first=fi[values[j],p1];idx=outcomes.index(first);sv=values[idx%len(values)];ans=fi[sv,p2];first_abs=3*j+2;second_abs=3*len(keys)+3*idx+2
 chain_audit.append({'key1':x['key1'],'first_matches_declared_dev_transition':ob['first']==first,'second_query_uses_first':ob['second_query']==ob['first'],'second_payload_correct':ob['second_payload']==sv,'second_exact_payload_occurrence_correct':ob['second_source_abs']==second_abs,'first_exact_payload_occurrence_correct':ob['first_source_abs']==first_abs,'answer_correct':ob['answer']==ans,'expected_fields_match_independent_dev_table':x['expected_first']==first and x['expected_second_value']==sv and x['expected_answer']==ans,'emitted_answer_matches':ob['emitted']==[ob['answer']],'terminal':ob['terminal'],'reported_first_lease_is_actual_second':ob['first_lease']==[1,second_abs,sv],'resume_identical_reported':x['resumed_identical']})
out['chain_recount']={'chains':len(chain_audit),'first_correct':sum(x['first_matches_declared_dev_transition'] for x in chain_audit),'first_exact_occurrences_correct':sum(x['first_exact_payload_occurrence_correct'] for x in chain_audit),'second_exact_occurrences_correct':sum(x['second_exact_payload_occurrence_correct'] for x in chain_audit),'answers_correct':sum(x['answer_correct'] for x in chain_audit),'rows':chain_audit,'label_and_source_payload_domains_disjoint':not bool(set(outcomes)&set(values)),'answer_tokens_present_as_other_evidence_keys':all(x['observed']['answer'] in outcomes for x in chain['rows']),'scope':'All4 chains use one authored36-token evidence bank, fixed2-step program, supplied query role/key, and outcomes already grounded in development. No independent heldout dependency population.'}
# Counterfactual mutation scope: rebuilding alt_vals also mutates every hop2 record using value0.
base_payloads=values+[values[i%4] for i in range(8)];altvals=values.copy();altvals[0]=values[1];alt_payloads=altvals+[altvals[i%4] for i in range(8)];changed=[3*i+2 for i,(a,b) in enumerate(zip(base_payloads,alt_payloads)) if a!=b];ctrl=chain['controls'];alt=ctrl['changed_first_source']['observed_b'];base=ctrl['changed_first_source']['observed_a'];original_second_idx=(alt['second_source_abs']-3*len(keys)-2)//3;untouched_second_value=values[original_second_idx%4]
out['controls_audit']={'changed_first_source_actual_changed_payload_positions':changed,'changed_first_source_also_changes_new_second_selected_record':alt['second_source_abs'] in changed,'new_second_query_is_new_first':alt['second_query']==alt['first'],'second_occurrence_changed':alt['second_source_abs']!=base['second_source_abs'],'reported_answer_changed':alt['answer']!=base['answer'],'unchanged_second_record_value_would_be':untouched_second_value,'declared_dev_label_for_unchanged_second_value':fi[untouched_second_value,p2],'reported_alt_second_value':alt['second_payload'],'reported_alt_answer':alt['answer'],'interpretation':'Final answer intervention confounded: abs2,14,26 changed, including selected second record26. First/query/occurrence changes are real; isolated first-source causal answer test NOT_RUN.','source_removed':ctrl['required_source_removed'],'read_disabled':ctrl['read_disabled'],'distractor_preservation_reported':ctrl['irrelevant_distractor_added'],'distractor_full_trace_retained':False,'resume_snapshot_bytes_retained':False,'resume_scope':'Runner roundtrips immediately after each read and after final stop; saved result retains equality booleans but not serialized snapshots or separate resumed trajectories. Interleaving is unit-test scope only.','lease_scope':'lease_is_live helper exists but is never invoked by actual chain read/apply/emit/resume; first_lease field is overwritten second lease. No observed stale-lease enforcement, same-value overwrite, reset, alternate-model restoration or interleaved ring intervention in saved run.'}
inputs={'E':BASE/'head-projection-3/corrected/empirical.cpl2','S':BASE/'s-attribution-3/corrected/separable_older_query_read.cpx3','selector':BASE/'relational-learning-4/artifacts/relational_ctx.rlr2'};out['serving_footprint_scope']={'retained_factorization_bytes':137,'retained_finite_bytes':1668,'serialized_ratio_finite_to_factorization':1668/137,'shared_loaded_input_artifacts':{k:{'path':str(p),'bytes':p.stat().st_size,'sha256':sha(p.read_bytes())} for k,p in inputs.items()},'group_product_table_payload_bytes':120*128,'group_inverse_table_payload_bytes':120,'whole_path_memory_or_energy_measured':False,'note':'The component compresses the JSON control; total serving includes shared E/S/selector artifacts, geometric tables, local logits, ring, session allocations and tokenizer.102 is not serialized or complete-path bytes; binary-vs-JSON serialization is an unequal encoding comparison.'}
out['resources']={'four_saved_run_elapsed_s':sum(v['elapsed_s'] for v in out['roots'].values()),'primary_elapsed_s':r['elapsed_s'],'retained_report_bytes':sum(v['retained_bytes'] for v in out['roots'].values()),'model_runs_by_auditor':0,'energy':'UNAVAILABLE'}
out['limits']=['Exposed authored fixture, complete transition supervision, supplied primitive/record grammar, exact-key dependent retrieval; no learned semantic control or general language.','New gs_serve_with reads detached item.primitives rather than st_instructions prefix slice; currently identical fixture copies, but the previously repaired causal boundary regressed.','No retained fitted comparator or session snapshot; loaded model variables unused downstream.','Source lease helper is not enforced at transitions; serialized session lacks model identity and permits unbounded/out-of-domain state without validation.','No complete pipeline performance/energy or equal-byte comparator measurement.'];out['script_sha256']=sha(P(__file__).read_bytes());dest=P('/tmp/uor-pr1340-evidence-audit.json');dest.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'output':str(dest),'primary_provenance':out['primary_provenance'],'all_reported_counts_match':out['all_reported_counts_match'],'counts':out['counts'],'factorization':out['factorization_audit'],'chain':out['chain_recount'],'controls':out['controls_audit'],'footprint':out['serving_footprint_scope'],'resources':out['resources']},indent=2))
