#!/usr/bin/env python3
"""Read-only independent audit of corrected PR1340 saved artifacts, outputs and checkpoints."""
import collections,hashlib,json,pathlib,struct
import blake3
P=pathlib.Path;B=P('/Users/casey.allard/uor-r4/.uor-models/realtext-prior-2026-09-20');R=B/'grounded-session-principal-1';REPO=P('/Users/casey.allard/.codex/worktrees/takeover-research-reconciliation/uor-r4');sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(p.read_text())
if not(R/'manifest.json').exists():raise SystemExit('Corrected root not sealed; no audit created.')
r=load(R/'result.json');m=load(R/'manifest.json');attempt=load(R/'attempt.json');actual={str(p.relative_to(R)) for p in R.rglob('*') if p.is_file()}-{'manifest.json'};listed={x['path'] for x in m['files']};exe=P(attempt['argv'][0]);out={'schema':'uor-r4.pr1340-corrected-exposed-replay-independent-audit/1','scope':'Saved output recount, artifact/snapshot byte and identity verification, exact integer Q8 checks on recorded states. No new predictor execution, fit, build or sealed-root mutation. Corrected exposed regression, not fresh qualification.','root':str(R),'integrity':{'listed_files':len(listed),'missing':sorted(listed-actual),'unlisted':sorted(actual-listed),'seal_errors':[x['path'] for x in m['files'] if len((R/x['path']).read_bytes())!=x['bytes'] or blake3.blake3((R/x['path']).read_bytes()).hexdigest()!=x['blake3']],'source_hash_matches':{x['path']:sha((REPO/x['path']).read_bytes())==x['sha256'] for x in r['running_source']['source_files']},'executable':str(exe),'executable_sha256':sha(exe.read_bytes()) if exe.exists() else None,'executable_matches':sha(exe.read_bytes())==r['running_source']['executable_sha256'] if exe.exists() else False,'result_sha256':sha((R/'result.json').read_bytes())},'counts':{},'report_checks':{},'artifacts':{},'checkpoints':{}}
class Reader:
 def __init__(self,b):self.b=b;self.c=0
 def take(self,n):z=self.b[self.c:self.c+n];assert len(z)==n;self.c+=n;return z
 def u32(self):return struct.unpack('<I',self.take(4))[0]
 def end(self):assert self.c==len(self.b)
def gf_parse(p):
 b=p.read_bytes();s=Reader(b);assert s.take(4)==b'RLGF';v=s.u32();cyc=bool(s.take(1)[0]);ref=s.u32();dom=[];codes=[]
 for _ in range(3):n=s.u32();dom.append([s.u32() for _ in range(n)])
 for _ in range(3):n=s.u32();codes.append(list(s.take(n)))
 s.end();return {'bytes':len(b),'sha256':sha(b),'version':v,'cyclic':cyc,'reference_outcome':ref,'action_domain':dom[0],'outcome_domain':dom[1],'payload_domain':dom[2],'action_codes':codes[0],'outcome_states':codes[1],'payload_states':codes[2]}
def frame_parse(b):
 s=Reader(b);assert s.take(4)==b'RLSF';v=s.u32();lease=[s.u32(),s.u32(),s.u32()] if s.take(1)[0] else None;state=s.u32() if s.take(1)[0] else None;outcome=s.u32() if s.take(1)[0] else None;phase=s.take(1)[0];n=s.u32();emitted=[s.u32() for _ in range(n)];terminal=s.take(1)[0];s.end();return {'version':v,'bytes':len(b),'lease':lease,'state':state,'outcome':outcome,'phase':phase,'emitted':emitted,'terminal_tag':terminal}
gf=gf_parse(R/'artifacts/grounded_factorization.rlgf');out['artifacts']['grounded_factorization']=gf;A=dict(zip(gf['action_domain'],gf['action_codes']));Z=dict(zip(gf['outcome_domain'],gf['outcome_states']));E=dict(zip(gf['payload_domain'],gf['payload_states']));invZ={v:k for k,v in Z.items()};finite=load(R/'artifacts/finite_transition.json');out['artifacts']['finite_transition_control']={'bytes':(R/'artifacts/finite_transition.json').stat().st_size,'sha256':sha((R/'artifacts/finite_transition.json').read_bytes()),'initial_entries':len(finite['initial']),'recurrent_entries':len(finite['recurrent'])};out['artifacts']['fitted_shared_recurrence']={'bytes':(R/'artifacts/fitted_recurrence.rlst').stat().st_size,'sha256':sha((R/'artifacts/fitted_recurrence.rlst').read_bytes())}
for a in r['loaded_artifacts']:
 out['artifacts'][a['arm']]['recorded_hash_matches']=out['artifacts'][a['arm']]['sha256']==a['sha256'];out['artifacts'][a['arm']]['recorded_size_matches']=out['artifacts'][a['arm']]['bytes']==a['serialized_bytes'];out['artifacts'][a['arm']]['actual_loaded_object_used_reported']=a['actual_loaded_object_used']
rows=r['panel1_events'];by=collections.defaultdict(list)
for x in rows:by[x['arm'],x['split']].append(x)
complete=lambda x:x['stopped'] and x['tokens']==x['expected'];correct=lambda x:x['read'] and x['payload_seq_abs'] is not None and x['payload_seq_abs'][1]==x['intended_payload_abs'] and x['selected_payload']==x['intended_payload']
old=load(B/'grounded-session-4/result.json');og={(x['arm'],x['item_id']):x for x in old['panel1_events']}
for (arm,split),xs in by.items():
 out['counts'][arm+'/'+split]={'items':len(xs),'complete':sum(map(complete,xs)),'token_hits':sum(sum(j<len(x['tokens']) and x['tokens'][j]==y for j,y in enumerate(x['expected'])) for x in xs),'token_total':sum(len(x['expected']) for x in xs),'stopped_correctly':sum(x['stopped'] and len(x['tokens'])==len(x['expected']) for x in xs),'correct_sources':sum(map(correct,xs)),'correct_source_complete':sum(correct(x) and complete(x) for x in xs),'terminal_counts':dict(collections.Counter(x['steps'][-1]['kind'] for x in xs)),'complete_flags_match':all(x['complete']==complete(x) for x in xs),'token_step_events_match':all(x['tokens']==[s['emitted'] for s in x['steps'] if s['kind']=='Emit'] for x in xs),'instruction_span_matches':all(x['observed_primitives']==x['prefix'][x['instruction_start']:-2] for x in xs),'tokens_identical_original_all_items':all(x['tokens']==og[arm,x['item_id']]['tokens'] for x in xs),'expected_identical_original_all_items':all(x['expected']==og[arm,x['item_id']]['expected'] for x in xs)}
for a in r['panel1_program_completion']:
 k=a['arm']+'/'+a['split'];out['report_checks'][k]={f:out['counts'][k][f]==a[f] for f in ['items','complete','token_hits','token_total','stopped_correctly']}
out['all_report_counts_match']=all(all(v.values()) for v in out['report_checks'].values())
# Development-label lookup used only to independently check declared evaluation expectations.
fi=collections.defaultdict(set);fr=collections.defaultdict(set)
for x in by['grounded_factorization','dev']:
 for j,(p,y) in enumerate(zip(x['observed_primitives'],x['expected'])):
  if j==0:fi[x['intended_payload'],p].add(y)
  else:fr[x['expected'][j-1],p].add(y)
assert all(len(v)==1 for v in fi.values());fi={k:next(iter(v)) for k,v in fi.items()}
q=[tuple(sign if j==axis else 0 for j in range(4)) for axis in range(4) for sign in (-1,1)]
def mul(x,y):
 a,b,c,d=q[x];e,f,g,h=q[y];return q.index((a*e-b*f-c*g-d*h,a*f+b*e+c*h-d*g,a*g-b*h+c*e+d*f,a*h+b*g-c*f+d*e))
gsteps=[s for x in rows if x['arm']=='grounded_factorization' for s in x['steps'] if s['kind']=='Emit'];out['factorization_checks']={'recorded_emit_steps':len(gsteps),'all_recorded_q8_products_match':all(mul(A[s['primitive']],s['pre_state'])==s['post_state'] for s in gsteps),'all_labels_match_recorded_state':all(invZ[s['post_state']]==s['emitted'] for s in gsteps),'all_672_dev_steps_correct':out['counts']['grounded_factorization/dev']['token_hits']==672,'unique_initial_transitions':len(fi),'unique_recurrent_transitions':len(fr)}
chain=r['panel2_dependent_chain'];out['chain_rows']=[]
def expected(ch):
 ev=ch['evidence'];request=ch['request'];ps=request['primitives'];lookup={ev[i+1]:(i+2,ev[i+2]) for i in range(0,len(ev),3)};first=lookup.get(request['key'])
 if first is None:return {'first':None,'first_payload_abs':None,'second_payload_abs':None,'second_payload':None,'answer':None}
 first_y=fi[first[1],ps[0]];second=lookup.get(first_y)
 return {'first':first_y,'first_payload_abs':first[0],'second_payload_abs':second[0] if second else None,'second_payload':second[1] if second else None,'answer':fi[second[1],ps[1]] if second else None}
def chaincheck(ch):
 exp=expected(ch);o=ch['observed'];return {'expected_independent':exp,'first_correct':o.get('first')==exp['first'],'first_occurrence_correct':o.get('first_source_abs')==exp['first_payload_abs'],'second_occurrence_correct':o.get('second_source_abs')==exp['second_payload_abs'],'second_payload_correct':o.get('second_payload')==exp['second_payload'],'answer_correct':o.get('answer')==exp['answer'],'answer':o.get('answer'),'first_snapshot':o.get('first_snapshot'),'second_snapshot':o.get('second_snapshot'),'terminal':o.get('terminal'),'resume_reported':ch.get('resumed_identical')}
for x in chain['rows']:
 ch=x['actual'];z=chaincheck(ch);z['key1']=x['key1'];z['expected_report_matches']=all(x['expected'].get(k)==v for k,v in z['expected_independent'].items());out['chain_rows'].append(z)
out['chain_counts']={'chains':len(out['chain_rows']),'first_correct':sum(z['first_correct'] and z['first_occurrence_correct'] for z in out['chain_rows']),'second_correct':sum(z['second_payload_correct'] and z['second_occurrence_correct'] for z in out['chain_rows']),'answer_correct':sum(z['answer_correct'] for z in out['chain_rows']),'reported_resume_identical':sum(z['resume_reported'] is True for z in out['chain_rows'])}
for p in sorted((R/'frames').glob('*.json')):
 cp=load(p);bs=bytes(cp['frame_bytes']);f=frame_parse(bs);idx=int(p.name.split('-')[1]);ch=chain['rows'][idx]['actual'];ob=ch['observed'];first=p.stem.endswith('after-first');expected_snap=ob['first_snapshot'] if first else ob['second_snapshot'];expected_state=ob['first_state'] if first else ob['final_state'];expected_outcome=ob['first'] if first else ob['answer']
 out['checkpoints'][p.name]={'json_sha256':sha(p.read_bytes()),'frame':f,'frame_hash_matches':sha(bs)==cp['frame_sha256'],'model_hash_matches':cp['model_sha256']==gf['sha256'],'group_hash_matches':cp['group_digest']==r['inputs']['group_digest'],'tokenizer_hash_matches':cp['tokenizer_sha256']==r['inputs']['tokenizer_derived'],'stage_matches':cp['stage']==('after_first_compute_before_second_read' if first else 'after_second_compute_before_emit'),'snapshot_matches_exact_selected_evidence':f['lease']==expected_snap and ch['evidence'][f['lease'][1]]==f['lease'][2],'state_matches_uninterrupted':f['state']==expected_state,'outcome_matches_uninterrupted':f['outcome']==expected_outcome,'outcome_matches_model_state':invZ.get(f['state'])==f['outcome'],'before_emit_and_unterminated':f['emitted']==[] and f['terminal_tag']==0,'phase_after_one_computation':f['phase']==1}
out['all_checkpoint_checks_pass']=all(all(v for k,v in cp.items() if k not in ['json_sha256','frame']) for cp in out['checkpoints'].values())
ctrl=chain['controls'];change=ctrl['changed_first_source'];ca=change['a'];cb=change['b'];changed=[i for i,(a,b) in enumerate(zip(ca['evidence'],cb['evidence'])) if a!=b];out['controls']={'single_first_payload_change':{'changed_positions':changed,'exactly_one_first_payload':changed==[2],'all_hop2_records_preserved':ca['evidence'][12:]==cb['evidence'][12:],'a':chaincheck(ca),'b':chaincheck(cb),'reported_changed_positions_match':change['changed_positions']==changed},'distractor':{'base':chaincheck(ctrl['irrelevant_distractor_added']['base']),'changed':chaincheck(ctrl['irrelevant_distractor_added']['changed']),'observed_original_evidence_preserved':ctrl['irrelevant_distractor_added']['changed']['evidence'][:-3]==ctrl['irrelevant_distractor_added']['base']['evidence']}}
for name in ['required_first_source_removed','required_second_source_removed','read_disabled','second_read_disabled','first_computation_disabled','second_payload_update_disabled']:
 ch=ctrl[name];out['controls'][name]={'recount':chaincheck(ch),'observed':ch['observed'],'request':ch['request'],'evidence':ch['evidence']}
out['control_limit']='The first primitive is the observed identity action. Disabling its update is an identity negative control and can preserve all outputs; this fixture does not establish necessity of a nonidentity first computation. Other controls retain supplied two-hop schedule.'
out['resume_scope']={'saved_frames':len(out['checkpoints']),'first_compute_before_second_read':sum(k.endswith('after-first.json') for k in out['checkpoints']),'second_compute_before_emit':sum(k.endswith('after-second.json') for k in out['checkpoints']),'actual_resume_equality_scope':'Source confirms checkpoint disk reload then continuation helper with no first source/key/primitive argument; saved bytes independently match uninterrupted first/final states. Full resumed continuation equality is asserted by runner; separate resumed event trace not retained.','snapshot_semantics':'Copied content snapshot acquired from exact live owning-ring occurrence; content intentionally survives later origin eviction. Origin liveness is separate diagnostic, not required after copying. Ring-local references are not globally durable identities.'}
out['source_receipt']=r['running_source'];out['resource_scope']={'model_elapsed_s':r['elapsed_s'],'auditor_new_model_runs':0,'energy':'UNAVAILABLE','debug_performance_not_serving_benchmark':True};out['limits']=['Exposed authored circuit, supplied record layout and two-hop program; no independent heldout session population.','All model artifacts now retained and source confirms actual loaded objects used; current data remain same original exposed panels.','Checkpoint wrapper binds model/group/tokenizer and phase; no learned scheduler, semantic parser, general reasoning, ordinary prose or coding qualification.','Component137 bytes is not full serving path, and1668-byte JSON table is not encoding-normalized comparator.','No whole-path energy or optimized useful-token latency measurement.'];out['script_sha256']=sha(P(__file__).read_bytes());dest=P('/tmp/uor-pr1340-corrected-replay-audit.json');dest.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'output':str(dest),'integrity':out['integrity'],'all_report_counts_match':out['all_report_counts_match'],'counts':out['counts'],'factorization_checks':out['factorization_checks'],'chain_counts':out['chain_counts'],'all_checkpoint_checks_pass':out['all_checkpoint_checks_pass'],'checkpoints':out['checkpoints'],'controls':out['controls'],'resource_scope':out['resource_scope']},indent=2))
